import { bankGenerate, type BioBank } from './biologieBank'
import type { Topic } from './types'

const fact = (
  concept: string,
  prompt: string,
  answer: string,
  wrong: [string, string, string],
  explanation: string,
  wissen: string,
  gap: string,
  gapAccepted: string[],
) => ({ concept, prompt, answer, wrong, explanation, wissen, gap, gapAccepted })

const pair = (concept: string, term: string, meaning: string, wissen: string) => ({
  concept,
  term,
  meaning,
  wissen,
})

const tf = (
  concept: string,
  statement: string,
  correct: boolean,
  explanation: string,
  wissen: string,
) => ({ concept, statement, correct, explanation, wissen })

const sort = (
  concept: string,
  question: string,
  labels: string[],
  explanation: string,
  wissen: string,
) => ({ concept, question, labels, explanation, wissen })

const neuzeit: BioBank = {
  quelle: 'Wikipedia: Frühe Neuzeit',
  url: 'https://de.wikipedia.org/wiki/Fr%C3%BChe_Neuzeit',
  conceptPrefix: 'ge:k7:neuzeit',
  facts: [
    fact(
      'renaissance',
      'Wofür steht die Renaissance?',
      'Für die Wiederentdeckung antiker Bildungsideale und neue Formen von Kunst und Denken',
      ['Für die Einführung des Lehnswesens', 'Für die Gründung des Völkerbunds', 'Für die Abschaffung aller Städte'],
      'Die Renaissance veränderte das Welt- und Menschenbild.',
      'Die Renaissance begann in Italien und griff auf antike Vorbilder zurück. Kunst, Architektur und Wissenschaft veränderten sich deutlich. Der Mensch und seine Fähigkeiten rückten stärker in den Mittelpunkt als im traditionellen mittelalterlichen Denken.',
      'Die ___ griff auf antike Bildungsideale zurück.',
      ['Renaissance'],
    ),
    fact(
      'humanismus',
      'Was betonte der Humanismus besonders?',
      'Bildung, Sprachen, kritisches Lesen und die Würde des Menschen',
      ['Nur militärische Erziehung von Rittern', 'Ausschließlich klösterliche Abschottung', 'Nur die Herrschaft des Adels über Bauern'],
      'Humanisten wollten Menschen durch Bildung formen.',
      'Der Humanismus war eine Bildungsbewegung der frühen Neuzeit. Humanisten lernten antike Sprachen, lasen Quellen kritisch und glaubten an die Formbarkeit des Menschen durch Bildung. Damit prägten sie Schule, Wissenschaft und Politik.',
      'Der Humanismus betonte besonders ___ und kritisches Lesen.',
      ['Bildung'],
    ),
    fact(
      'buchdruck',
      'Warum war der Buchdruck mit beweglichen Lettern so bedeutsam?',
      'Weil Texte schneller, günstiger und in größerer Zahl verbreitet werden konnten',
      ['Weil Bücher nur noch mündlich erzählt wurden', 'Weil Druck das Lesen unnötig machte', 'Weil nur Könige drucken durften'],
      'Der Buchdruck beschleunigte Wissensverbreitung.',
      'Johannes Gutenberg entwickelte im 15. Jahrhundert den Buchdruck mit beweglichen Metalllettern. Dadurch konnten Texte viel schneller vervielfältigt werden als durch Abschreiben. Das förderte Bildung, religiöse Debatten und die Ausbreitung neuer Ideen.',
      'Der Buchdruck machte die Verbreitung von ___ deutlich schneller.',
      ['Texten', 'Wissen'],
    ),
    fact(
      'kolumbus',
      'Warum gilt 1492 oft als Schlüsseljahr der Neuzeit?',
      'Weil Kolumbus Amerika erreichte und dadurch weltweite Verflechtungen zunahmen',
      ['Weil Rom erst dann gegründet wurde', 'Weil Ludwig XIV. die Magna Carta unterschrieb', 'Weil die Bauernkriege in Sachsen endeten'],
      'Entdeckungsfahrten erweiterten den europäischen Horizont stark.',
      'Mit der Fahrt von Kolumbus 1492 verstärkten sich Kontakte zwischen Europa, Amerika, Afrika und Asien. Diese Verbindungen brachten Handel, Wissen und Machtgewinne, aber auch Eroberung, Gewalt und Ausbeutung. Das macht Entdeckungen historisch ambivalent.',
      '1492 erreichte Kolumbus ___ und veränderte damit den Horizont Europas.',
      ['Amerika'],
    ),
    fact(
      'kompass',
      'Welche technischen Voraussetzungen halfen den Entdeckungsfahrten?',
      'Unter anderem Kompass, verbesserte Karten und seetüchtige Schiffe',
      ['Nur Ritterrüstungen und Burgen', 'Ausschließlich Dampfmaschinen', 'Nur Eisenbahnen und Telegrafen'],
      'Entdeckungsfahrten wurden durch Navigation und Schiffbau erleichtert.',
      'Fernfahrten über den Atlantik wurden durch technische und geografische Kenntnisse begünstigt. Kompass, Karten und neue Schiffstypen wie die Karavelle verbesserten Navigation und Sicherheit. Technik und Wissensdurst wirkten dabei zusammen.',
      'Entdeckungsfahrten wurden durch Kompass, Karten und geeignete ___ erleichtert.',
      ['Schiffe', 'Schiffstypen'],
    ),
    fact(
      'weltbild',
      'Wie veränderte sich in der Neuzeit das Weltbild vieler Europäer?',
      'Es wurde weiter, erforschender und weniger auf den eigenen Nahraum begrenzt',
      ['Es schrumpfte nur auf das Dorfleben', 'Es blieb völlig unverändert seit der Antike', 'Es wurde nur religiöser und ohne Naturbeobachtung'],
      'Neue Erfahrungen förderten ein offeneres Weltbild.',
      'Durch Reisen, Handel, Druck und Wissenschaft veränderte sich das Weltbild vieler Menschen. Fremde Räume und neue Erkenntnisse wurden wichtiger. Das bedeutete nicht, dass alte Vorstellungen verschwanden, aber neue Perspektiven gewannen an Gewicht.',
      'Das Weltbild wurde weiter und stärker auf ___ ausgerichtet.',
      ['Erforschung', 'Erkundung'],
    ),
    fact(
      'da-vinci',
      'Warum gilt Leonardo da Vinci als typische Gestalt der Renaissance?',
      'Weil er Kunst, Naturbeobachtung und technisches Denken verband',
      ['Weil er als Kurfürst Sachsen regierte', 'Weil er die Goldene Bulle verfasste', 'Weil er den Ersten Weltkrieg erklärte'],
      'Leonardo verkörpert das vielseitige Menschenbild der Epoche.',
      'Leonardo da Vinci war Maler, Forscher und Erfinder zugleich. Gerade diese Verbindung von Kunst und Naturstudium macht ihn zu einer Schlüsselfigur der Renaissance. Sie zeigt, wie stark die Epoche an menschliche Fähigkeiten glaubte.',
      'Leonardo da Vinci verband Kunst mit ___ und technischem Denken.',
      ['Naturbeobachtung'],
    ),
    fact(
      'amerika-folgen',
      'Welche Folge hatten die europäischen Entdeckungsfahrten für Amerika?',
      'Sie führten zu Eroberung, Kolonisierung und massiven Umbrüchen für indigene Gesellschaften',
      ['Sie ließen Amerika völlig unverändert', 'Sie beendeten jede Gewalt in Übersee', 'Sie führten sofort zur Gleichberechtigung aller Beteiligten'],
      'Entdeckungen waren für viele Menschen keine reine Erfolgsgeschichte.',
      'Die europäischen Entdeckungsfahrten hatten für indigene Gesellschaften in Amerika tiefgreifende Folgen. Eroberung, Krankheiten, Missionierung und Ausbeutung zerstörten bestehende Lebenswelten vielfach. Deshalb gehören zur Neuzeit nicht nur Fortschritt, sondern auch Gewalt und Herrschaft.',
      'Entdeckungsfahrten brachten in Amerika Kolonisierung und tiefgreifende ___.',
      ['Umbrüche', 'Veränderungen'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Renaissance',
      'Rückgriff auf die Antike in Kunst und Denken',
      'Die Renaissance griff antike Vorbilder auf und verband sie mit neuen künstlerischen Formen. So veränderte sie das Menschenbild der frühen Neuzeit.',
    ),
    pair(
      'p2',
      'Humanismus',
      'Bildungsbewegung mit Schwerpunkt auf Quellen und Sprachen',
      'Humanisten lasen antike Texte kritisch und betonten die Bildung des Menschen. Ihr Einfluss reichte tief in Schule und Wissenschaft.',
    ),
    pair(
      'p3',
      'Buchdruck',
      'Schnelle Vervielfältigung von Texten mit Lettern',
      'Der Buchdruck beschleunigte die Verbreitung von Wissen. Dadurch konnten neue Ideen viel rascher diskutiert werden.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Die Renaissance bedeutete nur, dass Europa im Mittelalter stehen blieb und sich geistig nicht veränderte.',
      false,
      'Gerade die Renaissance steht für neue Formen von Kunst, Bildung und Weltdeutung.',
      'Die Renaissance war eine Epoche kultureller und geistiger Erneuerung. Der Rückgriff auf die Antike verband sich mit neuen Beobachtungen, Forschungen und Ausdrucksformen. Deshalb markiert sie einen wichtigen Übergang zur Neuzeit.',
    ),
  ],
  sorts: [
    sort(
      's1',
      'Ordne grob chronologisch:',
      ['Renaissance und Humanismus', 'Buchdruck', 'Entdeckungsfahrten über den Atlantik'],
      'Alle drei Entwicklungen gehören in die frühe Neuzeit und verstärken sich gegenseitig.',
      'Renaissance, Humanismus, Buchdruck und Entdeckungsfahrten liegen eng beieinander und prägen die frühe Neuzeit. Neue Ideen, neue Medien und neue Räume greifen ineinander.',
    ),
  ],
}

const absolutismus: BioBank = {
  quelle: 'Wikipedia: Absolutismus',
  url: 'https://de.wikipedia.org/wiki/Absolutismus',
  conceptPrefix: 'ge:k7:absolutismus',
  facts: [
    fact(
      'absolutismus',
      'Was versteht man unter Absolutismus?',
      'Eine Herrschaftsform, in der der Monarch seine Macht stark zentralisiert',
      ['Eine direkte Demokratie aller Bürger', 'Die Herrschaft einer mittelalterlichen Zunft', 'Ein Bündnis unabhängiger Stadtstaaten'],
      'Im Absolutismus bündelt der König Macht am Hof und im Staat.',
      'Unter Absolutismus versteht man eine Herrschaftsform der frühen Neuzeit, in der Könige ihre Macht stark konzentrierten. Verwaltung, Heer und Hof wurden enger auf den Monarchen bezogen. In der Wirklichkeit blieb diese Macht dennoch durch Traditionen und Stände begrenzt.',
      'Absolutismus meint stark ___ Herrschaft beim Monarchen.',
      ['zentralisierte', 'gebündelte'],
    ),
    fact(
      'ludwig-xiv',
      'Warum gilt Ludwig XIV. als Symbol des Absolutismus?',
      'Weil er Frankreich lange regierte und den Hof von Versailles zur Machtdemonstration nutzte',
      ['Weil er die Weimarer Verfassung verfasste', 'Weil er die Reformation in Wittenberg auslöste', 'Weil er römischer Konsul der Antike war'],
      'Ludwig XIV. verkörpert höfische Pracht und zentralisierte Herrschaft.',
      'Ludwig XIV. regierte Frankreich im 17. und frühen 18. Jahrhundert. Er machte Versailles zum Mittelpunkt des Hofes und band den Adel an seine Person. Deshalb wird er oft als Muster eines absolutistischen Herrschers dargestellt.',
      'Ludwig XIV. nutzte den Hof von ___ zur Machtdemonstration.',
      ['Versailles'],
    ),
    fact(
      'versailles',
      'Welche politische Funktion hatte Versailles?',
      'Es war Residenz, Kontrollzentrum des Adels und Bühne königlicher Macht',
      ['Es war nur ein Handelslager für Gewürze', 'Es diente als Parlament der englischen Bürger', 'Es war ein Kloster ohne Hofleben'],
      'Der Hofstaat war Teil der Herrschaftsstrategie.',
      'Versailles war weit mehr als ein prunkvolles Schloss. Der Hof regelte Rang, Nähe und Zugang zum König und half so, den Adel zu kontrollieren. Repräsentation war im Absolutismus also selbst ein Mittel der Politik.',
      'Versailles war auch eine Bühne königlicher ___.',
      ['Macht', 'Herrschaft'],
    ),
    fact(
      'stehendes-heer',
      'Warum war ein stehendes Heer für absolutistische Staaten wichtig?',
      'Weil der Monarch damit Kriege führen und seine Herrschaft absichern konnte',
      ['Weil dadurch Parlamente überflüssig wurden', 'Weil Bauern dann keine Steuern zahlten', 'Weil Handel auf dem Meer unnötig wurde'],
      'Heer und Steuern gehörten eng zusammen.',
      'Absolutistische Herrschaft stützte sich auf ein dauerhaft verfügbares Heer. Um dieses zu finanzieren, brauchten Staaten Steuern und Verwaltung. Militär, Bürokratie und Königsmacht verstärkten sich dadurch gegenseitig.',
      'Ein stehendes Heer stärkte Kriegsfähigkeit und ___ des Monarchen.',
      ['Herrschaft'],
    ),
    fact(
      'merkantilismus',
      'Was wollte der Merkantilismus fördern?',
      'Staatlich gelenkte Wirtschaftskraft und Einnahmen des Staates',
      ['Die Abschaffung aller Zölle sofort', 'Nur Selbstversorgung ohne Handel', 'Ausschließlich freie Wahlen im Parlament'],
      'Wirtschaftspolitik sollte den Staat stärken.',
      'Im Merkantilismus griff der Staat gezielt in die Wirtschaft ein. Man wollte Ausfuhr fördern, Einfuhr begrenzen und Manufakturen stärken. Ziel war nicht wirtschaftliche Freiheit an sich, sondern mehr Reichtum und Macht des Staates.',
      'Der Merkantilismus sollte die ___ des Staates erhöhen.',
      ['Einnahmen', 'Wirtschaftskraft'],
    ),
    fact(
      'aufklaerung',
      'Wofür steht die Aufklärung?',
      'Für Vernunft, Kritik und das Prüfen von Herrschaft mit dem Verstand',
      ['Für bedingungslosen Gehorsam ohne Nachdenken', 'Für die Rückkehr zur Leibeigenschaft', 'Für die Herrschaft von Rittern und Burgen'],
      'Die Aufklärung hinterfragte Traditionen und Machtansprüche.',
      'Die Aufklärung war eine geistige Bewegung des 17. und 18. Jahrhunderts. Sie setzte auf Vernunft, Diskussion und Kritik an überlieferten Autoritäten. Dadurch wurden auch Staat, Kirche und Gesellschaft stärker hinterfragt.',
      'Die Aufklärung betonte ___ und Kritik.',
      ['Vernunft'],
    ),
    fact(
      'gewaltenteilung',
      'Welche Idee verband man in der Aufklärung mit Montesquieu?',
      'Die Gewaltenteilung',
      ['Die Alleinherrschaft des Königs', 'Die Rückkehr zum Lehnswesen', 'Die Kreuzzugsidee'],
      'Gewaltenteilung sollte Macht begrenzen.',
      'Montesquieu entwickelte die Vorstellung, staatliche Macht auf verschiedene Gewalten zu verteilen. Gesetzgebung, Regierung und Rechtsprechung sollten sich gegenseitig begrenzen. Diese Idee wurde für moderne Verfassungen sehr wichtig.',
      'Montesquieu verband Aufklärung mit der Idee der ___.',
      ['Gewaltenteilung'],
    ),
    fact(
      'widerspruch',
      'Wie verhielten sich Absolutismus und Aufklärung zueinander?',
      'Sie standen teils im Gegensatz, beeinflussten sich aber in manchen Reformen auch gegenseitig',
      ['Sie waren genau dasselbe', 'Sie hatten keinerlei Berührungspunkte', 'Die Aufklärung wollte nur mehr Hofzeremoniell'],
      'Geistesgeschichte und Herrschaft liefen nicht einfach parallel.',
      'Aufklärung und Absolutismus widersprachen sich oft, weil die Aufklärung Herrschaft kritisch prüfte. Gleichzeitig übernahmen manche Herrscher einzelne Reformideen. Deshalb ist das Verhältnis von absolutistischem Staat und Aufklärung spannungsreich, nicht schlicht.',
      'Zwischen Absolutismus und Aufklärung bestand ein ___ Verhältnis.',
      ['spannungsreiches', 'Spannungsverhältnis'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Absolutismus',
      'Stark zentralisierte Herrschaft des Monarchen',
      'Im Absolutismus bündelte der Monarch viele politische Mittel in seiner Hand. Dennoch blieb seine Macht in der Praxis nie völlig unbegrenzt.',
    ),
    pair(
      'p2',
      'Versailles',
      'Residenz und Machttheater Ludwigs XIV.',
      'Versailles diente der Repräsentation und der Kontrolle des Adels. Hofleben wurde damit Teil politischer Herrschaft.',
    ),
    pair(
      'p3',
      'Aufklärung',
      'Geistige Bewegung von Vernunft und Kritik',
      'Die Aufklärung prüfte Traditionen und Herrschaft mit dem Verstand. Daraus entstanden neue politische Ideen wie Gewaltenteilung und Menschenrechte.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Die Aufklärung bestärkte vor allem die Idee, dass Herrschaft niemals mit Vernunft oder Kritik geprüft werden dürfe.',
      false,
      'Gerade die Aufklärung wollte Herrschaft kritisch mit dem Verstand untersuchen.',
      'Aufklärer forderten, Autoritäten nicht einfach hinzunehmen. Vernunft, Diskussion und Kritik sollten Politik und Gesellschaft prüfen. Darin lag ihr Gegensatz zu rein traditionell oder göttlich begründeter Macht.',
    ),
  ],
}

const alleinherrschaft: BioBank = {
  quelle: 'Wikipedia: Magna Carta',
  url: 'https://de.wikipedia.org/wiki/Magna_Carta',
  conceptPrefix: 'ge:k7:alleinherrschaft',
  facts: [
    fact(
      'magna-carta',
      'Warum ist die Magna Carta von 1215 historisch wichtig?',
      'Weil sie königliche Macht begrenzte und Rechte des Adels festschrieb',
      ['Weil sie Frankreich zur Republik erklärte', 'Weil sie den Buchdruck erfand', 'Weil sie den Ersten Weltkrieg beendete'],
      'Die Magna Carta gilt als frühes Zeichen begrenzter Herrschaft.',
      'Die Magna Carta wurde 1215 dem englischen König Johann abgerungen. Sie beschränkte königliche Willkür und sicherte bestimmten Gruppen Rechte zu. Auch wenn sie noch keine moderne Demokratie schuf, wurde sie später zu einem wichtigen Symbol für Rechtsbindung der Macht.',
      'Die Magna Carta begrenzte die Macht des ___.',
      ['Königs', 'Koenigs'],
    ),
    fact(
      'parlament',
      'Welche Rolle gewann das englische Parlament langfristig?',
      'Es wurde zu einem Organ, das königliche Macht mitbestimmen und begrenzen konnte',
      ['Es diente nur der Hofunterhaltung', 'Es ersetzte jede Rechtsprechung durch Rituale', 'Es war nur eine Zunftversammlung von Kaufleuten'],
      'Parlamentarische Mitwirkung entwickelte sich schrittweise.',
      'Das englische Parlament entstand nicht auf einmal in moderner Form. Über lange Zeit gewann es Mitspracherechte, besonders bei Steuern und Gesetzen. Gerade dadurch wurde die königliche Alleinherrschaft schrittweise eingeschränkt.',
      'Das englische Parlament begrenzte langfristig die ___ des Königs.',
      ['Macht', 'Alleinherrschaft'],
    ),
    fact(
      'glorious-revolution',
      'Was zeigte die Glorious Revolution von 1688/89?',
      'Dass in England die Krone nicht völlig unabhängig vom Parlament regieren konnte',
      ['Dass England zum absolutistischen Musterstaat wurde', 'Dass Parlamente überall abgeschafft wurden', 'Dass Ludwig XIV. König von England wurde'],
      'Die Glorious Revolution stärkte die parlamentarische Ordnung.',
      'Die Glorious Revolution führte in England zu einer stärkeren Bindung der Krone an Recht und Parlament. Die Bill of Rights von 1689 machte deutlich, dass Herrschaft nicht beliebig sein durfte. Damit entstand ein wichtiges Gegenmodell zum Absolutismus.',
      'Die Glorious Revolution stärkte Recht und ___.',
      ['Parlament'],
    ),
    fact(
      'usa',
      'Warum war die Unabhängigkeit der USA für die Frage nach Herrschaft wichtig?',
      'Weil sie Regierung auf Rechte, Verfassung und Zustimmung der Regierten stützte',
      ['Weil sie ein neues Lehnswesen einführte', 'Weil sie den König von Frankreich stärkte', 'Weil sie jede Verfassung ablehnte'],
      'Die USA verbanden Unabhängigkeit mit Verfassungsideen.',
      'Die amerikanische Unabhängigkeitserklärung von 1776 begründete Herrschaft mit Rechten und Zustimmung der Regierten. In der Verfassung der USA wurden Gewaltenteilung und republikanische Ordnung wichtig. Damit entstand ein neues politisches Vorbild für viele Zeitgenossen.',
      'Die USA stützten Herrschaft auf Rechte, Verfassung und die ___ der Regierten.',
      ['Zustimmung'],
    ),
    fact(
      'fr-revolution',
      'Was griff die Französische Revolution gegen die alte Herrschaft an?',
      'Privilegien, Ständegesellschaft und unkontrollierte Monarchie',
      ['Nur den Buchdruck', 'Nur römisches Bürgerrecht der Antike', 'Nur mittelalterliche Stadtmauern'],
      'Die Revolution zielte auf grundlegende politische Veränderung.',
      'Die Französische Revolution von 1789 wandte sich gegen Privilegien des Ancien Régime. Sie stellte die Vorstellung in Frage, dass Herrschaft von Geburt oder Stand abhängen dürfe. Freiheit, Gleichheit und Volkssouveränität wurden dadurch zu zentralen politischen Begriffen.',
      'Die Französische Revolution griff Privilegien und die alte ___ an.',
      ['Ständegesellschaft', 'Monarchie'],
    ),
    fact(
      'bill-of-rights',
      'Wofür steht die englische Bill of Rights von 1689?',
      'Für die Bindung der Krone an Recht und Parlament',
      ['Für das Recht des Königs auf absolute Willkür', 'Für die Abschaffung jeder Volksvertretung', 'Für ein neues Kreuzzugsgesetz'],
      'Die Bill of Rights ordnete Macht verfassungsrechtlich ein.',
      'Die Bill of Rights von 1689 legte fest, dass der englische König nicht ohne Parlament herrschen sollte. Sie stärkte Rechte des Parlaments und begrenzte königliche Eingriffe. Damit wurde Rechtsbindung der Herrschaft deutlich ausgebaut.',
      'Die Bill of Rights band die Krone an Recht und ___.',
      ['Parlament'],
    ),
    fact(
      'verfassung',
      'Was leisten Verfassungen im Kampf gegen Alleinherrschaft?',
      'Sie legen Regeln fest und begrenzen Macht durch Recht',
      ['Sie ersetzen alle Gerichte durch den Hof', 'Sie schaffen automatisch soziale Gleichheit', 'Sie sind nur schöne Texte ohne politische Wirkung'],
      'Verfassungen ordnen Herrschaft und setzen Grenzen.',
      'Verfassungen sind grundlegende Regeln eines Staates. Sie legen fest, wer Macht ausübt und wie diese kontrolliert wird. Gerade dadurch können sie Alleinherrschaft einschränken und Rechte sichern.',
      'Verfassungen begrenzen Macht durch ___.',
      ['Recht'],
    ),
    fact(
      'vergleich',
      'Was verbindet Magna Carta, englisches Parlament, USA und Französische Revolution?',
      'Sie zeigen verschiedene Wege, Macht zu begrenzen und Rechte zu sichern',
      ['Sie alle stärken vorbehaltlos den Absolutismus', 'Sie gehören ausschließlich ins Mittelalter', 'Sie lehnen jede politische Mitwirkung ab'],
      'Herrschaft kann auf unterschiedliche Weise eingeschränkt werden.',
      'Magna Carta, Parlament, amerikanische Verfassung und Französische Revolution stehen nicht für dasselbe Modell. Gemeinsam ist ihnen aber, dass Herrschaft nicht grenzenlos sein soll. Geschichte zeigt hier mehrere Wege zur Begrenzung von Macht.',
      'Die Beispiele zeigen verschiedene Wege zur Begrenzung von ___.',
      ['Macht'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Magna Carta',
      'Frühe Begrenzung königlicher Willkür in England',
      'Die Magna Carta wurde 1215 durchgesetzt und gilt als Symbol rechtsgebundener Herrschaft. Sie schuf noch keine Demokratie, aber setzte Grenzen.',
    ),
    pair(
      'p2',
      'Bill of Rights',
      'Stärkte 1689 das Parlament gegenüber der Krone',
      'Die Bill of Rights baute die englische Verfassungsordnung aus. Sie zeigt, dass Könige nicht schrankenlos regieren konnten.',
    ),
    pair(
      'p3',
      'Volkssouveränität',
      'Idee, dass politische Macht vom Volk ausgeht',
      'Volkssouveränität wurde besonders seit den Revolutionen der Neuzeit wichtig. Sie widerspricht dem Gedanken reiner Alleinherrschaft.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Magna Carta und Bill of Rights sind Beispiele dafür, wie in England königliche Macht begrenzt wurde.',
      true,
      'Beide Texte stehen für die Bindung der Krone an Recht und Mitwirkung anderer Kräfte.',
      'In England entwickelte sich die Begrenzung königlicher Macht über mehrere Jahrhunderte. Magna Carta und Bill of Rights markieren wichtige Stationen dieser Entwicklung. Beide wurden später zu Symbolen verfassungsgebundener Herrschaft.',
    ),
  ],
  sources: [
    {
      concept: 'src-bill',
      question: 'Welche politische Idee steckt hinter diesem Grundsatz?',
      sourceText:
        'Der König soll ohne Zustimmung des Parlaments keine Steuern erheben und Gesetze nicht beliebig aussetzen.',
      sourceLabel: 'Verfassungsprinzip',
      sourceKind: 'Gesetzestext (sinngemäß)',
      attribution: 'Angelehnt an die englische Bill of Rights 1689',
      correct: 'Die Krone wird an Recht und Parlament gebunden',
      wrong: [
        'Der König erhält absolute Willkürgewalt',
        'Parlamente werden abgeschafft',
        'Nur der Adel darf Steuern zahlen',
      ] as [string, string, string],
      explanation: 'Die Bill of Rights begrenzte königliche Alleinherrschaft.',
      wissen:
        '1689 wurde festgeschrieben, dass der König nicht schrankenlos regieren darf. Parlament und Recht gewannen an Gewicht. Damit entstand ein Gegenmodell zum Absolutismus.',
    },
    {
      concept: 'src-usa',
      question: 'Worauf stützt dieser Text politische Herrschaft?',
      sourceText:
        'Regierungen leiten ihre rechtmäßige Macht von der Zustimmung der Regierten her.',
      sourceLabel: 'Politische Erklärung',
      sourceKind: 'Programmatischer Text',
      attribution: 'Sinngemäß nach der Unabhängigkeitserklärung der USA 1776',
      correct: 'Auf Zustimmung und Rechte der Regierten',
      wrong: [
        'Auf Gottesgnadentum ohne Verfassung',
        'Auf reines Lehnswesen',
        'Auf die Alleinherrschaft eines Pharaos',
      ] as [string, string, string],
      explanation: 'Zustimmung der Regierten widerspricht reiner Alleinherrschaft.',
      wissen:
        'Die USA verbanden Unabhängigkeit mit Verfassungsideen. Gewaltenteilung und Rechte wurden zentral. Das wurde zum Vorbild für viele Zeitgenossen.',
    },
  ],
  causeEffects: [
    {
      concept: 'ce-magna',
      cause: 'Adel erzwingt 1215 die Magna Carta',
      effect: 'Königliche Willkür wird erstmals schriftlich begrenzt',
      wissen:
        'Die Magna Carta schuf noch keine Demokratie, aber setzte Grenzen. Später wurde sie zum Symbol. Rechtsbindung der Macht begann schrittweise.',
    },
    {
      concept: 'ce-glorious',
      cause: 'Glorious Revolution 1688/89',
      effect: 'Bill of Rights stärkt Parlament gegenüber der Krone',
      wissen:
        'Die Krone wurde enger an Recht gebunden. Parlamentarische Mitwirkung wuchs. Absolutismus fand in England ein Gegenmodell.',
    },
    {
      concept: 'ce-fr',
      cause: 'Französische Revolution greift Privilegien an',
      effect: 'Volkssouveränität und Bürgerrechte werden zentrale Forderungen',
      wissen:
        '1789 stellte die Revolution Stand und Monarchie infrage. Freiheit und Gleichheit wurden Leitbegriffe. Alleinherrschaft verlor an Selbstverständlichkeit.',
    },
    {
      concept: 'ce-usa',
      cause: 'USA erklären Unabhängigkeit und Verfassung',
      effect: 'Herrschaft wird an Rechte und Zustimmung gebunden',
      wissen:
        'Verfassung und Gewaltenteilung begrenzten Macht. Das Vorbild wirkte über Amerika hinaus. Alleinherrschaft erhielt ein republikanisches Gegenbild.',
    },
  ],
}

const legitimation: BioBank = {
  quelle: 'Wikipedia: Herrschaftslegitimation',
  url: 'https://de.wikipedia.org/wiki/Legitimit%C3%A4t_(Politik)',
  conceptPrefix: 'ge:k7:legitimation',
  facts: [
    fact(
      'gottesgnadentum',
      'Was bedeutet Gottesgnadentum?',
      'Die Vorstellung, dass Herrscher ihre Macht von Gott erhalten',
      ['Die Idee, dass Macht nur aus Wahlen stammt', 'Die Lehre vom Gewaltenteilungsstaat', 'Das Bürgerrecht der römischen Republik'],
      'Gottesgnadentum legitimiert Herrschaft religiös.',
      'Beim Gottesgnadentum wird Herrschaft religiös begründet. Der Herrscher gilt nicht nur als mächtig, sondern als von Gott eingesetzt. Dadurch wird Widerstand leichter als Angriff auf die göttliche Ordnung dargestellt.',
      'Gottesgnadentum leitet Herrschaft von ___ her.',
      ['Gott'],
    ),
    fact(
      'hobbes',
      'Wie begründete Thomas Hobbes staatliche Herrschaft?',
      'Mit einem Gesellschaftsvertrag zum Schutz vor Unsicherheit und Gewalt',
      ['Mit der Abstammung von Karl dem Großen', 'Nur durch die Macht der Zünfte', 'Ausschließlich durch adelige Geburt'],
      'Hobbes stellte Sicherheit in den Mittelpunkt.',
      'Thomas Hobbes ging davon aus, dass Menschen im Naturzustand in Unsicherheit leben würden. Darum übertragen sie Macht an einen starken Staat, der Frieden sichert. Herrschaft entsteht bei ihm also durch Vertrag, nicht durch göttliche Abstammung.',
      'Hobbes begründete Herrschaft mit einem Gesellschafts___.',
      ['vertrag', 'Vertrag'],
    ),
    fact(
      'locke',
      'Worin unterschied sich John Locke von Hobbes?',
      'Locke betonte stärker Rechte des Einzelnen und das Recht auf Widerstand gegen Machtmissbrauch',
      ['Locke wollte absolute Königsherrschaft ohne Grenzen', 'Locke lehnte Eigentum vollständig ab', 'Locke war gegen jede Form von Parlamenten'],
      'Locke verband Vertrag mit Freiheitsrechten.',
      'John Locke begründete Staat und Regierung ebenfalls mit einem Vertrag, setzte aber stärkere Grenzen. Menschen besitzen nach ihm Rechte wie Leben, Freiheit und Eigentum. Wenn Herrscher diese Rechte verletzen, kann Widerstand legitim sein.',
      'Locke betonte stärker die Rechte des ___ gegen Machtmissbrauch.',
      ['Einzelnen'],
    ),
    fact(
      'rousseau',
      'Was hob Jean-Jacques Rousseau hervor?',
      'Den Gemeinwillen und die politische Selbstbestimmung der Bürger',
      ['Die erbliche Herrschaft des Adels', 'Die Vormacht der Kirche in jedem Staat', 'Nur das Lehnswesen des Mittelalters'],
      'Rousseau dachte Herrschaft von der politischen Gemeinschaft her.',
      'Rousseau fragte, wie Freiheit und politische Ordnung zusammenpassen. Er betonte den Gemeinwillen und die aktive Beteiligung der Bürger an der Gesetzgebung. Herrschaft sollte nach ihm nicht bloß von oben aufgedrückt werden.',
      'Rousseau betonte den Gemeinwillen und die politische ___ der Bürger.',
      ['Selbstbestimmung'],
    ),
    fact(
      'vergleich',
      'Was unterscheidet Gottesgnadentum und Vertragstheorien grundlegend?',
      'Gottesgnadentum leitet Macht von Gott ab, Vertragstheorien von Menschen und ihrer Zustimmung',
      ['Beide erklären Herrschaft nur über Rittertum', 'Beide lehnen jede Begründung von Macht ab', 'Nur Vertragstheorien sind mittelalterliche Kirchenlehren'],
      'Die Quelle der Legitimation verschiebt sich.',
      'Der größte Unterschied liegt in der Begründung von Herrschaft. Beim Gottesgnadentum kommt Legitimation von oben, bei Vertragstheorien von den Menschen selbst. Diese Verschiebung ist ein Kern des politischen Wandels in der Neuzeit.',
      'Vertragstheorien leiten Legitimation von den ___ und ihrer Zustimmung ab.',
      ['Menschen'],
    ),
    fact(
      'widerstand',
      'Wann kann nach Locke Widerstand gegen Herrschaft legitim sein?',
      'Wenn eine Regierung grundlegende Rechte verletzt',
      ['Immer gegen jede Form von Gesetz', 'Nur wenn ein Adeliger es befiehlt', 'Nie unter irgendeiner Bedingung'],
      'Widerstandsrecht soll Freiheit gegen Machtmissbrauch schützen.',
      'Locke sah Regierung als an Rechte gebunden. Wenn Herrscher Freiheit, Leben oder Eigentum zerstören, verlieren sie nach seiner Theorie ihre Legitimation. Daraus ergibt sich die Idee eines begrenzten Widerstandsrechts.',
      'Nach Locke kann bei Verletzung grundlegender Rechte ___ legitim sein.',
      ['Widerstand'],
    ),
    fact(
      'zustimmung',
      'Warum ist die Zustimmung der Regierten in Vertragstheorien so wichtig?',
      'Weil Herrschaft dort als von Menschen geschaffen und gerechtfertigt verstanden wird',
      ['Weil Zustimmung jede Verfassung überflüssig macht', 'Weil nur Priester zustimmen dürfen', 'Weil Macht dann ohne Regeln funktioniert'],
      'Vertragstheorien machen Menschen zu politischen Trägern.',
      'In Vertragstheorien ist Herrschaft nicht einfach naturgegeben. Sie entsteht, weil Menschen Ordnung und Sicherheit wollen und einer politischen Form zustimmen. Darum rückt die Frage nach Rechten, Pflichten und Grenzen der Macht in den Mittelpunkt.',
      'In Vertragstheorien wird Herrschaft durch ___ der Regierten begründet.',
      ['Zustimmung'],
    ),
    fact(
      'laengsschnitt',
      'Warum eignet sich Legitimation gut für einen Längsschnitt?',
      'Weil sich Begründungen von Herrschaft über viele Epochen hinweg vergleichen lassen',
      ['Weil Legitimation nur im 20. Jahrhundert vorkommt', 'Weil alle Herrscher immer gleich legitimiert wurden', 'Weil man dazu keine historischen Quellen braucht'],
      'Der Vergleich zeigt Wandel politischer Grundideen.',
      'Herrschaft wurde in der Geschichte sehr unterschiedlich begründet: religiös, dynastisch, vertraglich oder demokratisch. Gerade ein Längsschnitt macht sichtbar, wie sich diese Begründungen verändern. So erkennt man politische Entwicklung über Epochen hinweg.',
      'Ein Längsschnitt zeigt den Wandel von Herrschafts___.',
      ['legitimationen', 'Legitimationen'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Gottesgnadentum',
      'Religiöse Begründung von Herrschaft durch Gott',
      'Beim Gottesgnadentum wird der Herrscher als von Gott eingesetzt verstanden. So erhält Macht einen sakralen Anspruch.',
    ),
    pair(
      'p2',
      'Hobbes',
      'Vertragstheorie mit Schwerpunkt auf Sicherheit',
      'Hobbes begründet Staat mit dem Wunsch nach Frieden und Ordnung. Sicherheit steht bei ihm im Vordergrund.',
    ),
    pair(
      'p3',
      'Locke',
      'Vertragstheorie mit Rechten und Widerstandsrecht',
      'Locke verbindet Regierung mit Schutz individueller Rechte. Macht bleibt dadurch stärker begrenzt als bei Hobbes.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Vertragstheorien und Gottesgnadentum begründen Herrschaft auf dieselbe Weise.',
      false,
      'Sie unterscheiden sich gerade darin, ob Macht von Gott oder von Menschen und ihrer Zustimmung hergeleitet wird.',
      'Gottesgnadentum und Vertragstheorien setzen an ganz unterschiedlichen Quellen der Legitimation an. Das eine verweist auf göttliche Ordnung, das andere auf menschliche Zustimmung und politische Zwecke. Diese Differenz ist historisch grundlegend.',
    ),
  ],
}

const reformGerechtigkeit: BioBank = {
  quelle: 'Wikipedia: Deutscher Bauernkrieg',
  url: 'https://de.wikipedia.org/wiki/Deutscher_Bauernkrieg',
  conceptPrefix: 'ge:k7:reformation-gerechtigkeit',
  facts: [
    fact(
      'luther',
      'Warum löste Martin Luther eine große religiöse Bewegung aus?',
      'Weil er Missstände der Kirche kritisierte und neue Glaubensakzente setzte',
      ['Weil er Frankreich absolutistisch regierte', 'Weil er die USA gründete', 'Weil er die Goldene Bulle schrieb'],
      'Luthers Kritik wurde durch Druck und Debatten weit verbreitet.',
      'Martin Luther kritisierte kirchliche Missstände wie den Ablasshandel und stellte zentrale Fragen nach Gnade und Glauben. Seine Schriften verbreiteten sich rasch durch den Buchdruck. So wurde aus einer Kritik eine große Reformbewegung.',
      'Luther kritisierte kirchliche ___ und setzte neue Glaubensakzente.',
      ['Missstände'],
    ),
    fact(
      '95-thesen',
      'Wogegen richteten sich Luthers 95 Thesen besonders?',
      'Gegen den Ablasshandel und falsche Heilsversprechen',
      ['Gegen die Magna Carta', 'Gegen das römische Bürgerrecht', 'Gegen die Entdeckung Amerikas'],
      'Die Thesen griffen kirchliche Praxis und Theologie an.',
      'Die 95 Thesen von 1517 richteten sich besonders gegen den Ablasshandel. Luther kritisierte, dass Vergebung nicht gekauft werden könne. Damit stellte er Autorität und Praxis der Kirche öffentlich in Frage.',
      'Die 95 Thesen richteten sich besonders gegen den ___.',
      ['Ablasshandel'],
    ),
    fact(
      'bauernkrieg',
      'Warum beriefen sich viele Bauern im Bauernkrieg auf reformatorische Ideen?',
      'Weil sie hofften, religiöse Erneuerung könne auch mehr Gerechtigkeit im Alltag bringen',
      ['Weil Luther ihnen den Königstitel versprach', 'Weil sie nur für den Papst kämpften', 'Weil sie die Rückkehr zur Leibeigenschaft wollten'],
      'Soziale Fragen verbanden sich mit religiöser Sprache.',
      'Im Bauernkrieg von 1524/25 verbanden viele Bauern soziale Forderungen mit religiösen Argumenten. Sie wollten Abgaben, Frondienste und Ungerechtigkeiten begrenzen. Reformation wurde damit für manche auch zu einer Frage sozialer Gerechtigkeit.',
      'Viele Bauern verbanden Reformation mit Hoffnung auf mehr soziale ___.',
      ['Gerechtigkeit'],
    ),
    fact(
      'zwoelf-artikel',
      'Was waren die Zwölf Artikel?',
      'Eine Sammlung bäuerlicher Forderungen nach Rechten und gerechteren Verhältnissen',
      ['Ein Katalog absolutistischer Hofregeln', 'Die Verfassung der USA', 'Ein Vertrag zwischen Ludwig XIV. und dem Papst'],
      'Die Zwölf Artikel zählen zu den wichtigsten Texten des Bauernkriegs.',
      'Die Zwölf Artikel formulierten Forderungen nach gerechteren Lebensbedingungen, etwa bei Abgaben und Nutzung von Gemeinderechten. Sie zeigen, dass Bauern ihre Anliegen schriftlich und argumentativ darstellten. Damit wurden soziale Konflikte politisch und religiös begründet.',
      'Die Zwölf Artikel sammelten bäuerliche ___ nach gerechteren Verhältnissen.',
      ['Forderungen'],
    ),
    fact(
      'luther-bauern',
      'Wie reagierte Luther auf den Bauernkrieg?',
      'Er wandte sich gegen den gewaltsamen Aufstand der Bauern',
      ['Er führte die Bauernheere persönlich an', 'Er erklärte alle Herren für abgesetzt', 'Er blieb völlig ohne Stellungnahme'],
      'Luthers Haltung enttäuschte viele Hoffnungen auf soziale Reform.',
      'Luther hatte zunächst Verständnis für manche Beschwerden, lehnte aber den gewaltsamen Aufstand ab. In seiner Schrift gegen die Bauern stellte er sich deutlich gegen deren Kriegführung. Das zeigt die Spannungen zwischen religiöser Reform und sozialer Revolte.',
      'Luther wandte sich gegen den ___ Aufstand der Bauern.',
      ['gewaltsamen'],
    ),
    fact(
      'gerechtigkeit',
      'Warum ist der Bauernkrieg ein Beispiel für die Frage nach Gerechtigkeit?',
      'Weil Menschen religiöse Erneuerung mit Forderungen nach gerechteren Lebensverhältnissen verbanden',
      ['Weil es nur um technische Erfindungen ging', 'Weil Gerechtigkeit damals keine Rolle spielte', 'Weil nur Fürsten mitredeten'],
      'Reformation wirkte auch in soziale Konflikte hinein.',
      'Der Bauernkrieg zeigt, dass religiöse Ideen politische und soziale Folgen haben können. Bauern fragten, ob christliche Ordnung auch gerechtere Lebensverhältnisse bedeuten müsse. Gerade deshalb ist das Thema mehr als reine Kirchengeschichte.',
      'Der Bauernkrieg verbindet Religion mit sozialer ___.',
      ['Gerechtigkeit'],
    ),
    fact(
      'gewalt',
      'Was zeigt der Bauernkrieg über politische Veränderung?',
      'Dass Reformhoffnungen in gewaltsame Konflikte umschlagen können',
      ['Dass jede Reform automatisch friedlich verläuft', 'Dass Bauern immer erfolgreich siegen', 'Dass Fürsten sofort auf alle Forderungen eingehen'],
      'Gesellschaftlicher Wandel ist oft umkämpft.',
      'Der Bauernkrieg macht sichtbar, wie schnell Hoffnungen auf Veränderung in Gewalt umschlagen können. Unterschiedliche Interessen von Bauern, Fürsten und Reformatoren prallten hart aufeinander. Wandel verlief deshalb nicht gradlinig, sondern konfliktreich.',
      'Der Bauernkrieg zeigt, dass Reformhoffnungen in ___ umschlagen können.',
      ['Gewalt', 'Konflikte'],
    ),
    fact(
      'folge',
      'Welche unmittelbare Folge hatte der Bauernkrieg für viele Bauern?',
      'Sie wurden militärisch besiegt und ihre Lage verbesserte sich zunächst kaum',
      ['Sie erhielten sofort allgemeines Wahlrecht', 'Sie wurden alle zu Stadtbürgern', 'Sie setzten europaweit eine Republik durch'],
      'Die Niederlage beendete den Konflikt nicht als Erinnerung.',
      'Die Bauernheere wurden 1525 militärisch geschlagen. Für viele Bauern brachte das zunächst keine grundlegende Verbesserung ihrer Lage. Dennoch blieb der Bauernkrieg ein wichtiges Erinnerungszeichen für soziale Konflikte und Gerechtigkeitsfragen.',
      'Viele Bauern wurden 1525 militärisch ___.',
      ['besiegt'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      '95 Thesen',
      'Luthers Kritik am Ablasshandel von 1517',
      'Die 95 Thesen griffen den Ablasshandel an und machten kirchliche Missstände öffentlich. Sie wurden zum Ausgangspunkt der Reformation.',
    ),
    pair(
      'p2',
      'Zwölf Artikel',
      'Schriftliche Forderungen der Bauern im Bauernkrieg',
      'Die Zwölf Artikel formulierten soziale und wirtschaftliche Anliegen der Bauern. Sie verbinden religiöse Sprache mit Gerechtigkeitsforderungen.',
    ),
    pair(
      'p3',
      'Bauernkrieg',
      'Großer Aufstand von 1524/25 im Zeichen sozialer und religiöser Konflikte',
      'Im Bauernkrieg trafen Erwartungen an Reformation und soziale Wirklichkeit hart aufeinander. Das macht ihn zu einem Schlüsselthema der Epoche.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Der Bauernkrieg hatte nur religiöse Ursachen und nichts mit sozialen Belastungen zu tun.',
      false,
      'Soziale Forderungen und Erfahrungen von Ungerechtigkeit spielten eine zentrale Rolle.',
      'Die Bauern beriefen sich zwar auf religiöse Argumente, kämpften aber auch gegen Abgaben, Frondienste und rechtliche Benachteiligung. Gerade diese Verbindung macht den Bauernkrieg historisch so bedeutsam. Reformation und soziale Frage griffen ineinander.',
    ),
  ],
}

const reformSachsen: BioBank = {
  quelle: 'Wikipedia: Wittenberg',
  url: 'https://de.wikipedia.org/wiki/Wittenberg',
  conceptPrefix: 'ge:k7:reformation-sachsen',
  facts: [
    fact(
      'wittenberg',
      'Warum ist Wittenberg für die Reformation besonders wichtig?',
      'Weil Luther dort wirkte und die Stadt zu einem Zentrum der Bewegung wurde',
      ['Weil dort Ludwig XIV. residierte', 'Weil Wittenberg die Magna Carta ausstellte', 'Weil dort der Erste Weltkrieg begann'],
      'Wittenberg wurde zum Erinnerungsort der Reformation.',
      'Wittenberg war der Wirkungsort Martin Luthers und anderer Reformatoren. Universität, Druck und fürstlicher Schutz machten die Stadt zu einem Zentrum der Reformation. Darum besitzt sie bis heute große symbolische Bedeutung.',
      'Wittenberg wurde zu einem Zentrum der ___.',
      ['Reformation'],
    ),
    fact(
      'friedrich-weise',
      'Welche Rolle spielte Kurfürst Friedrich der Weise?',
      'Er schützte Luther politisch und stärkte damit die Reformation in Sachsen',
      ['Er verurteilte Luther als Sultan', 'Er gründete den Jesuitenorden', 'Er führte den Bauernkrieg gegen die Fürsten an'],
      'Fürstenschutz war für die Reformation entscheidend.',
      'Kurfürst Friedrich der Weise unterstützte Luther nicht in allen theologischen Fragen, schützte ihn aber politisch. Ohne diesen Rückhalt wäre Luthers Weg sehr viel gefährlicher gewesen. Sachsen wurde dadurch zu einem Kernraum der Reformation.',
      'Friedrich der Weise schützte Luther vor allem ___.',
      ['politisch'],
    ),
    fact(
      'wartburg',
      'Warum ist die Zeit auf der Wartburg für die Reformation bedeutsam?',
      'Weil Luther dort das Neue Testament ins Deutsche übersetzte',
      ['Weil dort die Goldene Bulle beschlossen wurde', 'Weil dort die Sorben siedelten', 'Weil dort Versailles errichtet wurde'],
      'Die Bibelübersetzung stärkte Sprache und Glaubenszugang.',
      'Während seines Aufenthalts auf der Wartburg übersetzte Luther das Neue Testament ins Deutsche. Dadurch wurde die Bibel für viele Menschen zugänglicher. Zugleich wirkte die Übersetzung prägend auf die deutsche Schriftsprache.',
      'Auf der Wartburg übersetzte Luther das Neue Testament ins ___.',
      ['Deutsche', 'Deutsch'],
    ),
    fact(
      'universitaet',
      'Warum war die Universität Wittenberg für die Reformation wichtig?',
      'Weil dort gelehrt, diskutiert und reformatorische Ideen verbreitet wurden',
      ['Weil Universitäten damals nur Ritter ausbildeten', 'Weil dort keinerlei Texte gedruckt wurden', 'Weil Bildung für die Reformation unwichtig war'],
      'Universitäten halfen, Ideen dauerhaft zu verbreiten.',
      'Die Universität Wittenberg war ein Zentrum von Lehre und Debatte. Dort wurden reformatorische Gedanken ausgearbeitet, diskutiert und an Studenten weitergegeben. Bildung und Öffentlichkeit verstärkten so die Wirkung der Reformation.',
      'Die Universität half, reformatorische Ideen zu ___.',
      ['verbreiten'],
    ),
    fact(
      'druck',
      'Warum spielte der Buchdruck gerade in Sachsen für die Reformation eine große Rolle?',
      'Weil Schriften Luthers schnell vervielfältigt und verbreitet werden konnten',
      ['Weil dadurch alle Klöster sofort verschwanden', 'Weil nur Fürsten lesen durften', 'Weil Druck handschriftliche Briefe verbot'],
      'Druck machte die Reformation zu einer Massenbewegung.',
      'Ohne den Buchdruck hätte sich die Reformation viel langsamer verbreitet. Flugschriften, Predigten und Bibeltexte konnten nun schnell gedruckt werden. Sachsen wurde dadurch nicht nur politisch, sondern auch medial zu einem Kernland der Bewegung.',
      'Der Buchdruck machte die Verbreitung von Luthers ___ schneller.',
      ['Schriften'],
    ),
    fact(
      'kursachsen',
      'Warum war Kursachsen für die Reformation so bedeutsam?',
      'Weil dort ein politisch starkes Territorium die Bewegung trug und schützte',
      ['Weil Kursachsen außerhalb des Reiches lag', 'Weil dort nie Fürsten herrschten', 'Weil nur Bauern ohne Städte lebten'],
      'Reformation brauchte politische Räume und Schutz.',
      'Kursachsen war ein wichtiges Territorium im Heiligen Römischen Reich. Wenn ein Kurfürst reformatorische Entwicklungen zuließ oder schützte, wirkte das weit über die Region hinaus. Darum wurde Sachsen zu einem Kernland der Reformation.',
      'Kursachsen war wichtig, weil es der Reformation politischen ___ bot.',
      ['Schutz', 'Rückhalt'],
    ),
    fact(
      'erinnerungsort',
      'Warum sind Wittenberg und andere Reformationsorte bis heute bedeutend?',
      'Weil sie historische Erinnerung an religiösen Wandel und politische Entscheidungen bündeln',
      ['Weil dort heute keine Geschichte mehr sichtbar ist', 'Weil sie nur touristische Erfindungen sind', 'Weil Erinnerungsorte keine Quellen darstellen'],
      'Orte können Geschichte dauerhaft verkörpern.',
      'Reformationsorte wie Wittenberg sind Erinnerungsorte, weil an ihnen entscheidende Entwicklungen festgemacht werden. Gebäude, Kirchen und Museen machen Geschichte sichtbar. So bleibt die Reformation im öffentlichen Gedächtnis präsent.',
      'Reformationsorte bündeln historische ___.',
      ['Erinnerung'],
    ),
    fact(
      'kernland',
      'Was meint die Aussage, Sachsen sei ein Kernland der Reformation?',
      'Dass von dort wichtige Impulse, Akteure und Schutzräume für die Bewegung ausgingen',
      ['Dass die Reformation nur in Sachsen stattfand', 'Dass andere Regionen keinerlei Rolle spielten', 'Dass Sachsen damals unabhängig von Europa war'],
      'Ein Kernland ist wichtig, aber nicht alleiniger Schauplatz.',
      'Sachsen war für die Reformation besonders bedeutend, weil dort wichtige Personen wirkten und politische Schutzräume entstanden. Das heißt aber nicht, dass nur dort reformiert wurde. Vielmehr verband Sachsen lokale Ereignisse mit europäischer Wirkung.',
      'Ein Kernland liefert wichtige Impulse und ___ für eine Bewegung.',
      ['Schutzräume', 'Rückhalt'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Wittenberg',
      'Zentrum der Reformation in Kursachsen',
      'Wittenberg verband Universität, Druck und reformatorische Akteure. Dadurch wurde die Stadt zu einem zentralen Erinnerungsort.',
    ),
    pair(
      'p2',
      'Friedrich der Weise',
      'Kurfürst, der Luther politisch schützte',
      'Fürstlicher Schutz war für die Reformation entscheidend. Friedrich der Weise gab Luther einen wichtigen Rückhalt.',
    ),
    pair(
      'p3',
      'Wartburgübersetzung',
      'Luthers Übertragung des Neuen Testaments ins Deutsche',
      'Die Übersetzung machte biblische Texte zugänglicher und wirkte sprachprägend. Sie gehört zu den bekanntesten Leistungen der Reformation.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Sachsen gilt als Kernland der Reformation, weil dort nur theologische Texte wichtig waren, nicht aber Fürsten und Druck.',
      false,
      'Gerade Fürstenschutz, Universität und Buchdruck machten Sachsen so bedeutsam.',
      'Theologische Ideen allein erklären den Erfolg der Reformation nicht. In Sachsen kamen politische Unterstützung, mediale Verbreitung und Bildungsorte zusammen. Diese Verbindung machte die Region besonders wirksam.',
    ),
  ],
}

const reformKatholisch: BioBank = {
  quelle: 'Wikipedia: Konzil von Trient',
  url: 'https://de.wikipedia.org/wiki/Konzil_von_Trient',
  conceptPrefix: 'ge:k7:reformation-katholisch',
  facts: [
    fact(
      'trient',
      'Was war das Konzil von Trient?',
      'Eine katholische Kirchenversammlung zur Reform und Klärung des Glaubens',
      ['Ein englisches Parlament gegen den König', 'Eine Bauernversammlung in Memmingen', 'Eine antike Philosophenschule in Athen'],
      'Das Konzil reagierte auf Herausforderungen der Reformation.',
      'Das Konzil von Trient tagte im 16. Jahrhundert und war eine zentrale Antwort der katholischen Kirche auf die Reformation. Es klärte Lehre und forderte Reformen im kirchlichen Leben. Dadurch prägte es die katholische Kirche über Jahrhunderte.',
      'Das Konzil von Trient war eine katholische ___ zur Reform der Kirche.',
      ['Kirchenversammlung'],
    ),
    fact(
      'katholische-reform',
      'Was meint "katholische Reform" oder Gegenreformation?',
      'Die Erneuerung und Stärkung der katholischen Kirche als Reaktion auf die Reformation',
      ['Die Abschaffung aller Klöster in Europa', 'Die Einführung des Gottesgnadentums in England', 'Die Gründung des Völkerbunds'],
      'Katholische Reform war mehr als bloßer Widerstand.',
      'Die katholische Reform bestand nicht nur aus Abwehr gegen Protestanten. Sie umfasste auch innere Erneuerung, bessere Ausbildung des Klerus und strengere Kirchenordnung. Deshalb spricht man häufig lieber von katholischer Reform als nur von Gegenreformation.',
      'Katholische Reform bedeutete Erneuerung und ___ der Kirche.',
      ['Stärkung'],
    ),
    fact(
      'jesuiten',
      'Welche Rolle spielte der Jesuitenorden?',
      'Er wirkte in Bildung, Mission und Stärkung der katholischen Kirche',
      ['Er führte als Ritterorden die Kreuzzüge des Mittelalters weiter', 'Er war nur eine Bauernbewegung', 'Er löste die Französische Revolution aus'],
      'Jesuiten wurden zu einem wichtigen Träger katholischer Reform.',
      'Der Jesuitenorden wurde im 16. Jahrhundert gegründet und gewann rasch Einfluss. Er engagierte sich in Schulen, Mission und Seelsorge. Dadurch trug er wesentlich dazu bei, die katholische Kirche zu festigen und neu auszurichten.',
      'Die Jesuiten wirkten besonders in Bildung, Mission und ___.',
      ['Seelsorge'],
    ),
    fact(
      'priesterbildung',
      'Warum war bessere Ausbildung der Priester ein Ziel der katholischen Reform?',
      'Weil Bildung und Disziplin Missstände verringern und Glaubensvermittlung stärken sollten',
      ['Weil Priester fortan nur Ritter sein sollten', 'Weil Bildung in der Kirche verboten wurde', 'Weil man alle Klöster sofort schließen wollte'],
      'Reform sollte den Alltag der Kirche verbessern.',
      'Ein wichtiges Anliegen der katholischen Reform war die bessere Ausbildung des Klerus. Seminare und klare Regeln sollten Seelsorge und Glaubensunterweisung verbessern. Damit reagierte die Kirche auch auf frühere Missstände.',
      'Die katholische Reform wollte die ___ der Priester verbessern.',
      ['Ausbildung'],
    ),
    fact(
      'barock',
      'Wie hing der Barock oft mit der katholischen Reform zusammen?',
      'Prunkvolle Kunst und Kirchen sollten Glauben sichtbar und eindrucksvoll machen',
      ['Der Barock lehnte jede Kirche ab', 'Barock war nur ein Bauernwerkzeug', 'Er gehörte ausschließlich zur Antike'],
      'Kunst wurde gezielt für religiöse Wirkung genutzt.',
      'Im Barock nutzte die katholische Kirche Kunst, Musik und Architektur besonders eindrucksvoll. Prachtvolle Kirchenräume sollten Glauben erfahrbar machen und Menschen ansprechen. Damit wurde Kultur Teil religiöser Erneuerung.',
      'Im Barock sollte Kunst den ___ eindrucksvoll sichtbar machen.',
      ['Glauben'],
    ),
    fact(
      'bekenntnisse',
      'Welche Folge hatte die Reformation langfristig für Europa?',
      'Europa blieb konfessionell gespalten in katholische und protestantische Räume',
      ['Alle Christen wurden sofort wieder eine einzige Kirche', 'Konfession spielte keine Rolle mehr', 'Nur Sachsen blieb religiös verschieden'],
      'Die Glaubensspaltung prägte Politik und Gesellschaft langfristig.',
      'Nach Reformation und katholischer Reform blieb Europa konfessionell geteilt. In vielen Regionen bestimmten katholische oder protestantische Mehrheiten Politik, Schule und Alltag. Diese Spaltung wirkte über Jahrhunderte weiter.',
      'Europa blieb langfristig konfessionell ___.',
      ['gespalten'],
    ),
    fact(
      'trient-lehre',
      'Was tat das Konzil von Trient mit katholischer Lehre?',
      'Es bestätigte zentrale Lehren und grenzte sie gegenüber protestantischen Positionen ab',
      ['Es übernahm vollständig Luthers Lehre', 'Es verbot jede Sakramentenlehre', 'Es erklärte alle Unterschiede für unwichtig'],
      'Trient schuf Klarheit und Abgrenzung.',
      'Das Konzil von Trient bestätigte zentrale katholische Lehren und präzisierte sie. Zugleich grenzte es sich bewusst gegen protestantische Positionen ab. So verband sich innere Reform mit deutlicher konfessioneller Profilbildung.',
      'Trient bestätigte katholische Lehren und ___ sie gegenüber protestantischen Positionen ab.',
      ['grenzte'],
    ),
    fact(
      'schulen',
      'Warum waren Schulen für die katholische Reform wichtig?',
      'Weil Bildung helfen sollte, Glauben zu vermitteln und die Kirche zu stärken',
      ['Weil Religion von nun an ohne Wissen auskommen sollte', 'Weil nur Adlige lesen lernen durften', 'Weil Schulen durch Ritterburgen ersetzt wurden'],
      'Bildung war ein zentrales Feld konfessioneller Prägung.',
      'Schulen waren in der konfessionellen Zeit wichtig, weil dort Wissen und Glaubensvorstellungen weitergegeben wurden. Besonders Jesuiten gründeten und leiteten viele Bildungseinrichtungen. So wurde Erziehung ein zentrales Mittel religiöser Festigung.',
      'Schulen halfen, Glauben zu vermitteln und die Kirche zu ___.',
      ['stärken'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Konzil von Trient',
      'Katholische Kirchenversammlung zur Reform und Lehre',
      'Trient reagierte auf die Reformation und ordnete die katholische Kirche neu. Es verband innere Reform mit klarer Abgrenzung.',
    ),
    pair(
      'p2',
      'Jesuiten',
      'Orden mit großer Bedeutung für Bildung und Mission',
      'Die Jesuiten wirkten stark in Schulen und Seelsorge. So wurden sie zu wichtigen Trägern katholischer Reform.',
    ),
    pair(
      'p3',
      'katholische Reform',
      'Erneuerung der katholischen Kirche im 16. Jahrhundert',
      'Katholische Reform umfasste Disziplin, Ausbildung und Lehre. Sie war also mehr als nur Abwehr gegen Protestanten.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Die katholische Reform bestand nur darin, jede Veränderung abzulehnen und nichts in der Kirche zu verbessern.',
      false,
      'Sie umfasste auch echte Erneuerung wie bessere Priesterausbildung und neue Bildungsarbeit.',
      'Katholische Reform bedeutete nicht bloß starre Abwehr. Kirche und Orden bemühten sich auch um bessere Bildung, Disziplin und Glaubensvermittlung. Gerade das macht die Epoche komplexer als das Schlagwort Gegenreformation vermuten lässt.',
    ),
  ],
}

const englandParlament: BioBank = {
  quelle: 'Wikipedia: Bill of Rights (England)',
  url: 'https://de.wikipedia.org/wiki/Bill_of_Rights_(England)',
  conceptPrefix: 'ge:k7:england',
  facts: [
    fact('magna', 'Warum ist die Magna Carta von 1215 historisch wichtig?', 'Weil sie königliche Macht begrenzte und Rechte des Adels festschrieb', ['Weil sie Frankreich zur Republik erklärte', 'Weil sie den Buchdruck erfand', 'Weil sie den Ersten Weltkrieg beendete'], 'Die Magna Carta gilt als frühes Zeichen begrenzter Herrschaft.', 'Die Magna Carta wurde 1215 dem englischen König Johann abgerungen. Sie beschränkte königliche Willkür und sicherte bestimmten Gruppen Rechte zu. Auch wenn sie noch keine moderne Demokratie schuf, wurde sie später zu einem wichtigen Symbol.', 'Die Magna Carta begrenzte die Macht des ___.', ['Königs', 'Koenigs']),
    fact('parlament', 'Welche Rolle gewann das englische Parlament langfristig?', 'Es wurde zu einem Organ, das königliche Macht mitbestimmen und begrenzen konnte', ['Es diente nur der Hofunterhaltung', 'Es ersetzte jede Rechtsprechung durch Rituale', 'Es war nur eine Zunftversammlung'], 'Parlamentarische Mitwirkung entwickelte sich schrittweise.', 'Das englische Parlament entstand nicht auf einmal in moderner Form. Über lange Zeit gewann es Mitspracherechte, besonders bei Steuern und Gesetzen. Gerade dadurch wurde die königliche Alleinherrschaft schrittweise eingeschränkt.', 'Das englische Parlament begrenzte langfristig die ___ des Königs.', ['Macht', 'Alleinherrschaft']),
    fact('glorious', 'Was zeigte die Glorious Revolution von 1688/89?', 'Dass in England die Krone nicht völlig unabhängig vom Parlament regieren konnte', ['Dass England zum absolutistischen Musterstaat wurde', 'Dass Parlamente überall abgeschafft wurden', 'Dass Ludwig XIV. König von England wurde'], 'Die Glorious Revolution stärkte die parlamentarische Ordnung.', 'Die Glorious Revolution führte zu einer stärkeren Bindung der Krone an Recht und Parlament. Die Bill of Rights von 1689 machte deutlich, dass Herrschaft nicht beliebig sein durfte. Damit entstand ein Gegenmodell zum Absolutismus.', 'Die Glorious Revolution stärkte Recht und ___.', ['Parlament']),
    fact('bill', 'Wofür steht die englische Bill of Rights von 1689?', 'Für die Bindung der Krone an Recht und Parlament', ['Für das Recht des Königs auf absolute Willkür', 'Für die Abschaffung jeder Volksvertretung', 'Für ein neues Kreuzzugsgesetz'], 'Die Bill of Rights ordnete Macht verfassungsrechtlich ein.', 'Die Bill of Rights von 1689 legte fest, dass der englische König nicht ohne Parlament herrschen sollte. Sie stärkte Rechte des Parlaments und begrenzte königliche Eingriffe. Damit wurde Rechtsbindung der Herrschaft deutlich ausgebaut.', 'Die Bill of Rights band die Krone an Recht und ___.', ['Parlament']),
    fact('konstitutionell', 'Was meint konstitutionelle Monarchie grob?', 'Ein Königreich, in dem die Herrschaft durch Recht und Mitwirkung begrenzt ist', ['Ein Staat ohne jedes Gesetz', 'Eine reine Militärdiktatur', 'Ein Pharaonenstaat ohne Schrift'], 'Konstitutionelle Monarchie bindet den Herrscher an Regeln. Parlament und Rechte begrenzen Willkür. England wurde dafür zum europäischen Beispiel.', 'Konstitutionelle Monarchie bindet den Herrscher an Regeln. Parlament und Rechte begrenzen Willkür. England wurde dafür zum europäischen Beispiel.', 'In der konstitutionellen Monarchie begrenzt ___ die königliche Macht.', ['Recht', 'Parlament']),
    fact('steuern', 'Warum war die Steuerfrage für das Parlament so zentral?', 'Weil Zustimmung zu Abgaben Macht über den König gab', ['Weil Steuern nur Bauern betrafen', 'Weil Könige keine Heere brauchten', 'Weil Geld bedeutungslos war'], 'Wer Steuern bewilligt, kann Herrschaft mitsteuern.', 'Könige brauchten Geld für Krieg und Hof. Das Parlament nutzte die Bewilligung als Hebel. So wuchs politische Mitwirkung.', 'Zustimmung zu ___ stärkte das Parlament.', ['Steuern', 'Abgaben']),
    fact('vergleich', 'Warum ist England ein Gegenmodell zum Absolutismus?', 'Weil Krone und Parlament Herrschaft teilten und rechtlich banden', ['Weil England absolutistischer als Frankreich war', 'Weil es kein Parlament gab', 'Weil Ludwig XIV. dort residierte'], 'Geteilte und gebundene Macht widerspricht Alleinherrschaft.', 'Während Ludwig XIV. verdichtete Herrschaft verkörperte, entwickelte England parlamentarische Begrenzung. Der Vergleich ist Lehrplanstoff. Beide Modelle prägten Europa.', 'England begrenzte königliche Macht durch ___.', ['Parlament', 'Recht']),
    fact('symbol', 'Warum wirken Magna Carta und Bill of Rights bis heute als Symbole?', 'Weil sie für die Idee rechtsgebundener Herrschaft stehen', ['Weil sie den Absolutismus feierten', 'Weil sie nur Sportregeln waren', 'Weil sie die Steinzeit beschrieben'], 'Symbole verdichten lange Entwicklungen.', 'Nicht jeder Artikel war modern demokratisch. Dennoch markieren die Texte Stationen der Machtbegrenzung. Spätere Generationen beriefen sich darauf.', 'Beide Texte symbolisieren ___ Herrschaft.', ['rechtsgebundene', 'begrenzte']),
  ],
  pairs: [
    pair('p1', 'Magna Carta', 'Frühe Begrenzung königlicher Willkür', '1215 durchgesetzt, später Symbol.'),
    pair('p2', 'Bill of Rights', 'Stärkte 1689 das Parlament', 'Band die Krone an Recht.'),
    pair('p3', 'Parlament', 'Organ der Mitbestimmung und Kontrolle', 'Begrenzte königliche Macht.'),
  ],
  trueFalse: [
    tf('t1', 'Die Bill of Rights von 1689 stärkte die absolute Willkür des Königs.', false, 'Sie band die Krone an Recht und Parlament.', '1689 wurde königliche Macht begrenzt, nicht ausgeweitet. Parlament und Recht gewannen an Gewicht. Das ist das Gegenteil von Absolutismus.'),
  ],
  sources: alleinherrschaft.sources,
  causeEffects: alleinherrschaft.causeEffects?.filter((c) =>
    ['ce-magna', 'ce-glorious'].includes(c.concept ?? ''),
  ),
}

const usaVerfassung: BioBank = {
  quelle: 'Wikipedia: Unabhängigkeitserklärung der Vereinigten Staaten',
  url: 'https://de.wikipedia.org/wiki/Unabh%C3%A4ngigkeitserkl%C3%A4rung_der_Vereinigten_Staaten',
  conceptPrefix: 'ge:k7:usa',
  facts: [
    fact('usa', 'Warum war die Unabhängigkeit der USA für die Frage nach Herrschaft wichtig?', 'Weil sie Regierung auf Rechte, Verfassung und Zustimmung der Regierten stützte', ['Weil sie ein neues Lehnswesen einführte', 'Weil sie den König von Frankreich stärkte', 'Weil sie jede Verfassung ablehnte'], 'Die USA verbanden Unabhängigkeit mit Verfassungsideen.', 'Die Unabhängigkeitserklärung von 1776 begründete Herrschaft mit Rechten und Zustimmung. In der Verfassung wurden Gewaltenteilung und republikanische Ordnung wichtig. Damit entstand ein neues politisches Vorbild.', 'Die USA stützten Herrschaft auf Rechte, Verfassung und die ___ der Regierten.', ['Zustimmung']),
    fact('1776', 'Was geschah 1776 in Nordamerika?', 'Die Unabhängigkeitserklärung der USA wurde verkündet', ['Rom wurde gegründet', 'Die Magna Carta wurde unterzeichnet', 'Der Erste Weltkrieg begann'], '1776 markiert den Bruch mit der britischen Krone.', 'Die Kolonien erklärten sich unabhängig. Der Text formulierte Rechte und Zustimmung der Regierten. Das wirkte als politisches Signal weit über Amerika hinaus.', '1776 verkündeten die USA die ___.', ['Unabhängigkeitserklärung']),
    fact('verfassung', 'Was leisten Verfassungen im Kampf gegen Alleinherrschaft?', 'Sie legen Regeln fest und begrenzen Macht durch Recht', ['Sie ersetzen alle Gerichte durch den Hof', 'Sie schaffen automatisch soziale Gleichheit', 'Sie sind nur schöne Texte ohne Wirkung'], 'Verfassungen ordnen Herrschaft und setzen Grenzen.', 'Verfassungen sind grundlegende Regeln eines Staates. Sie legen fest, wer Macht ausübt und wie diese kontrolliert wird. Gerade dadurch können sie Alleinherrschaft einschränken.', 'Verfassungen begrenzen Macht durch ___.', ['Recht']),
    fact('gewalt', 'Warum ist Gewaltenteilung wichtig?', 'Weil sie Macht auf verschiedene Organe verteilt und Kontrolle ermöglicht', ['Weil ein einzelner Herrscher alles allein entscheiden soll', 'Weil Gerichte überflüssig werden', 'Weil Parlamente verboten sind'], 'Geteilte Macht soll Missbrauch erschweren.', 'Legislative, Exekutive und Judikative kontrollieren einander. Das war ein Kern der US-Verfassungsideen. Alleinherrschaft widerspricht diesem Prinzip.', 'Gewaltenteilung verteilt ___ auf Organe.', ['Macht']),
    fact('rechte', 'Welche Idee wurde in den USA besonders betont?', 'Dass Menschen unveräußerliche Rechte haben', ['Dass nur der König Rechte besitzt', 'Dass Rechte nur dem Adel zustehen', 'Dass Rechte bedeutungslos sind'], 'Rechte begrenzen, was Herrschaft darf.', 'Freiheit und Rechte wurden als Begründung gegen Willkür genutzt. Nicht alle Menschen waren faktisch gleichberechtigt. Dennoch wurde die Idee politisch wirkmächtig.', 'Die USA betonten unveräußerliche ___.', ['Rechte']),
    fact('vorbild', 'Warum wurden die USA für Europäer interessant?', 'Weil sie ein republikanisches Gegenmodell zur Alleinherrschaft zeigten', ['Weil sie den Absolutismus Ludwigs XIV. kopierten', 'Weil sie das Lehnswesen wiedereinführten', 'Weil sie Geschichte abschafften'], 'Das amerikanische Experiment wirkte als Vorbild und Streitfall.', 'Viele Europäer beobachteten Verfassung und Republik aufmerksam. Die Französische Revolution griff verwandte Ideen auf. Transatlantische Bezüge gehören zur Epoche.', 'Die USA zeigten ein ___ zur Alleinherrschaft.', ['Gegenmodell', 'Vorbild']),
    fact('grenzen', 'Welche Grenze hatte die frühe US-Freiheit?', 'Viele Menschen, etwa Versklavte, waren ausgeschlossen', ['Alle Einwohner hatten sofort gleiches Stimmrecht', 'Es gab keine Verfassung', 'Nur Pharaonen durften wählen'], 'Idee und Praxis fielen auseinander.', 'Rechte auf dem Papier galten nicht für alle. Sklaverei und Ausschluss widersprachen den eigenen Grundsätzen. Historische Beurteilung muss beides nennen.', 'Frühe US-Freiheit schloss viele Menschen ___.', ['aus', 'ausgeschlossen']),
    fact('zustimmung', 'Was meint Zustimmung der Regierten?', 'Dass legitime Macht von den Beherrschten ausgehen soll', ['Dass nur der König zustimmen darf', 'Dass Bauern keine Meinung haben dürfen', 'Dass Verfassungen verboten sind'], 'Zustimmung widerspricht reiner Alleinherrschaft.', 'Herrschaft braucht Rechtfertigung durch die Regierten. Wahlen und Verfassung sollen das absichern. Das ist ein Kern moderner Politikideen.', 'Legitime Macht soll von den ___ ausgehen.', ['Regierten', 'Beherrschten']),
  ],
  pairs: [
    pair('p1', 'Unabhängigkeit 1776', 'Bruch mit der britischen Krone', 'Rechte und Zustimmung als Begründung.'),
    pair('p2', 'Gewaltenteilung', 'Machtverteilung auf Organe', 'Soll Missbrauch erschweren.'),
    pair('p3', 'Verfassung', 'Grundregeln des Staates', 'Begrenzt Herrschaft durch Recht.'),
  ],
  trueFalse: [
    tf('t1', 'Die frühen USA stützten Herrschaft auf Zustimmung der Regierten und eine Verfassung.', true, 'Unabhängigkeit und Verfassungsideen gehörten zusammen.', '1776 und die spätere Verfassung verbanden Rechte mit institutioneller Ordnung. Das wurde zum Gegenbild reiner Alleinherrschaft. Grenzen der Praxis bleiben zu bedenken.'),
  ],
  sources: alleinherrschaft.sources?.filter((s) => s.concept === 'src-usa'),
  causeEffects: alleinherrschaft.causeEffects?.filter((c) => c.concept === 'ce-usa'),
}

const franzoesischeRevolution: BioBank = {
  quelle: 'Wikipedia: Französische Revolution',
  url: 'https://de.wikipedia.org/wiki/Franz%C3%B6sische_Revolution',
  conceptPrefix: 'ge:k7:fr-revolution',
  facts: [
    fact('fr', 'Was griff die Französische Revolution gegen die alte Herrschaft an?', 'Privilegien, Ständegesellschaft und unkontrollierte Monarchie', ['Nur den Buchdruck', 'Nur römisches Bürgerrecht', 'Nur mittelalterliche Stadtmauern'], 'Die Revolution zielte auf grundlegende politische Veränderung.', 'Die Französische Revolution von 1789 wandte sich gegen Privilegien des Ancien Régime. Sie stellte infrage, dass Herrschaft von Geburt abhängen dürfe. Freiheit, Gleichheit und Volkssouveränität wurden zentrale Begriffe.', 'Die Französische Revolution griff Privilegien und die alte ___ an.', ['Ständegesellschaft', 'Monarchie']),
    fact('1789', 'Welches Jahr gilt als Beginn der Französischen Revolution?', '1789', ['1215', '1689', '1914'], '1789 markiert den Umbruch in Frankreich.', 'Mit dem Jahr 1789 verbinden sich Einberufung der Generalstände, Bastille und erste revolutionäre Schritte. Das Datum ist ein Schlüsseljahr der Neuzeit. Es verändert das Bild legitimer Herrschaft.', 'Die Französische Revolution begann ___ .', ['1789']),
    fact('volk', 'Was meint Volkssouveränität?', 'Dass politische Macht vom Volk ausgehen soll', ['Dass nur der König Souverän ist', 'Dass Bauern keine Rechte haben', 'Dass Parlamente verboten sind'], 'Volkssouveränität widerspricht Alleinherrschaft.', 'Die Idee macht das Volk zum Träger der Macht. Revolutionäre forderten Mitbestimmung und Rechte. Das wurde zum Leitmotiv moderner Demokratien.', 'Volkssouveränität meint Macht vom ___.', ['Volk']),
    fact('rechte', 'Welche Erklärung wurde 1789 besonders wichtig?', 'Die Erklärung der Menschen- und Bürgerrechte', ['Die Magna Carta von 1215 allein', 'Die Bill of Rights ohne Bezug', 'Der Versailler Vertrag'], 'Rechte sollten Herrschaft begrenzen.', 'Die Erklärung formulierte Freiheit und Gleichheit vor dem Gesetz. Sie wurde zum Bezugspunkt. Praxis und Terror zeigten aber auch Widersprüche.', '1789 wurde die Erklärung der Menschen- und ___ wichtig.', ['Bürgerrechte']),
    fact('terror', 'Warum ist die Phase des Terrors historisch umstritten?', 'Weil Revolutionäre Gewalt im Namen der Freiheit einsetzten', ['Weil es keine Gewalt gab', 'Weil der König absolut siegte', 'Weil nur Sport stattfand'], 'Freiheit und Gewalt traten in Spannung.', 'Die Revolution radikalierte sich. Gegner wurden verfolgt und hingerichtet. Historiker bewerten Ziele und Mittel kontrovers.', 'Im Terror wurde Gewalt im Namen der ___ eingesetzt.', ['Freiheit', 'Revolution']),
    fact('stand', 'Was war der Dritte Stand?', 'Die große Mehrheit außerhalb von Klerus und Adel', ['Nur der Königshof', 'Nur die römischen Konsuln', 'Nur die Pharaonen'], 'Der Dritte Stand forderte politische Anerkennung.', 'Bürger, Bauern und andere trugen Lasten ohne gleiche Rechte. Ihre Emanzipation war zentral. Das sprengte die Ständeordnung.', 'Der Dritte Stand umfasste die große ___ außerhalb von Klerus und Adel.', ['Mehrheit']),
    fact('karikatur', 'Warum eignen sich Karikaturen als Quelle zur Revolution?', 'Weil sie Kritik, Feindbilder und politische Botschaften zuspitzen', ['Weil sie immer neutral sind', 'Weil sie keine Absicht haben', 'Weil sie nur Wetter zeigen'], 'Karikaturen sind parteilich und aussagekräftig.', 'Überzeichnung macht Standpunkte sichtbar. Historiker fragen nach Absicht und Publikum. Der Lehrplan nennt die Quellenart ausdrücklich.', 'Karikaturen spitzen politische ___ zu.', ['Botschaften', 'Kritik']),
    fact('erbe', 'Welches Erbe hinterließ die Revolution langfristig?', 'Ideen von Rechten, Nation und politischer Teilhabe', ['Die Rückkehr zum reinen Lehnswesen', 'Die Abschaffung jeder Verfassungsidee', 'Nur mittelalterliche Zünfte'], 'Trotz Widersprüchen wirkten die Ideen weiter.', 'Menschenrechte und Nation wurden Leitbegriffe. Europa und die Welt reagierten unterschiedlich. Das Erbe bleibt umkämpft und zentral.', 'Die Revolution hinterließ Ideen von Rechten und ___.', ['Teilhabe', 'Nation']),
  ],
  pairs: [
    pair('p1', 'Volkssouveränität', 'Macht soll vom Volk ausgehen', 'Kernidee gegen Alleinherrschaft.'),
    pair('p2', '1789', 'Beginn der Französischen Revolution', 'Schlüsseljahr der Neuzeit.'),
    pair('p3', 'Menschen- und Bürgerrechte', 'Erklärung von Freiheit und Gleichheit', 'Sollte Herrschaft begrenzen.'),
  ],
  trueFalse: [
    tf('t1', 'Die Französische Revolution griff Privilegien und unkontrollierte Monarchie an.', true, 'Ständegesellschaft und Alleinherrschaft standen infrage.', '1789 begann ein Umbruch, der Rechte und Volkssouveränität in den Mittelpunkt rückte. Gewalt und Widersprüche gehören zur Bewertung. Das Thema ist Kern des Lehrplans.'),
  ],
  causeEffects: alleinherrschaft.causeEffects?.filter((c) => c.concept === 'ce-fr'),
}

const napoleonBank: BioBank = {
  quelle: 'Wikipedia: Napoleon Bonaparte',
  url: 'https://de.wikipedia.org/wiki/Napoleon_Bonaparte',
  conceptPrefix: 'ge:k7:napoleon',
  facts: [
    fact('kaisertum', 'Was kennzeichnete Napoleons Kaisertum?', 'Persönliche Herrschaft nach der Revolution mit militärischer Machtbasis', ['Eine reine attische Demokratie', 'Ein mittelalterliches Lehnswesen ohne Heer', 'Eine Ablehnung jeder Ordnung'], 'Napoleon beendete und formte die Revolutionszeit neu.', 'Aus der Revolution ging eine starke Führungsfigur hervor. Napoleon krönte sich zum Kaiser und führte Kriege in Europa. Freiheitspathos und Herrschaftsanspruch traten in Spannung.', 'Napoleon errichtete ein ___ nach der Revolution.', ['Kaisertum']),
    fact('ende', 'Warum gehört Napoleon zum Thema Beschränkung der Alleinherrschaft?', 'Weil nach revolutionärer Begrenzung wieder persönliche Herrschaft entstand', ['Weil er die Magna Carta erfand', 'Weil er nur Steinzeitforschung betrieb', 'Weil er den Absolutismus Ludwigs XIV. unverändert fortsetzte'], 'Die Revolution begrenzte Macht, Napoleon verdichtete sie neu.', 'Das zeigt, dass Alleinherrschaft in neuer Form zurückkehren kann. Bewertung muss Revolution und Kaiserreich zusammensehen. Herrschaftsformen sind wandelbar.', 'Nach der Revolution entstand unter Napoleon wieder persönliche ___.', ['Herrschaft']),
    fact('code', 'Wofür steht der Code civil grob?', 'Für eine einheitliche Rechtsordnung unter Napoleon', ['Für ein mittelalterliches Zunftstatut allein', 'Für den Versailler Vertrag', 'Für attische Ostraka'], 'Recht wurde vereinheitlicht und exportiert.', 'Der Code civil ordnete Zivilrecht neu. Er wirkte in besetzten und verbündeten Gebieten. Rechtsgleichheit und patriarchale Grenzen gehörten dazu.', 'Der Code civil war eine einheitliche ___.', ['Rechtsordnung']),
    fact('europa', 'Wie veränderte Napoleon Europa?', 'Durch Kriege, Neuordnung von Staaten und Verbreitung von Reformideen', ['Durch Gründung des Völkerbunds 1919', 'Durch Abschaffung aller Heere', 'Durch Rückkehr zur Steinzeit'], 'Militärische Expansion und Reformen gingen zusammen.', 'Viele Territorien wurden umgeordnet. Manche Reformen blieben, andere stießen auf Widerstand. Europa nach 1815 reagierte darauf.', 'Napoleon veränderte Europa durch Kriege und ___.', ['Neuordnung', 'Reformen']),
    fact('widerstand', 'Warum entstand Widerstand gegen Napoleon?', 'Weil Besatzung, Kriegslasten und Herrschaftsanspruch Ablehnung erzeugten', ['Weil er zu wenig Macht wollte', 'Weil er keine Armee hatte', 'Weil er nur Frieden stiftete'], 'Herrschaft nach außen erzeugte Gegner.', 'Nationale und dynastische Kräfte formierten sich. Die späteren Koalitionskriege beendeten seine Herrschaft. Folgen wirkten im 19. Jahrhundert nach.', 'Kriegslasten und Besatzung erzeugten ___.', ['Widerstand', 'Ablehnung']),
    fact('karikatur', 'Warum wurden Karikaturen über Napoleon verbreitet?', 'Weil sie Macht, Krieg und Selbstinszenierung kritisierten oder überzeichneten', ['Weil Karikaturen verboten und unmöglich waren', 'Weil sie nur Wetter zeigten', 'Weil Napoleon anonym blieb'], 'Karikatur ist Lehrplan-Quellenart.', 'Bilder transportierten politische Botschaften. Historiker lesen Absicht und Publikum mit. Kritik an Alleinherrschaft erscheint oft satirisch.', 'Karikaturen überzeichneten Napoleons ___ und Krieg.', ['Macht', 'Herrschaft']),
    fact('erbe', 'Welches ambivalente Erbe hinterließ Napoleon?', 'Reformen und Rechtsideen neben Krieg und persönlicher Herrschaft', ['Nur reine Demokratie ohne Krieg', 'Nur Steinzeitwerkzeuge', 'Nur die Abschaffung jedes Rechts'], 'Fortschritt und Gewalt lagen nah beieinander.', 'Code civil und Verwaltung wirkten fort. Gleichzeitig kosteten Kriege unzählige Menschenleben. Historische Bewertung bleibt kontrovers.', 'Napoleons Erbe verbindet Reformen mit ___.', ['Krieg', 'Herrschaft']),
    fact('lehrplan', 'Warum nennt der Lehrplan das Kaisertum Napoleons explizit?', 'Weil es zeigt, wie Alleinherrschaft nach revolutionärer Begrenzung neu entstehen kann', ['Weil Napoleon die Steinzeit erforschte', 'Weil er den Buchdruck erfand', 'Weil er nur Sachsens Kurfürst war'], 'Revolution und Kaisertum gehören zusammen betrachtet.', 'Schüler sollen Wandel von Herrschaftsformen verstehen. Begrenzung und erneute Verdichtung von Macht sind das Thema. Napoleon ist das Schlüsselfigur-Beispiel.', 'Napoleon zeigt erneute ___ von Herrschaft nach der Revolution.', ['Verdichtung', 'Personalisierung']),
  ],
  pairs: [
    pair('p1', 'Kaisertum', 'Persönliche Herrschaft Napoleons', 'Nach der Revolution neu verdichtet.'),
    pair('p2', 'Code civil', 'Zivilrechtskodifikation', 'Vereinheitlichte Recht unter Napoleon.'),
    pair('p3', 'Koalitionskriege', 'Kriege gegen und um Napoleon', 'Endeten seine Vorherrschaft.'),
  ],
  trueFalse: [
    tf('t1', 'Unter Napoleon entstand nach der Revolution erneut eine starke persönliche Herrschaft.', true, 'Das Kaisertum verdichtete Macht in einer Person.', 'Die Revolution hatte Alleinherrschaft infrage gestellt. Napoleon formte daraus ein neues Herrschaftsmodell. Genau diese Spannung ist lehrplanrelevant.'),
  ],
}

export const GESCHICHTE_K7_GENERATORS: Record<string, Topic['generate']> = {
  'ge-k7-lb1-neuzeit': bankGenerate(neuzeit),
  'ge-k7-lb2-absolutismus': bankGenerate(absolutismus),
  'ge-k7-lb3-alleinherrschaft': bankGenerate(alleinherrschaft),
  'ge-k7-lb3-england': bankGenerate(englandParlament),
  'ge-k7-lb3-usa': bankGenerate(usaVerfassung),
  'ge-k7-lb3-franzoesische-revolution': bankGenerate(franzoesischeRevolution),
  'ge-k7-lb3-napoleon': bankGenerate(napoleonBank),
  'ge-k7-lb4-legitimation': bankGenerate(legitimation),
  'ge-k7-lbw-reformation-gerechtigkeit': bankGenerate(reformGerechtigkeit),
  'ge-k7-lbw-reformation-sachsen': bankGenerate(reformSachsen),
  'ge-k7-lbw-reformation-katholisch': bankGenerate(reformKatholisch),
}
