import { bankGenerate, type BioBank } from './biologieBank'
import type { Topic } from './types'

const fact = (
  concept: string,
  prompt: string,
  answer: string,
  wrong: [string, string, string],
  explanation: string,
  wissen: string,
  gap: string,
  gapAccepted: string[],
) => ({ concept, prompt, answer, wrong, explanation, wissen, gap, gapAccepted })

const pair = (concept: string, term: string, meaning: string, wissen: string) => ({
  concept,
  term,
  meaning,
  wissen,
})

const tf = (
  concept: string,
  statement: string,
  correct: boolean,
  explanation: string,
  wissen: string,
) => ({ concept, statement, correct, explanation, wissen })

const nachWk1: BioBank = {
  quelle: 'Wikipedia: Versailler Vertrag',
  url: 'https://de.wikipedia.org/wiki/Versailler_Vertrag',
  conceptPrefix: 'ge:k9:nach-wk1',
  facts: [
    fact(
      'versailles',
      'Was regelte der Versailler Vertrag von 1919?',
      'Er legte Friedensbedingungen für Deutschland nach dem Ersten Weltkrieg fest',
      ['Er gründete das Kurfürstentum Sachsen', 'Er beendete die Französische Revolution', 'Er führte den Buchdruck ein'],
      'Versailles war ein zentraler Teil der Nachkriegsordnung.',
      'Der Versailler Vertrag von 1919 war einer der wichtigsten Friedensverträge nach dem Ersten Weltkrieg. Er regelte Gebietsverluste, Abrüstung, Reparationen und politische Bedingungen für Deutschland. Viele Deutsche empfanden ihn als hart und demütigend.',
      'Der Versailler Vertrag legte die Friedensbedingungen für ___ fest.',
      ['Deutschland'],
    ),
    fact(
      'kriegsschuldartikel',
      'Warum war der sogenannte Kriegsschuldartikel in Deutschland besonders umstritten?',
      'Weil er Deutschland und seinen Verbündeten die Verantwortung für Kriegsschäden zuschrieb',
      ['Weil er Deutschland sofort in die EU aufnahm', 'Weil er die Monarchie wieder einführte', 'Weil er nur Österreichs Innenpolitik regelte'],
      'Der Artikel traf nationale Gefühle und politische Deutungen stark.',
      'Im Versailler Vertrag wurde Deutschland und seinen Verbündeten die Verantwortung für Schäden des Krieges zugeschrieben. Dieser Artikel war politisch und emotional besonders umkämpft. Er wurde in der Weimarer Republik von vielen Gegnern des neuen Staates propagandistisch ausgeschlachtet.',
      'Der Kriegsschuldartikel schrieb Deutschland die Verantwortung für Kriegs___ zu.',
      ['schäden', 'Schaeden'],
    ),
    fact(
      'voelkerbund',
      'Welche Aufgabe hatte der Völkerbund?',
      'Er sollte Konflikte friedlich regeln und internationale Zusammenarbeit fördern',
      ['Er war eine geheime Militärallianz', 'Er ersetzte alle nationalen Regierungen', 'Er war nur ein deutscher Reichstag'],
      'Der Völkerbund war ein früher Versuch internationaler Friedenssicherung.',
      'Der Völkerbund wurde nach dem Ersten Weltkrieg gegründet, um Kriege künftig zu verhindern. Staaten sollten Konflikte diplomatisch lösen und zusammenarbeiten. Seine Möglichkeiten blieben aber begrenzt, weil wichtige Mächte zeitweise fehlten oder Regeln missachteten.',
      'Der Völkerbund sollte Konflikte ___ regeln.',
      ['friedlich'],
    ),
    fact(
      'neue-staaten',
      'Warum entstanden nach 1918 in Europa neue Staaten?',
      'Weil große Reiche zerfielen und nationale Selbstbestimmung an Bedeutung gewann',
      ['Weil das Mittelalter zurückkehrte', 'Weil alle Monarchen Europas ein gemeinsames Reich wollten', 'Weil Kolonien nach Amerika verlegt wurden'],
      'Nach Kriegsende wurde Europa politisch neu geordnet.',
      'Nach dem Ersten Weltkrieg zerfielen das Deutsche, das Habsburger, das Russische und das Osmanische Reich in ihrer alten Form. Neue Grenzen und Staaten entstanden, oft unter Berufung auf nationale Selbstbestimmung. Diese Ordnung blieb jedoch vielerorts umstritten.',
      'Neue Staaten entstanden, weil alte ___ zerfielen.',
      ['Reiche'],
    ),
    fact(
      'reparationen',
      'Was waren Reparationen?',
      'Leistungen eines besiegten Staates zur Wiedergutmachung von Kriegsschäden',
      ['Freiwillige Kulturspenden an Museen', 'Wahlversprechen demokratischer Parteien', 'Mittelalterliche Lehnsabgaben an Ritter'],
      'Reparationen belasteten Politik und Wirtschaft der Nachkriegszeit.',
      'Reparationen sollten Kriegsschäden ausgleichen, die der Krieg in anderen Ländern verursacht hatte. Für Deutschland wurden sie zu einer wirtschaftlichen und politischen Belastung. In der öffentlichen Debatte wirkten sie als ständiger Streitpunkt der Nachkriegsordnung.',
      'Reparationen waren Leistungen zur Wiedergutmachung von Kriegs___.',
      ['schäden', 'Schaeden'],
    ),
    fact(
      'friedensordnung',
      'Warum spricht man nach 1918 von Nachkriegsordnungen und nicht nur von einem einzigen Vertrag?',
      'Weil mehrere Friedensverträge verschiedene Staaten und Regionen neu ordneten',
      ['Weil es überhaupt keine Verträge gab', 'Weil nur Deutschland betroffen war', 'Weil Frieden allein durch Zeitungsartikel entstand'],
      'Die Ordnung nach 1918 war vielschichtig.',
      'Die Nachkriegsordnung nach 1918 bestand aus mehreren Verträgen, nicht nur aus Versailles. Unterschiedliche Staaten und Regionen wurden jeweils neu geregelt. Gerade deshalb muss man von Nachkriegsordnungen im Plural sprechen.',
      'Nach 1918 gab es mehrere Friedens___ für verschiedene Staaten.',
      ['verträge', 'Vertraege'],
    ),
    fact(
      'minderheiten',
      'Warum blieben trotz neuer Grenzen viele Konflikte bestehen?',
      'Weil Minderheiten, Grenzfragen und nationale Ansprüche nicht einfach verschwanden',
      ['Weil nach 1918 alle Nationen vollkommen zufrieden waren', 'Weil Grenzen in Europa keine Rolle spielten', 'Weil der Völkerbund jede Krise sofort löste'],
      'Neue Staaten bedeuteten nicht automatisch stabile Verhältnisse.',
      'Auch nach der Neuordnung Europas lebten viele Minderheiten in fremd gewordenen Staaten. Grenzfragen und nationale Ansprüche blieben umstritten. Die neue Friedensordnung war daher von Beginn an belastet.',
      'Konflikte blieben wegen Minderheiten, Grenzfragen und nationalen ___.',
      ['Ansprüchen', 'Anspruechen'],
    ),
    fact(
      'bewertung',
      'Warum wird die Nachkriegsordnung nach 1918 unterschiedlich bewertet?',
      'Weil sie Frieden sichern sollte, zugleich aber neue Spannungen und Enttäuschungen erzeugte',
      ['Weil sie völlig bedeutungslos war', 'Weil sie Europa vollständig einte', 'Weil sie keine Folgen für Deutschland hatte'],
      'Historische Urteile müssen Chancen und Probleme zugleich sehen.',
      'Die Friedensordnung nach 1918 sollte einen neuen Krieg verhindern und nationale Ansprüche ordnen. Zugleich erzeugte sie Unzufriedenheit, wirtschaftliche Belastungen und neue Konflikte. Deshalb wird sie historisch ambivalent beurteilt.',
      'Die Nachkriegsordnung sollte Frieden sichern, erzeugte aber auch neue ___.',
      ['Spannungen', 'Konflikte'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Versailler Vertrag',
      'Friedensvertrag mit Deutschland nach 1918',
      'Der Versailler Vertrag war ein Kernstück der Nachkriegsordnung. Er prägte Politik und Erinnerung in der Weimarer Republik stark.',
    ),
    pair(
      'p2',
      'Völkerbund',
      'Früher Versuch internationaler Friedenssicherung',
      'Der Völkerbund sollte Konflikte friedlich regeln. Seine begrenzte Durchsetzungskraft zeigte aber auch die Schwächen der Ordnung.',
    ),
    pair(
      'p3',
      'Reparationen',
      'Leistungen zur Wiedergutmachung von Kriegsschäden',
      'Reparationen wurden zu einem wirtschaftlichen und politischen Streitpunkt. Dadurch belasteten sie die junge Demokratie zusätzlich.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Die Nachkriegsordnung nach 1918 bestand nur aus dem Versailler Vertrag und betraf sonst keine anderen Staaten.',
      false,
      'Es gab mehrere Friedensverträge und eine umfassende Neuordnung Europas.',
      'Nach 1918 wurden verschiedene Reiche und Regionen durch mehrere Verträge neu geordnet. Neben Deutschland betraf dies auch Österreich, Ungarn, das Osmanische Reich und weitere Gebiete. Der Plural "Nachkriegsordnungen" ist deshalb sachlich wichtig.',
    ),
  ],
}

const demokratieDiktatur: BioBank = {
  quelle: 'Wikipedia: Weimarer Republik',
  url: 'https://de.wikipedia.org/wiki/Weimarer_Republik',
  conceptPrefix: 'ge:k9:demokratie-diktatur',
  facts: [
    fact(
      'weimar',
      'Was war die Weimarer Republik?',
      'Deutschlands erste parlamentarische Demokratie von 1918/19 bis 1933',
      ['Das Kaiserreich des 19. Jahrhunderts', 'Ein mittelalterliches Kurfürstentum', 'Eine französische Monarchie'],
      'Die Weimarer Republik war ein demokratischer Neuanfang unter schwierigen Bedingungen.',
      'Die Weimarer Republik entstand nach dem Ende des Kaiserreichs und war Deutschlands erste Demokratie. Sie besaß Wahlen, Parlament und Grundrechte. Gleichzeitig musste sie mit Kriegsfolgen, politischen Feinden und wirtschaftlichen Krisen umgehen.',
      'Die Weimarer Republik war Deutschlands erste parlamentarische ___.',
      ['Demokratie'],
    ),
    fact(
      'verfassung',
      'Was kennzeichnete die Weimarer Verfassung?',
      'Sie regelte demokratische Wahlen, Grundrechte und die Gewaltenteilung',
      ['Sie machte den Kaiser wieder allmächtig', 'Sie schaffte Parteien vollständig ab', 'Sie führte das Lehnswesen erneut ein'],
      'Die Verfassung legte den demokratischen Rahmen fest.',
      'Die Weimarer Verfassung von 1919 schuf die Grundlage der neuen Demokratie. Sie regelte Wahlen, Grundrechte, Reichstag, Regierung und Reichspräsident. Zugleich enthielt sie mit Artikel 48 auch Möglichkeiten für Notverordnungen.',
      'Die Weimarer Verfassung regelte Wahlen, Grundrechte und die ___.',
      ['Gewaltenteilung'],
    ),
    fact(
      'hyperinflation',
      'Warum war die Hyperinflation von 1923 für die Republik so gefährlich?',
      'Weil Geld rapide an Wert verlor und viele Menschen Vertrauen in Staat und Wirtschaft verloren',
      ['Weil dadurch alle Schulden der Welt sofort verschwanden', 'Weil nur ausländische Staaten betroffen waren', 'Weil Inflation politische Fragen nie beeinflusst'],
      'Wirtschaftskrisen untergraben politische Stabilität.',
      '1923 entwertete sich die deutsche Währung extrem schnell. Ersparnisse wurden vernichtet, Alltag und Handel gerieten durcheinander und das Vertrauen in die Republik litt stark. Solche Erfahrungen machten demokratische Politik für viele Menschen anfälliger für Ablehnung.',
      'Die Hyperinflation zerstörte Ersparnisse und politisches ___.',
      ['Vertrauen'],
    ),
    fact(
      'weltwirtschaftskrise',
      'Warum traf die Weltwirtschaftskrise ab 1929 die Weimarer Republik so schwer?',
      'Weil Arbeitslosigkeit, Armut und politische Radikalisierung stark zunahmen',
      ['Weil Deutschland wirtschaftlich völlig unabhängig war', 'Weil die Krise nur die USA betraf', 'Weil Parlamente in Krisen automatisch stärker werden'],
      'Soziale Not stärkte radikale Parteien.',
      'Die Weltwirtschaftskrise führte in Deutschland zu Massenarbeitslosigkeit und großer sozialer Unsicherheit. Viele Menschen verloren den Glauben an demokratische Lösungen. Dadurch gewannen antidemokratische Kräfte Zulauf.',
      'Die Weltwirtschaftskrise verstärkte Arbeitslosigkeit, Armut und politische ___.',
      ['Radikalisierung'],
    ),
    fact(
      'praesidialkabinette',
      'Was waren Präsidialkabinette in der Endphase Weimars?',
      'Regierungen, die sich stark auf den Reichspräsidenten und Notverordnungen stützten',
      ['Ausschüsse nur für Kulturpolitik', 'Verfassungen einzelner Bundesländer', 'Militärbündnisse der Siegerstaaten'],
      'Die parlamentarische Demokratie geriet dadurch in eine Krise.',
      'In den letzten Jahren der Weimarer Republik regierten mehrere Kabinette ohne stabile Parlamentsmehrheit. Sie stützten sich stark auf den Reichspräsidenten und Notverordnungen. Das schwächte den parlamentarischen Charakter der Demokratie.',
      'Präsidialkabinette stützten sich stark auf den Reichs___ und Notverordnungen.',
      ['präsidenten', 'Praesidenten'],
    ),
    fact(
      'nsdap-aufstieg',
      'Warum gewann die NSDAP in der Krise an Zustimmung?',
      'Weil sie Ängste, Unzufriedenheit und Feindbilder politisch ausnutzte',
      ['Weil sie die Demokratie konsequent verteidigte', 'Weil sie keine Propaganda einsetzte', 'Weil alle Wähler ihre Ziele teilten'],
      'Krisen boten Nährboden für antidemokratische Vereinfachungen.',
      'Die NSDAP nutzte wirtschaftliche Not, politische Enttäuschung und gesellschaftliche Spannungen gezielt aus. Mit Propaganda, Versprechen und Feindbildern gewann sie Wähler. Ihr Aufstieg zeigt, wie verletzlich Demokratien in Krisenzeiten sein können.',
      'Die NSDAP nutzte Ängste und politische ___ aus.',
      ['Unzufriedenheit'],
    ),
    fact(
      'ernennung-hitler',
      'Warum war der 30. Januar 1933 ein Wendepunkt?',
      'Weil Hitler zum Reichskanzler ernannt wurde und so legal an die Regierung kam',
      ['Weil Deutschland eine neue demokratische Verfassung erhielt', 'Weil der Weltkrieg an diesem Tag endete', 'Weil der Kaiser zurückkehrte'],
      'Die Diktatur begann nicht nur durch Gewalt, sondern auch durch politische Entscheidungen.',
      'Am 30. Januar 1933 ernannte Reichspräsident Hindenburg Adolf Hitler zum Reichskanzler. Damit gelangten die Nationalsozialisten auf legalem Weg in die Regierung. Dieser Schritt war ein entscheidender Übergang von der Krise der Demokratie zur Diktatur.',
      'Am 30. Januar 1933 wurde Hitler zum Reichs___ ernannt.',
      ['kanzler', 'Kanzler'],
    ),
    fact(
      'ermachtigung',
      'Warum war das Ermächtigungsgesetz von 1933 so folgenschwer?',
      'Weil es der Regierung erlaubte, ohne Parlament Gesetze zu erlassen',
      ['Weil es freie Wahlen ausweitete', 'Weil es die Gewaltenteilung stärkte', 'Weil es Grundrechte dauerhaft schützte'],
      'Mit dem Gesetz wurde die Demokratie rechtlich ausgehebelt.',
      'Das Ermächtigungsgesetz vom März 1933 gab der Regierung weitreichende Gesetzgebungsrechte. Parlamentarische Kontrolle wurde damit massiv ausgeschaltet. So wurde die Diktatur auch juristisch abgesichert.',
      'Das Ermächtigungsgesetz erlaubte Gesetze ohne ___.',
      ['Parlament'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Weimarer Republik',
      'Erste deutsche Demokratie von 1918/19 bis 1933',
      'Die Weimarer Republik war ein demokratischer Neubeginn. Ihre Krisen zeigen, wie verletzlich Demokratie sein kann.',
    ),
    pair(
      'p2',
      'Hyperinflation',
      'Extreme Geldentwertung im Jahr 1923',
      'Die Hyperinflation zerstörte Vermögen und Vertrauen. Sie gehört zu den prägenden Krisenerfahrungen der Republik.',
    ),
    pair(
      'p3',
      'Ermächtigungsgesetz',
      'Gesetz von 1933 zur Ausschaltung des Parlaments',
      'Mit dem Ermächtigungsgesetz wurde demokratische Kontrolle massiv eingeschränkt. Es gehört zu den Schlüsselschritten in die Diktatur.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Die Weimarer Republik scheiterte nur an einem einzigen Ereignis und nicht an einer Kette aus Krisen, Entscheidungen und Feinden der Demokratie.',
      false,
      'Mehrere Faktoren wirkten zusammen: Wirtschaftskrisen, politische Entscheidungen und antidemokratische Kräfte.',
      'Historische Entwicklungen verlaufen selten monokausal. Das Ende der Weimarer Republik erklärt sich aus strukturellen Problemen, Krisenerfahrungen, Machtentscheidungen und dem gezielten Angriff von Demokratiefeinden. Gerade dieses Zusammenwirken macht das Thema wichtig.',
    ),
  ],
}

const nsDiktatur: BioBank = {
  quelle: 'Wikipedia: Nationalsozialismus',
  url: 'https://de.wikipedia.org/wiki/Nationalsozialismus',
  conceptPrefix: 'ge:k9:ns-diktatur',
  facts: [
    fact(
      'gleichschaltung',
      'Was meint "Gleichschaltung" im Nationalsozialismus?',
      'Die erzwungene Anpassung von Staat, Gesellschaft und Organisationen an das NS-Regime',
      ['Die freie Zusammenarbeit aller Parteien', 'Nur technischen Ausbau des Stromnetzes', 'Die Wiederherstellung mittelalterlicher Zünfte'],
      'Gleichschaltung zerstörte politische und gesellschaftliche Vielfalt.',
      'Mit Gleichschaltung meint man die systematische Unterordnung von Institutionen, Vereinen, Medien und Verbänden unter die NS-Herrschaft. Unabhängige Stimmen wurden ausgeschaltet. So wurde aus einer pluralen Gesellschaft ein diktatorisch kontrollierter Raum.',
      'Gleichschaltung bedeutete die erzwungene ___ an das NS-Regime.',
      ['Anpassung'],
    ),
    fact(
      'terror',
      'Welche Rolle spielte Terror in der NS-Diktatur?',
      'Er diente dazu, Gegner einzuschüchtern, auszuschalten und Gehorsam zu erzwingen',
      ['Er war im Regime verboten', 'Er betraf nur ausländische Staaten', 'Er wurde allein von Gerichten kontrolliert'],
      'Gewalt war ein Grundelement der Diktatur.',
      'Die NS-Diktatur stützte sich nicht nur auf Propaganda, sondern wesentlich auf Gewalt und Einschüchterung. Verhaftungen, Misshandlungen und Lager bedrohten politische Gegner und viele andere Gruppen. Terror war also kein Randphänomen, sondern Teil des Systems.',
      'Terror sollte Gegner einschüchtern und ___ erzwingen.',
      ['Gehorsam'],
    ),
    fact(
      'gestapo',
      'Was war die Gestapo?',
      'Die Geheime Staatspolizei des NS-Regimes',
      ['Ein demokratischer Bürgerverein', 'Ein Gericht des Völkerbunds', 'Eine Gewerkschaft der Weimarer Republik'],
      'Die Gestapo verfolgte Menschen im Namen der Diktatur.',
      'Die Gestapo war ein zentrales Instrument politischer Verfolgung im Nationalsozialismus. Sie überwachte, verhaftete und bedrohte Menschen, die als Gegner oder unerwünscht galten. Ihre Macht beruhte auch auf Angst und Denunziation.',
      'Die Gestapo war die Geheime Staats___.',
      ['polizei'],
    ),
    fact(
      'antisemitismus',
      'Warum war Antisemitismus ein Kernbestandteil der NS-Ideologie?',
      'Weil das Regime Juden systematisch ausgrenzte, entrechtete und als Feindbild verfolgte',
      ['Weil das Regime religiöse Vielfalt schützen wollte', 'Weil Juden politische Macht im Reich besaßen', 'Weil Antisemitismus nur eine Randmeinung einzelner Gegner war'],
      'Antisemitismus stand im Zentrum nationalsozialistischer Verfolgungspolitik.',
      'Antisemitismus war im Nationalsozialismus nicht nebensächlich, sondern zentral. Jüdinnen und Juden wurden schrittweise entrechtet, ausgegrenzt, beraubt und verfolgt. Aus dieser Ideologie entwickelte sich schließlich der Holocaust.',
      'Im NS-Regime wurden Juden systematisch ___ und verfolgt.',
      ['entrechtet', 'ausgegrenzt'],
    ),
    fact(
      'nuernberger-gesetze',
      'Was bewirkten die Nürnberger Gesetze von 1935?',
      'Sie entzogen Juden zentrale Rechte und machten Diskriminierung zum Gesetz',
      ['Sie stellten Demokratie wieder her', 'Sie schafften jede Rassentheorie ab', 'Sie führten allgemeine Pressefreiheit ein'],
      'Verfolgung wurde rechtlich festgeschrieben.',
      'Die Nürnberger Gesetze machten antisemitische Ausgrenzung staatlich verbindlich. Jüdinnen und Juden verloren Rechte und wurden aus der politischen Gemeinschaft ausgeschlossen. Daran zeigt sich, wie Diktatur und Unrecht auch juristisch organisiert wurden.',
      'Die Nürnberger Gesetze machten Diskriminierung zum ___.',
      ['Gesetz'],
    ),
    fact(
      'holocaust',
      'Was bezeichnet der Begriff Holocaust?',
      'Den nationalsozialistischen Völkermord an den europäischen Juden',
      ['Nur ein Wirtschaftsgesetz der Kriegszeit', 'Eine Friedenskonferenz nach 1945', 'Die Evakuierung deutscher Städte'],
      'Der Holocaust war ein einzigartiges Menschheitsverbrechen.',
      'Mit dem Begriff Holocaust bezeichnet man den systematischen Mord an den europäischen Juden durch das nationalsozialistische Deutschland und seine Helfer. Millionen Menschen wurden entrechtet, deportiert und ermordet. Das Thema verlangt sachliche Sprache und respektvolle Erinnerung.',
      'Der Holocaust war der nationalsozialistische Völker___ an den europäischen Juden.',
      ['mord', 'Völkermord', 'Voelkermord'],
    ),
    fact(
      'widerstand',
      'Gab es im Nationalsozialismus auch Widerstand?',
      'Ja, aber er war gefährlich, vielfältig und blieb gegenüber der Diktatur meist begrenzt',
      ['Nein, niemand widersprach jemals', 'Nur ausländische Regierungen leisteten Widerstand', 'Widerstand war ungefährlich und legal'],
      'Widerstand existierte, aber unter hohem Risiko.',
      'Im Nationalsozialismus gab es Menschen und Gruppen, die halfen, protestierten oder sich widersetzten. Dazu gehörten unterschiedliche Motive und Formen des Handelns. Wegen Terror und Überwachung war Widerstand jedoch äußerst gefährlich.',
      'Widerstand war möglich, aber für Beteiligte sehr ___.',
      ['gefährlich'],
    ),
    fact(
      'propaganda',
      'Warum reichte Propaganda allein nicht aus, um die NS-Diktatur zu erklären?',
      'Weil sie mit Gewalt, Verfolgung und institutioneller Macht zusammenwirkte',
      ['Weil Propaganda im Regime verboten war', 'Weil das Regime nur durch freie Wahlen bestand', 'Weil Gewalt im Nationalsozialismus keine Rolle spielte'],
      'Diktaturen stabilisieren sich meist durch mehrere Herrschaftsmittel zugleich.',
      'Propaganda war im Nationalsozialismus wichtig, aber nicht der einzige Machtfaktor. Erst im Zusammenspiel mit Polizei, Gesetzen, Terror und Ausgrenzung wurde die Diktatur so wirksam. Historische Erklärung muss diese Verbindung beachten.',
      'Propaganda wirkte im NS-Staat zusammen mit Gewalt und institutioneller ___.',
      ['Macht'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Gleichschaltung',
      'Erzwungene Unterordnung von Gesellschaft und Staat unter das Regime',
      'Gleichschaltung zerstörte Vielfalt und Unabhängigkeit. Dadurch konnte das Regime fast alle Bereiche kontrollieren.',
    ),
    pair(
      'p2',
      'Gestapo',
      'Geheime Staatspolizei des NS-Regimes',
      'Die Gestapo war ein Instrument von Angst und Verfolgung. Sie zeigt die repressive Seite der Diktatur besonders deutlich.',
    ),
    pair(
      'p3',
      'Holocaust',
      'Völkermord an den europäischen Juden',
      'Der Holocaust war ein einzigartiges Menschheitsverbrechen. Erinnerung und sachliche Aufklärung bleiben daher unverzichtbar.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Der Holocaust war ein zentraler Bestandteil nationalsozialistischer Verfolgungspolitik und kein zufälliges Nebenereignis.',
      true,
      'Antisemitismus und die systematische Verfolgung von Juden standen im Zentrum der NS-Ideologie.',
      'Nationalsozialistische Herrschaft zielte bewusst auf Ausgrenzung, Entrechtung und Vernichtung jüdischer Menschen. Der Holocaust war daher kein Randaspekt, sondern Teil des Kerns der Diktatur. Genau deshalb ist präzise historische Sprache hier besonders wichtig.',
    ),
  ],
}

const aussenpolitik: BioBank = {
  quelle: 'Wikipedia: Deutsche Außenpolitik',
  url: 'https://de.wikipedia.org/wiki/Deutsche_Au%C3%9Fenpolitik',
  conceptPrefix: 'ge:k9:aussenpolitik',
  facts: [
    fact(
      'bismarck',
      'Wofür stand Bismarcks Außenpolitik nach 1871 vor allem?',
      'Für Bündnisse und Ausgleich zur Sicherung des Reichs und Vermeidung eines großen Krieges',
      ['Für sofortige Kolonialkriege in ganz Europa', 'Für völlige Isolation Deutschlands ohne Diplomatie', 'Für die Auflösung jedes Bündnisses im Reich'],
      'Bismarck wollte das Reich nach der Gründung absichern.',
      'Nach 1871 versuchte Bismarck, das neue Deutsche Reich außenpolitisch abzusichern. Er knüpfte Bündnisse und suchte den Ausgleich mit anderen Mächten, um einen Mehrfrontenkrieg zu vermeiden. Stabilität stand stärker im Vordergrund als offener Machtzuwachs.',
      'Bismarck suchte außenpolitisch vor allem ___ und Absicherung.',
      ['Ausgleich'],
    ),
    fact(
      'weltpolitik',
      'Was änderte sich unter Wilhelm II. mit der sogenannten Weltpolitik?',
      'Deutschland trat offensiver auf und suchte mehr Einfluss als Weltmacht',
      ['Deutschland zog sich völlig aus der Außenpolitik zurück', 'Es kehrte zur mittelalterlichen Lehnspolitik zurück', 'Außenpolitik wurde nur noch von Städten bestimmt'],
      'Der Kurs wurde konfrontativer und risikoreicher.',
      'Unter Wilhelm II. änderte sich der außenpolitische Stil des Deutschen Reichs. Weltpolitik, Flottenbau und koloniale Ambitionen machten den Kurs offensiver. Dadurch verschärften sich Spannungen mit anderen Großmächten.',
      'Weltpolitik bedeutete ein offensiveres Streben nach weltweitem ___.',
      ['Einfluss'],
    ),
    fact(
      'weimar',
      'Warum gilt die Außenpolitik Stresemanns oft als Politik des Ausgleichs?',
      'Weil sie auf Verständigung, internationale Einbindung und schrittweise Revision setzte',
      ['Weil sie nur auf Eroberung zielte', 'Weil sie jede Zusammenarbeit ablehnte', 'Weil sie den Völkerbund bekämpfte'],
      'Stresemann verband nationale Interessen mit Diplomatie.',
      'Gustav Stresemann versuchte in den 1920er Jahren, Deutschland diplomatisch wieder handlungsfähig zu machen. Verständigung mit Frankreich und Eintritt in den Völkerbund gehörten dazu. Revision von Versailles sollte eher durch Verhandlung als durch Gewalt erreicht werden.',
      'Stresemann setzte eher auf Verständigung und diplomatischen ___.',
      ['Ausgleich'],
    ),
    fact(
      'locarno',
      'Warum waren die Locarno-Verträge wichtig?',
      'Weil sie zur Entspannung in Westeuropa beitrugen und Deutschlands Stellung verbesserten',
      ['Weil sie den Ersten Weltkrieg auslösten', 'Weil sie den Kaiser zurückbrachten', 'Weil sie nur Kolonialfragen in Afrika regelten'],
      'Locarno steht für eine Phase begrenzter Entspannung.',
      'Die Locarno-Verträge von 1925 verbesserten das Verhältnis Deutschlands zu westlichen Nachbarn. Sie trugen zu einer Phase der Entspannung bei und erleichterten die internationale Einbindung Deutschlands. Damit gehören sie zu den Erfolgen der Weimarer Außenpolitik.',
      'Locarno trug zu einer Phase der ___ in Westeuropa bei.',
      ['Entspannung'],
    ),
    fact(
      'ns-ap',
      'Wie unterschied sich die Außenpolitik des NS-Regimes von Stresemanns Kurs?',
      'Sie setzte auf aggressive Expansion, Vertragsbruch und Kriegsvorbereitung',
      ['Sie zielte vor allem auf friedliche Verständigung', 'Sie lehnte jede Gebietsveränderung ab', 'Sie stärkte den Völkerbund nachhaltig'],
      'Das NS-Regime ging von Ausgleich zu Konfrontation über.',
      'Die Außenpolitik des NS-Regimes war von Revision, Expansion und rassistischer Ideologie geprägt. Verträge wurden gebrochen, Aufrüstung betrieben und Krieg bewusst vorbereitet. Damit wandelte sich die deutsche Außenpolitik von Ausgleich zu offener Konfrontation.',
      'Die NS-Außenpolitik setzte auf Expansion, Vertragsbruch und ___.',
      ['Kriegsvorbereitung'],
    ),
    fact(
      'laengsschnitt',
      'Warum eignet sich deutsche Außenpolitik für einen Längsschnitt?',
      'Weil zwischen Ausgleich und Konfrontation über verschiedene Epochen hinweg verglichen werden kann',
      ['Weil Außenpolitik nur 1939 existierte', 'Weil alle Regierungen immer denselben Kurs verfolgten', 'Weil Diplomatie in der Geschichte unwichtig ist'],
      'Außenpolitik zeigt Wandel politischer Ziele und Mittel.',
      'Von Bismarck über Stresemann bis zum NS-Regime verändern sich Ziele, Mittel und Stil deutscher Außenpolitik deutlich. Gerade der Vergleich macht sichtbar, wann Diplomatie auf Ausgleich und wann Politik auf Konfrontation setzt. Darin liegt der Wert des Längsschnitts.',
      'Der Längsschnitt zeigt den Wechsel zwischen Ausgleich und ___.',
      ['Konfrontation'],
    ),
    fact(
      'voelkerbund',
      'Warum war der Eintritt Deutschlands in den Völkerbund 1926 bedeutsam?',
      'Weil Deutschland damit stärker international eingebunden und diplomatisch anerkannt wurde',
      ['Weil Deutschland dadurch sofort Kolonien zurückerhielt', 'Weil alle außenpolitischen Konflikte endeten', 'Weil der Völkerbund Deutschland zum Kaiserreich erklärte'],
      'Internationale Anerkennung war für Weimar wichtig.',
      'Der Eintritt in den Völkerbund markierte einen außenpolitischen Erfolg der Weimarer Republik. Deutschland wurde dadurch stärker in internationale Zusammenarbeit eingebunden. Das verbesserte seinen Handlungsspielraum, ohne alle Probleme zu lösen.',
      'Der Völkerbund-Eintritt brachte Deutschland diplomatische ___.',
      ['Anerkennung'],
    ),
    fact(
      'krieg',
      'Warum ist aggressive Außenpolitik besonders gefährlich?',
      'Weil sie Konflikte verschärft und in Aufrüstung oder Krieg münden kann',
      ['Weil sie immer automatisch Frieden sichert', 'Weil Außenpolitik keine Folgen für andere Staaten hat', 'Weil Diplomatie dadurch überflüssig wird'],
      'Außenpolitik prägt internationale Sicherheit direkt.',
      'Außenpolitik entscheidet mit darüber, ob Staaten auf Verhandlung oder Gewalt setzen. Wenn Regierungen systematisch auf Drohung, Aufrüstung und Expansion bauen, steigen internationale Risiken erheblich. Geschichte zeigt diese Gefahr sehr deutlich.',
      'Aggressive Außenpolitik kann Konflikte verschärfen und zu ___ führen.',
      ['Krieg'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Bismarck',
      'Außenpolitik des Ausgleichs zur Sicherung des Reichs',
      'Bismarck wollte nach 1871 vor allem Stabilität und Bündnisse. Er versuchte, große Kriege außenpolitisch zu vermeiden.',
    ),
    pair(
      'p2',
      'Locarno',
      'Verträge der Entspannung in den 1920er Jahren',
      'Locarno steht für Verständigung und diplomatische Einbindung. Es zeigt die Möglichkeiten einer Politik des Ausgleichs.',
    ),
    pair(
      'p3',
      'Weltpolitik',
      'Offensiver deutscher Großmachtkurs unter Wilhelm II.',
      'Weltpolitik verschärfte Konkurrenz und Spannungen. Sie markiert den Weg von Absicherung zu stärkerer Konfrontation.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Ein Längsschnitt zur deutschen Außenpolitik zeigt, dass alle Regierungen vom Kaiserreich bis zum NS-Regime denselben Kurs des friedlichen Ausgleichs verfolgten.',
      false,
      'Zwischen Bismarck, Weimar und NS-Regime gab es deutliche Unterschiede zwischen Ausgleich und Konfrontation.',
      'Gerade der historische Vergleich macht unterschiedliche außenpolitische Stile sichtbar. Bündnispolitik, Verständigungskurs und aggressive Expansion gehören nicht in dieselbe Kategorie. Außenpolitik verändert sich mit Zielen und Herrschaftsformen.',
    ),
  ],
}

const justiz: BioBank = {
  quelle: 'Wikipedia: Justiz im Nationalsozialismus',
  url: 'https://de.wikipedia.org/wiki/Justiz_im_Nationalsozialismus',
  conceptPrefix: 'ge:k9:justiz',
  facts: [
    fact(
      'weimar-recht',
      'Welche Aufgabe hat Justiz in einer Demokratie grundsätzlich?',
      'Sie soll Recht anwenden, Bürger schützen und staatliche Macht an Gesetze binden',
      ['Sie dient nur der Regierung ohne Regeln', 'Sie entscheidet nach Herkunft statt nach Recht', 'Sie ersetzt jede Wahl durch Befehle'],
      'Rechtsstaatliche Justiz begrenzt Macht.',
      'In einer Demokratie gehört Justiz zum Rechtsstaat. Gerichte sollen Gesetze anwenden, Rechte schützen und Macht kontrollieren. Gerade dadurch unterscheidet sich rechtsstaatliche Ordnung von Willkürherrschaft.',
      'In einer Demokratie soll Justiz Macht an ___ binden.',
      ['Gesetze', 'Recht'],
    ),
    fact(
      'weimar-probleme',
      'Warum war die Justiz in der Weimarer Republik nicht frei von Problemen?',
      'Weil alte Eliten, politische Vorurteile und ungleiche Urteile das Vertrauen belasteten',
      ['Weil es gar keine Gerichte gab', 'Weil nur Frauen Richterinnen waren', 'Weil Justiz nur im Ausland stattfand'],
      'Institutionen tragen oft alte Prägungen weiter.',
      'Die Weimarer Justiz war formal Teil eines demokratischen Staates, blieb aber personell und kulturell teilweise von älteren Traditionen geprägt. Politische Urteile fielen nicht immer gleich streng aus. Das schwächte das Vertrauen in rechtsstaatliche Neutralität.',
      'Die Weimarer Justiz litt teils unter alten Eliten und politischen ___.',
      ['Vorurteilen'],
    ),
    fact(
      'ns-justiz',
      'Was geschah mit der Justiz im Nationalsozialismus?',
      'Sie wurde dem Regime untergeordnet und half bei Verfolgung und Unrecht mit',
      ['Sie schützte konsequent alle Grundrechte', 'Sie blieb völlig unabhängig vom Staat', 'Sie löste die Polizei als einzige Behörde ab'],
      'Auch Gerichte können in Diktaturen zu Werkzeugen werden.',
      'Im Nationalsozialismus wurde Justiz nicht einfach abgeschafft, sondern gleichgeschaltet und politisch missbraucht. Gerichte, Gesetze und Richter halfen, Verfolgung zu legitimieren und Gegner zu bestrafen. Dadurch wurde Unrecht oft in eine scheinbar legale Form gebracht.',
      'Im NS-Staat wurde Justiz dem ___ untergeordnet.',
      ['Regime'],
    ),
    fact(
      'sondergerichte',
      'Wozu dienten Sondergerichte im NS-Staat?',
      'Zur schnellen politischen Verurteilung ohne rechtsstaatliche Sicherungen',
      ['Zur unabhängigen Kontrolle der Regierung', 'Zur Wahrung voller Pressefreiheit', 'Zur Aufarbeitung der Weimarer Inflation'],
      'Sondergerichte verschärften politischen Terror durch Rechtsschein.',
      'Sondergerichte urteilten im Nationalsozialismus oft schnell und hart gegen angebliche Gegner. Rechtsstaatliche Standards wurden stark eingeschränkt. So zeigte sich, wie Justiz zur Stütze einer Diktatur werden konnte.',
      'Sondergerichte dienten der schnellen politischen ___.',
      ['Verurteilung'],
    ),
    fact(
      'volksgerichtshof',
      'Was war der Volksgerichtshof?',
      'Ein NS-Sondergericht für politische Verfahren mit besonders harten Urteilen',
      ['Ein demokratisches Kontrollorgan des Parlaments', 'Die höchste Instanz des Völkerbunds', 'Eine Bürgerinitiative der Weimarer Zeit'],
      'Der Volksgerichtshof steht für politische Justiz im NS-Regime.',
      'Der Volksgerichtshof wurde zu einem Symbol nationalsozialistischer Unrechtsjustiz. In politischen Verfahren fällte er besonders harte Urteile, oft ohne faire rechtsstaatliche Bedingungen. Viele Gegner des Regimes wurden hier verurteilt und hingerichtet.',
      'Der Volksgerichtshof war ein Sondergericht für politische ___.',
      ['Verfahren'],
    ),
    fact(
      'rechtsstaat',
      'Was unterscheidet rechtsstaatliche von diktatorischer Justiz?',
      'Rechtsstaatliche Justiz schützt Rechte und Verfahren, diktatorische Justiz dient der Herrschaft',
      ['Diktatorische Justiz ist immer neutraler', 'Beide Formen sind praktisch identisch', 'Rechtsstaatliche Justiz braucht keine Gesetze'],
      'Die Funktion der Justiz hängt vom politischen System ab.',
      'Im Rechtsstaat sind Gerichte an Verfahren, Gesetze und Rechte gebunden. In einer Diktatur kann Justiz zum Werkzeug politischer Ziele werden. Der Vergleich zeigt, dass Recht nicht nur Texte, sondern auch Institutionen und Haltungen braucht.',
      'Diktatorische Justiz dient vor allem der ___ des Regimes.',
      ['Herrschaft'],
    ),
    fact(
      'kontinuitaeten',
      'Warum ist der Vergleich Weimar und NS historisch wichtig?',
      'Weil er zeigt, wie Institutionen geschwächt oder für Unrecht missbraucht werden können',
      ['Weil Justiz nur in Demokratien vorkommt', 'Weil sich Gerichte nie verändern', 'Weil Geschichte der Justiz ohne Politik verläuft'],
      'Institutionen müssen aktiv geschützt werden.',
      'Der Vergleich zwischen Weimarer Republik und NS-Staat zeigt, dass Justiz nicht automatisch gerecht bleibt. Personal, politische Kultur und Machtverhältnisse prägen ihr Handeln. Darin liegt eine wichtige Lehre über die Verletzlichkeit des Rechtsstaats.',
      'Der Vergleich zeigt die Verletzlichkeit des ___.',
      ['Rechtsstaats', 'Rechtsstaates'],
    ),
    fact(
      'urteil',
      'Warum sind gerechte Verfahren für Demokratie so zentral?',
      'Weil ohne faire Verfahren Recht leicht zur Willkür werden kann',
      ['Weil Verfahren nur Zeit kosten und politisch unwichtig sind', 'Weil Diktaturen auf faire Verfahren angewiesen sind', 'Weil nur Parlamente über Schuld entscheiden dürfen'],
      'Verfahren schützen Menschen vor Machtmissbrauch.',
      'Faire Verfahren sichern Anhörung, Begründung und Kontrolle. Ohne solche Regeln wird Recht anfällig für Vorurteile oder politische Willkür. Gerade deshalb gehört unabhängige Justiz zu den Grundpfeilern demokratischer Ordnung.',
      'Ohne faire Verfahren wird Recht anfällig für ___.',
      ['Willkür', 'Machtmissbrauch'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Rechtsstaat',
      'Ordnung mit gebundener Macht und geschützten Rechten',
      'Der Rechtsstaat lebt von Gesetzen, fairen Verfahren und unabhängigen Gerichten. Er ist das Gegenmodell zur politischen Justiz der Diktatur.',
    ),
    pair(
      'p2',
      'Sondergericht',
      'Politisches Gericht mit eingeschränkten Sicherungen im NS-Staat',
      'Sondergerichte zeigen, wie Regime Recht für schnelle Verfolgung nutzen können. Sie stehen für den Abbau rechtsstaatlicher Garantien.',
    ),
    pair(
      'p3',
      'Volksgerichtshof',
      'Zentrales NS-Gericht für politische Verfahren',
      'Der Volksgerichtshof symbolisiert nationalsozialistische Unrechtsjustiz. Er verband harte Strafen mit politischer Einschüchterung.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Der Vergleich von Weimarer Republik und NS-Staat zeigt, dass Justiz immer automatisch unabhängig und gerecht bleibt, egal unter welcher Herrschaft.',
      false,
      'Justiz kann geschützt, geschwächt oder politisch missbraucht werden.',
      'Gerichte handeln nie völlig losgelöst von politischen Rahmenbedingungen. Geschichte zeigt, dass der Rechtsstaat verteidigt werden muss und Justiz in Diktaturen missbraucht werden kann. Der Vergleich ist deshalb besonders lehrreich.',
    ),
  ],
}

const frauen: BioBank = {
  quelle: 'Wikipedia: Frauen in der Weimarer Republik',
  url: 'https://de.wikipedia.org/wiki/Frauen_in_der_Weimarer_Republik',
  conceptPrefix: 'ge:k9:frauen',
  facts: [
    fact(
      'wahlrecht',
      'Welche wichtige politische Neuerung brachte die Weimarer Republik für Frauen?',
      'Frauen erhielten das aktive und passive Wahlrecht',
      ['Frauen verloren das Recht auf Bildung', 'Frauen durften nur noch im Haushalt arbeiten', 'Frauen wurden aus allen Berufen ausgeschlossen'],
      'Mitbestimmung von Frauen wurde politisch anerkannt.',
      'Nach dem Ende des Kaiserreichs erhielten Frauen in Deutschland das Wahlrecht. Damit konnten sie wählen und gewählt werden. Diese Veränderung war ein großer Schritt politischer Gleichberechtigung in der Weimarer Republik.',
      'In der Weimarer Republik erhielten Frauen das ___.',
      ['Wahlrecht'],
    ),
    fact(
      'beruf',
      'Wie veränderte sich die gesellschaftliche Rolle vieler Frauen in der Weimarer Republik?',
      'Mehr Frauen traten sichtbar in Beruf, Politik und Öffentlichkeit auf',
      ['Frauen verschwanden völlig aus dem öffentlichen Leben', 'Nur adelige Frauen durften lesen', 'Frauen wurden grundsätzlich vom Schulbesuch ausgeschlossen'],
      'Weimar eröffnete neue Räume, aber keine vollständige Gleichheit.',
      'In der Weimarer Republik wurden Frauen in Büro, Kultur, Politik und Bildung sichtbarer. Dennoch blieben traditionelle Rollenbilder und Benachteiligungen bestehen. Fortschritt und Begrenzung standen also nebeneinander.',
      'In Weimar traten Frauen stärker in Beruf, Politik und ___.',
      ['Öffentlichkeit', 'Oeffentlichkeit'],
    ),
    fact(
      'ns-frauenbild',
      'Welches Frauenbild propagierte der Nationalsozialismus?',
      'Vor allem die Rolle der Frau als Mutter im Dienst von Familie und "Volksgemeinschaft"',
      ['Die völlige politische Gleichstellung in allen Bereichen', 'Die Förderung unabhängiger Frauenbewegungen', 'Die Abschaffung jeder Familienpolitik'],
      'Das Regime ordnete Frauen stark ideologischen Rollen zu.',
      'Der Nationalsozialismus propagierte ein traditionelles und ideologisch aufgeladenes Frauenbild. Frauen sollten vor allem Mutter sein und dem Regime demografisch dienen. Politische und berufliche Eigenständigkeit wurde dadurch eingeschränkt.',
      'Im NS-Frauenbild stand besonders die Rolle als ___ im Vordergrund.',
      ['Mutter'],
    ),
    fact(
      'ausschluss-politik',
      'Wie veränderte das NS-Regime die politische Stellung von Frauen?',
      'Es drängte Frauen aus vielen Bereichen politischer Mitbestimmung und unabhängiger Organisation',
      ['Es baute das Frauenwahlrecht zu direkter Herrschaft aus', 'Es schuf freie feministische Parteien', 'Es machte alle Frauen zu Richterinnen'],
      'Diktatur schränkte weibliche Selbstorganisation stark ein.',
      'Unabhängige Frauenverbände und politische Mitwirkung passten nicht zum NS-Staat. Frauen sollten sich im Sinne der Ideologie einordnen, nicht eigenständig politisch handeln. Dadurch wurden frühere Freiräume deutlich eingeschränkt.',
      'Das NS-Regime drängte Frauen aus unabhängiger politischer ___.',
      ['Mitwirkung', 'Organisation'],
    ),
    fact(
      'vergleich',
      'Was zeigt der Vergleich Weimar und NS bei der Lage von Frauen?',
      'Dass Fortschritte in Rechten und Öffentlichkeit wieder eingeschränkt werden konnten',
      ['Dass sich Frauenleben historisch nie verändert', 'Dass Diktatur automatisch mehr Gleichberechtigung bringt', 'Dass Politik auf Geschlechterrollen keinen Einfluss hat'],
      'Rechte sind historisch nicht selbstverständlich.',
      'Der Vergleich zeigt, dass erreichte Rechte und Sichtbarkeit nicht dauerhaft gesichert waren. In der Diktatur konnten politische und gesellschaftliche Freiräume wieder begrenzt werden. Geschichte von Frauen ist deshalb auch eine Geschichte von Kämpfen um Rechte.',
      'Der Vergleich zeigt, dass Rechte auch wieder ___ werden konnten.',
      ['eingeschränkt', 'zurückgenommen'],
    ),
    fact(
      'arbeit',
      'Warum blieb Erwerbsarbeit von Frauen auch im NS-Staat ein widersprüchliches Thema?',
      'Weil Ideologie traditionelle Rollen betonte, die Wirtschaft aber zugleich auf weibliche Arbeit angewiesen sein konnte',
      ['Weil Frauen grundsätzlich nie arbeiteten', 'Weil Ideologie und Wirtschaft immer identisch handeln', 'Weil nur Männer in Fabriken vorkamen'],
      'Politische Leitbilder und wirtschaftliche Realität konnten auseinanderfallen.',
      'Die NS-Ideologie stellte Frauen vor allem als Mütter dar. Gleichzeitig brauchte die Wirtschaft in manchen Bereichen Arbeitskräfte, besonders im Krieg. Das zeigt, dass Ideologie und gesellschaftliche Praxis nicht immer vollständig übereinstimmten.',
      'Im NS-Staat standen Ideologie und wirtschaftliche ___ teils im Widerspruch.',
      ['Realität', 'Praxis'],
    ),
    fact(
      'neue-frau',
      'Wofür steht das Bild der "Neuen Frau" in der Weimarer Republik?',
      'Für modernere Lebensstile, größere Sichtbarkeit und ein verändertes Selbstverständnis mancher Frauen',
      ['Für die Rückkehr zur Grundherrschaft', 'Für ein ausschließlich ländliches Frauenbild', 'Für die Abschaffung weiblicher Bildung'],
      'Das Bild stand für Modernisierung, aber nicht für alle Frauen gleichermaßen.',
      'Die "Neue Frau" war ein Symbol der 1920er Jahre und stand für moderne Kleidung, Berufstätigkeit und mehr Öffentlichkeit. Dieses Bild erfasste jedoch nicht alle sozialen Gruppen. Es zeigt eher einen Trend der städtischen Moderne als eine vollständige Realität.',
      'Die "Neue Frau" steht für modernere Lebensstile und mehr ___.',
      ['Sichtbarkeit', 'Öffentlichkeit'],
    ),
    fact(
      'bedeutung',
      'Warum ist das Thema Frauen in Weimar und NS mehr als eine Randfrage?',
      'Weil sich daran Demokratie, Diktatur und gesellschaftliche Rollen besonders deutlich vergleichen lassen',
      ['Weil Frauen nur im Familienleben vorkamen', 'Weil politische Systeme auf Geschlechterrollen keinen Einfluss haben', 'Weil historische Rechte immer gleich bleiben'],
      'Geschlechtergeschichte macht politische Unterschiede sichtbar.',
      'An der Lage von Frauen lässt sich gut erkennen, wie politische Systeme Gesellschaft formen. Demokratie konnte neue Rechte eröffnen, Diktatur sie wieder beschneiden. Das Thema zeigt also zentrale Unterschiede von Freiheit und Herrschaft.',
      'An der Lage von Frauen lassen sich Demokratie und ___ gut vergleichen.',
      ['Diktatur'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Frauenwahlrecht',
      'Politisches Mitbestimmungsrecht in der Weimarer Republik',
      'Mit dem Frauenwahlrecht wurde politische Gleichberechtigung erweitert. Es war ein wichtiger demokratischer Fortschritt.',
    ),
    pair(
      'p2',
      'Neue Frau',
      'Symbol moderner weiblicher Öffentlichkeit der 1920er Jahre',
      'Die "Neue Frau" steht für veränderte Lebensstile und neue Rollenbilder. Sie beschreibt aber nicht die gesamte Lebenswirklichkeit aller Frauen.',
    ),
    pair(
      'p3',
      'NS-Frauenbild',
      'Ideologisches Rollenbild von Mutter und "Volksgemeinschaft"',
      'Im NS-Staat wurden Frauen stark auf Familie und Geburtenpolitik bezogen. Dadurch wurden politische und berufliche Freiräume begrenzt.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Der Vergleich von Weimar und NS zeigt, dass Frauenrechte und weibliche Öffentlichkeit historisch ausgebaut, aber auch wieder eingeschränkt werden konnten.',
      true,
      'Genau dieser Wandel macht das Thema historisch besonders aufschlussreich.',
      'Weimar eröffnete neue politische und gesellschaftliche Räume für Frauen, die unter dem NS-Regime teilweise wieder eingegrenzt wurden. Rechte und Rollenbilder sind also historisch umkämpft und nicht selbstverständlich. Darin liegt die eigentliche Lernchance des Vergleichs.',
    ),
  ],
}

const kultur: BioBank = {
  quelle: 'Wikipedia: Neue Sachlichkeit',
  url: 'https://de.wikipedia.org/wiki/Neue_Sachlichkeit',
  conceptPrefix: 'ge:k9:kultur',
  facts: [
    fact(
      'weimar-kultur',
      'Was kennzeichnete Kultur in der Weimarer Republik oft?',
      'Vielfalt, Experimentierfreude und lebendige Debatten in Kunst, Film und Literatur',
      ['Nur staatlich erlaubte Einheitskunst', 'Ausschließlich mittelalterliche Kirchenkunst', 'Das völlige Ende aller Theater und Kinos'],
      'Weimar war kulturell offen und umkämpft zugleich.',
      'Die Weimarer Republik war kulturell sehr lebendig. Film, Theater, Architektur und Literatur entwickelten neue Formen und stritten über Moderne, Politik und Gesellschaft. Diese Vielfalt machte die Epoche bis heute besonders interessant.',
      'Die Kultur der Weimarer Republik war durch ___ und Experimentierfreude geprägt.',
      ['Vielfalt'],
    ),
    fact(
      'bauhaus',
      'Wofür steht das Bauhaus?',
      'Für moderne Gestaltung, funktionale Architektur und Verbindung von Kunst und Alltag',
      ['Für barocke Hofkunst Ludwigs XIV.', 'Für eine NS-Parteiakademie', 'Für antike Tempelarchitektur in Rom'],
      'Das Bauhaus wurde zu einem Symbol kultureller Moderne.',
      'Das Bauhaus suchte nach neuen Formen von Gestaltung und Architektur für die moderne Gesellschaft. Kunst, Handwerk und Technik sollten zusammenwirken. Gerade deshalb wurde es international zu einem Symbol der Moderne.',
      'Das Bauhaus steht für moderne Gestaltung und funktionale ___.',
      ['Architektur'],
    ),
    fact(
      'entartete-kunst',
      'Wie ging das NS-Regime mit moderner Kunst um, die nicht in sein Weltbild passte?',
      'Es diffamierte sie als "entartet", verbot sie und verfolgte Künstler',
      ['Es förderte jede Form künstlerischer Vielfalt', 'Es überließ Kunst vollständig privaten Museen', 'Es machte moderne Kunst zur Staatsdoktrin'],
      'Kultur wurde im NS-Staat ideologisch kontrolliert.',
      'Das NS-Regime griff massiv in Kunst und Kultur ein. Moderne und politisch unerwünschte Werke wurden als "entartet" diffamiert, aus Museen entfernt und Künstler verfolgt. So wurde kulturelle Vielfalt systematisch zerstört.',
      'Das NS-Regime diffamierte unerwünschte moderne Kunst als "___.',
      ['entartet'],
    ),
    fact(
      'propaganda-kunst',
      'Wozu nutzte der NS-Staat Kultur besonders?',
      'Zur Propaganda, Selbstdarstellung und Vermittlung seiner Ideologie',
      ['Nur zur freien Kritik an der Regierung', 'Nur zur Pflege antiker Bibliotheken', 'Ausschließlich für private Unterhaltung ohne Politik'],
      'Kultur diente im NS-Staat gezielt politischer Lenkung.',
      'Im Nationalsozialismus sollte Kultur nicht unabhängig sein, sondern die Ideologie des Regimes stützen. Kunst, Film und Feiern vermittelten politische Botschaften und Bilder von Gemeinschaft. Dadurch wurde Kultur zu einem Instrument der Herrschaft.',
      'Im NS-Staat diente Kultur besonders der ___.',
      ['Propaganda', 'Ideologie'],
    ),
    fact(
      'film',
      'Warum spielte der Film in beiden Systemen eine wichtige Rolle?',
      'Weil er viele Menschen erreichte und Kultur wie Politik sichtbar machen konnte',
      ['Weil Film nur für kleine Eliten zugänglich war', 'Weil Kinos im 20. Jahrhundert verboten waren', 'Weil Film keine Wirkung auf Meinungen hatte'],
      'Massenkultur prägt Wahrnehmung breiter Bevölkerung.',
      'Film war im 20. Jahrhundert ein starkes Massenmedium. In der Weimarer Republik zeigte er kulturelle Vielfalt und neue Ausdrucksformen, im NS-Staat diente er oft auch der Propaganda. Der Vergleich macht den politischen Gebrauch von Kultur sichtbar.',
      'Film war wichtig, weil er viele Menschen ___ konnte.',
      ['erreichen'],
    ),
    fact(
      'vergleich',
      'Was zeigt der Vergleich von Weimarer Republik und NS-Staat im Bereich Kultur?',
      'Offenheit und Vielfalt können durch ideologische Kontrolle ersetzt werden',
      ['Kultur bleibt immer unabhängig von Politik', 'Diktaturen fördern automatisch mehr Vielfalt', 'Demokratien verbieten grundsätzlich moderne Kunst'],
      'Kultur spiegelt politische Freiheit oder Unfreiheit deutlich wider.',
      'In der Weimarer Republik bestand große kulturelle Offenheit mit vielen Stilen und Debatten. Im NS-Staat wurde Kultur politisch kontrolliert, gelenkt und gesäubert. Gerade dieser Gegensatz macht Kultur zu einem wichtigen Vergleichsfeld.',
      'Der Vergleich zeigt den Gegensatz von Vielfalt und ideologischer ___.',
      ['Kontrolle'],
    ),
    fact(
      'exil',
      'Warum gingen viele Künstler im Nationalsozialismus ins Exil?',
      'Weil Verfolgung, Zensur und Berufsverbote freies Arbeiten unmöglich machten',
      ['Weil das Regime alle Künstler ins Ausland schicken wollte', 'Weil Kultur im Exil weniger gefährlich wirkte', 'Weil Weimar keine Bühnen kannte'],
      'Diktatur zerstört kulturelle Freiheit und Lebenswege.',
      'Viele Künstler, Schriftsteller und Intellektuelle konnten unter dem NS-Regime nicht frei leben oder arbeiten. Ausgrenzung, Zensur und Verfolgung zwangen sie ins Exil. Damit verlor Deutschland einen wichtigen Teil seiner kulturellen Vielfalt.',
      'Viele Künstler gingen wegen Verfolgung und ___ ins Exil.',
      ['Zensur', 'Berufsverboten'],
    ),
    fact(
      'bedeutung',
      'Warum ist Kulturgeschichte für den Vergleich von Demokratie und Diktatur wichtig?',
      'Weil sich an Kunst und Medien Freiheit, Vielfalt und Kontrolle besonders gut zeigen lassen',
      ['Weil Kultur nur Privatangelegenheit ohne politische Aussage ist', 'Weil Diktaturen keine Medien nutzen', 'Weil Kunst immer gleich funktioniert'],
      'Kultur macht politische Systeme im Alltag sichtbar.',
      'An Kunst, Film, Architektur und Literatur lässt sich erkennen, wie offen oder kontrolliert eine Gesellschaft ist. Demokratie lässt mehr Vielfalt zu, Diktatur lenkt und begrenzt sie stärker. Kulturgeschichte hilft daher, politische Systeme anschaulich zu verstehen.',
      'An Kultur lassen sich Freiheit, Vielfalt und politische ___ erkennen.',
      ['Kontrolle'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Bauhaus',
      'Symbol moderner Gestaltung in der Weimarer Republik',
      'Das Bauhaus verband Kunst, Technik und Alltag. Es steht bis heute für kulturelle Moderne.',
    ),
    pair(
      'p2',
      'entartete Kunst',
      'NS-Schmähbegriff für unerwünschte moderne Kunst',
      'Mit diesem Begriff diffamierte das Regime künstlerische Vielfalt. Dahinter stand ideologische Kontrolle von Kultur.',
    ),
    pair(
      'p3',
      'Exil',
      'Flucht vieler Künstler vor Verfolgung und Zensur',
      'Exil zeigt, wie stark Diktaturen kulturelle Freiheit zerstören können. Zugleich entstand im Ausland neue deutschsprachige Kultur.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Der Kulturvergleich zwischen Weimar und NS zeigt, dass Politik kaum Einfluss auf Kunst und Medien hatte.',
      false,
      'Gerade der Unterschied zwischen Offenheit und ideologischer Lenkung ist hier zentral.',
      'Kultur war weder in der Weimarer Republik noch im NS-Staat unpolitisch. Sie konnte Raum für Vielfalt eröffnen oder zum Instrument der Herrschaft werden. Genau deshalb eignet sich der Vergleich kultureller Entwicklungen besonders gut.',
    ),
  ],
}

export const GESCHICHTE_K9_GENERATORS: Record<string, Topic['generate']> = {
  'ge-k9-lb1-nach-wk1': bankGenerate(nachWk1),
  'ge-k9-lb2-demokratie-diktatur': bankGenerate(demokratieDiktatur),
  'ge-k9-lb3-ns-diktatur': bankGenerate(nsDiktatur),
  'ge-k9-lb4-aussenpolitik': bankGenerate(aussenpolitik),
  'ge-k9-lbw-justiz': bankGenerate(justiz),
  'ge-k9-lbw-frauen': bankGenerate(frauen),
  'ge-k9-lbw-kultur': bankGenerate(kultur),
}
