import { bankGenerate, type BioBank } from './biologieBank'
import type { Topic } from './types'

const fact = (
  concept: string,
  prompt: string,
  answer: string,
  wrong: [string, string, string],
  explanation: string,
  wissen: string,
  gap: string,
  gapAccepted: string[],
) => ({ concept, prompt, answer, wrong, explanation, wissen, gap, gapAccepted })

const pair = (concept: string, term: string, meaning: string, wissen: string) => ({
  concept,
  term,
  meaning,
  wissen,
})

const tf = (
  concept: string,
  statement: string,
  correct: boolean,
  explanation: string,
  wissen: string,
) => ({ concept, statement, correct, explanation, wissen })

const sort = (
  concept: string,
  question: string,
  labels: string[],
  explanation: string,
  wissen: string,
) => ({ concept, question, labels, explanation, wissen })

const mittelalter: BioBank = {
  quelle: 'Wikipedia: Mittelalter',
  url: 'https://de.wikipedia.org/wiki/Mittelalter',
  conceptPrefix: 'ge:k6:mittelalter',
  facts: [
    fact(
      'lehnswesen',
      'Was war ein Lehen im Mittelalter?',
      'Ein Gut oder Recht, das ein Herr seinem Vasallen gegen Dienste überließ',
      ['Eine städtische Steuer nur für Handwerker', 'Ein Klosterschwur ohne Besitz', 'Ein Bürgerrecht der antiken Polis'],
      'Lehen verbanden Herr und Vasall in einem persönlichen Treueverhältnis.',
      'Im Lehnswesen vergab ein Lehnsherr Land, Einkünfte oder Rechte an einen Vasallen. Dafür schuldete der Vasall vor allem Treue und meist militärische Dienste. So wurde Herrschaft im Mittelalter persönlich gebunden und nicht nur über Ämter organisiert.',
      'Ein ___ war ein Gut oder Recht, das gegen Treue und Dienste vergeben wurde.',
      ['Lehen'],
    ),
    fact(
      'vasall',
      'Welche Hauptpflicht hatte ein Vasall gegenüber seinem Lehnsherrn?',
      'Treue und Dienst, besonders Heeresfolge und Beratung',
      ['Nur Handel mit Fernwaren', 'Ausschließlich geistliche Predigt', 'Steuerfreiheit ohne Gegenleistung'],
      'Vasallen unterstützten ihren Herrn politisch und militärisch.',
      'Ein Vasall war an seinen Lehnsherrn durch einen Treueeid gebunden. Er musste den Herrn beraten und im Kriegsfall oft Heeresdienst leisten. Das Verhältnis beruhte auf gegenseitigen Pflichten und persönlicher Bindung.',
      'Ein Vasall schuldete seinem Herrn vor allem ___ und Dienst.',
      ['Treue'],
    ),
    fact(
      'grundherrschaft',
      'Was bedeutet Grundherrschaft?',
      'Herrschaft eines Grundherrn über Land und die darauf lebenden abhängigen Bauern',
      ['Gleichberechtigte Selbstverwaltung aller Städter', 'Nur die Herrschaft eines Bischofs über Klöster', 'Eine antike Volksversammlung in Athen'],
      'Grundherrschaft prägte das ländliche Leben vieler Menschen.',
      'Grundherrschaft bezeichnet die wirtschaftliche und rechtliche Macht eines Herrn über Land und Bauern. Viele Bauern mussten Abgaben leisten und Frondienste verrichten. Dadurch war das Leben auf dem Land stark von Abhängigkeit und festen Pflichten geprägt.',
      '___ bezeichnet die Herrschaft eines Grundherrn über Land und Bauern.',
      ['Grundherrschaft'],
    ),
    fact(
      'ritter',
      'Wie wurde man im Mittelalter meist Ritter?',
      'Durch adlige Herkunft, Ausbildung als Page und Knappe sowie den Ritterschlag',
      ['Durch Wahl in der Volksversammlung', 'Durch ein Universitätsstudium in Rom', 'Durch Kauf eines Zunftbriefs'],
      'Rittertum war an Stand, Ausbildung und militärische Aufgabe gebunden.',
      'Ritter waren meist adlige Krieger zu Pferde. Jungen aus adligen Familien wurden als Page und später als Knappe erzogen, bevor sie den Ritterschlag erhielten. Rittertum verband Kampf, Standesbewusstsein und höfische Lebensformen.',
      'Vor dem Ritterschlag war ein junger Adliger oft ___ und danach Knappe.',
      ['Page'],
    ),
    fact(
      'stadt',
      'Warum wurden mittelalterliche Städte für viele Menschen attraktiv?',
      'Weil Handel, Handwerk und persönliche Freiheit dort oft größer waren als auf dem Land',
      ['Weil dort keine Abgaben und Regeln galten', 'Weil nur Ritter in Städten leben durften', 'Weil Städte keinen Markt und keine Mauern hatten'],
      'Städte boten wirtschaftliche Chancen und rechtliche Vorteile.',
      'Mittelalterliche Städte waren Zentren von Handel und Handwerk. Viele Bewohner hatten dort mehr persönliche Freiheiten als abhängige Bauern auf dem Land. Die bekannte Formel "Stadtluft macht frei" verweist auf diese Unterschiede, auch wenn nicht jeder automatisch frei wurde.',
      'Mittelalterliche Städte boten mehr Chancen für ___ und Handwerk.',
      ['Handel'],
    ),
    fact(
      'zunft',
      'Welche Aufgabe hatte eine Zunft?',
      'Sie regelte Ausbildung, Qualität und Interessen eines Handwerks in der Stadt',
      ['Sie führte das Ritterheer des Königs', 'Sie war die Bezeichnung für einen Bauernhof', 'Sie ersetzte jede Kirche in der Stadt'],
      'Zünfte ordneten das Handwerk und schützten wirtschaftliche Interessen.',
      'Zünfte waren Zusammenschlüsse von Handwerkern eines Berufs in der Stadt. Sie regelten Lehre, Meisterprüfung und Qualitätsstandards. Außerdem vertraten sie wirtschaftliche Interessen gegenüber der Stadtregierung.',
      'Eine ___ regelte Ausbildung und Qualität eines Handwerks.',
      ['Zunft'],
    ),
    fact(
      'karl',
      'Warum gilt Karl der Große als wichtige Herrscherfigur des frühen Mittelalters?',
      'Weil er ein großes Reich beherrschte und 800 zum Kaiser gekrönt wurde',
      ['Weil er die Magna Carta erließ', 'Weil er den Buchdruck erfand', 'Weil er als Sultan in Jerusalem herrschte'],
      'Karl verband fränkische Macht mit dem Kaisertum.',
      'Karl der Große regierte das Frankenreich und dehnte seine Herrschaft stark aus. Im Jahr 800 wurde er in Rom zum Kaiser gekrönt. Seine Herrschaft prägte Vorstellungen von christlichem Königtum und europäischer Ordnung im frühen Mittelalter.',
      'Karl der Große wurde im Jahr 800 zum ___ gekrönt.',
      ['Kaiser'],
    ),
    fact(
      'staende',
      'Wie wurden die mittelalterlichen Stände häufig beschrieben?',
      'Als Betende, Kämpfende und Arbeitende mit unterschiedlichen Aufgaben',
      ['Als nur freie Bürger ohne Unterschiede', 'Als Parteien eines modernen Parlaments', 'Als Kolonien eines Weltreichs'],
      'Die Ständegesellschaft ordnete Menschen ungleich ein.',
      'Die mittelalterliche Gesellschaft wurde oft in Geistliche, Adel und Bauern gegliedert. Diese Ordnung erklärte man religiös und als gottgewollt. Tatsächlich lebten Menschen sehr unterschiedlich, doch die Ständevorstellung prägte das Denken lange Zeit.',
      'Die mittelalterliche Gesellschaft wurde oft in verschiedene ___ gegliedert.',
      ['Stände'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Lehnswesen',
      'Persönliches Treueverhältnis zwischen Herr und Vasall',
      'Lehnswesen band Herrschaft an Treueeid, Lehen und Dienst. Es ersetzte keine moderne Staatsverwaltung, sondern ordnete Macht über persönliche Bindungen.',
    ),
    pair(
      'p2',
      'Grundherrschaft',
      'Ländliche Herrschaft über Land und abhängige Bauern',
      'Grundherrschaft prägte den Alltag vieler Bauern. Abgaben und Frondienste machten die Abhängigkeit vom Grundherrn sichtbar.',
    ),
    pair(
      'p3',
      'Zunft',
      'Zusammenschluss von Handwerkern eines Berufs',
      'Zünfte regelten Ausbildung, Preise und Qualität. In vielen Städten bestimmten sie auch das soziale Leben von Handwerkern mit.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Im Mittelalter hatten Bauern in der Regel dieselben Freiheiten und Rechte wie adlige Herren.',
      false,
      'Die Ständegesellschaft war deutlich ungleich; viele Bauern waren abhängig.',
      'Die mittelalterliche Gesellschaft war ständisch gegliedert und ungleich. Adlige und Geistliche verfügten über mehr Rechte und Macht als abhängige Bauern. Gerade Grundherrschaft zeigt diese Unterschiede deutlich.',
    ),
  ],
  sorts: [
    sort(
      's1',
      'Ordne vom eher ländlichen Herrschaftsmodell zur eher städtischen Ordnung:',
      ['Grundherrschaft', 'Lehnswesen', 'Stadt mit Zünften'],
      'Erst prägt ländliche Abhängigkeit das Bild, dann personale Herrschaftsbindungen, schließlich städtisches Handwerk und Handel.',
      'Auf dem Land dominierten Grundherrschaft und Abhängigkeit. Lehnswesen ordnete Herrschaft zwischen Herren und Vasallen. Städte mit Märkten und Zünften entwickelten daneben eigene wirtschaftliche und rechtliche Formen.',
    ),
  ],
}

const religionen: BioBank = {
  quelle: 'Wikipedia: Abrahamitische Religionen',
  url: 'https://de.wikipedia.org/wiki/Abrahamitische_Religionen',
  conceptPrefix: 'ge:k6:religionen',
  facts: [
    fact(
      'christentum',
      'Wer steht im Mittelpunkt des Christentums?',
      'Jesus Christus',
      ['Mose als letzter Kalif', 'Karl der Große als Prophet', 'Aristoteles als Kirchenvater'],
      'Christen beziehen Glauben und Lehre auf Jesus Christus.',
      'Das Christentum ist eine monotheistische Religion und bezieht sich auf Jesus Christus. Im Mittelalter prägte es Politik, Alltag und Feste in Europa stark. Die Kirche war religiöse Autorität und zugleich ein wichtiger Machtfaktor.',
      'Im Mittelpunkt des Christentums steht ___ Christus.',
      ['Jesus'],
    ),
    fact(
      'islam',
      'Welche heilige Schrift gehört zum Islam?',
      'Der Koran',
      ['Die Tora', 'Die Goldene Bulle', 'Die Magna Carta'],
      'Der Koran ist die zentrale Schrift des Islam.',
      'Der Islam entstand im 7. Jahrhundert auf der Arabischen Halbinsel. Seine heilige Schrift ist der Koran, und Muslime verstehen ihn als Offenbarung Gottes. Im Mittelalter bildeten islamische Reiche bedeutende Zentren von Wissenschaft, Handel und Kultur.',
      'Die heilige Schrift des Islam ist der ___.',
      ['Koran'],
    ),
    fact(
      'judentum',
      'Welche gemeinsame Wurzel hat das Judentum mit Christentum und Islam?',
      'Den Glauben an den einen Gott',
      ['Den Glauben an viele Stadtgötter', 'Die Verehrung des Kaisers von Rom', 'Nur die Pflicht zum Ritterdienst'],
      'Alle drei Religionen sind monotheistisch.',
      'Judentum, Christentum und Islam gehören zu den monotheistischen Religionen. Sie glauben an einen einzigen Gott und beziehen sich auf Abraham. Im Mittelalter lebten ihre Anhänger teils zusammen, teils in scharfer Abgrenzung und unter Konflikten.',
      'Judentum, Christentum und Islam glauben an ___ Gott.',
      ['einen', 'einen Gott'],
    ),
    fact(
      'jerusalem',
      'Warum war Jerusalem für drei Religionen bedeutend?',
      'Weil die Stadt für Judentum, Christentum und Islam heilige Orte besitzt',
      ['Weil dort Karl der Große geboren wurde', 'Weil nur Ritter dort handeln durften', 'Weil die Stadt im Mittelalter keine religiöse Rolle hatte'],
      'Jerusalem ist ein heiliger Ort mehrerer Religionen.',
      'Jerusalem ist für Juden, Christen und Muslime eine heilige Stadt. Gerade weil mehrere Religionen wichtige Orte mit Jerusalem verbinden, wurde die Stadt immer wieder zum Ziel religiöser Verehrung und politischer Konflikte. Das machte sie im Mittelalter besonders umkämpft.',
      'Jerusalem war heilig für ___ Religionen.',
      ['drei'],
    ),
    fact(
      'kreuzzuege',
      'Was waren die Kreuzzüge?',
      'Kriegszüge christlicher Herrscher und Ritter vor allem in den östlichen Mittelmeerraum',
      ['Nur friedliche Handelsreisen italienischer Kaufleute', 'Eine Reformbewegung innerhalb des Judentums', 'Ausschließlich Kämpfe zwischen deutschen Städten'],
      'Kreuzzüge verbanden Religion, Macht und Gewalt.',
      'Die Kreuzzüge begannen Ende des 11. Jahrhunderts. Christliche Herrscher und Ritter zogen unter religiösen Vorzeichen in den östlichen Mittelmeerraum, besonders nach Jerusalem. Dabei spielten Frömmigkeit, Machtinteressen und Gewalt eng zusammen.',
      'Die ___ waren Kriegszüge mit religiöser Begründung.',
      ['Kreuzzüge'],
    ),
    fact(
      'zusammenleben',
      'War das Zusammenleben von Christen, Juden und Muslimen im Mittelalter nur friedlich oder nur feindlich?',
      'Weder noch; es gab Austausch, aber auch Ausgrenzung und Gewalt',
      ['Nur vollkommenen Frieden überall', 'Nur dauernden Krieg ohne Handel', 'Überhaupt keinen Kontakt zwischen den Gruppen'],
      'Mittelalterliches Zusammenleben war widersprüchlich.',
      'Im Mittelalter gab es zwischen Christen, Juden und Muslimen sowohl Handel und Wissensaustausch als auch Vorurteile, Diskriminierung und Gewalt. Das Zusammenleben war regional sehr unterschiedlich. Einfache Schwarz-Weiß-Bilder werden der Geschichte deshalb nicht gerecht.',
      'Zwischen den Religionen gab es Austausch, aber auch ___ und Gewalt.',
      ['Ausgrenzung', 'Diskriminierung'],
    ),
    fact(
      'wissenschaft',
      'Warum waren islamische Zentren wie Bagdad oder Córdoba für Europa bedeutsam?',
      'Dort wurden Wissen gesammelt, weiterentwickelt und Texte überliefert',
      ['Dort wurde der Feudalismus erstmals abgeschafft', 'Dort entstand die Goldene Bulle', 'Dort wurde Rom gegründet'],
      'Wissenschaftlicher Austausch verlief über kulturelle Grenzen hinweg.',
      'In islamischen Zentren wurden antike Schriften gesammelt, übersetzt und weiterentwickelt. Mathematik, Medizin und Astronomie profitierten davon besonders. Über Kontakte im Mittelmeerraum gelangten viele Kenntnisse auch nach Europa.',
      'Islamische Zentren bewahrten und erweiterten antikes ___.',
      ['Wissen'],
    ),
    fact(
      'juden-europa',
      'Welche Erfahrung machten viele jüdische Gemeinden im mittelalterlichen Europa?',
      'Sie erlebten Schutzphasen, aber auch Ausgrenzung, Sondersteuern und Pogrome',
      ['Sie herrschten meist als Könige über Europa', 'Sie lebten überall völlig gleichberechtigt', 'Sie bildeten die Mehrheit aller Ritterorden'],
      'Die Lage jüdischer Gemeinden war oft unsicher.',
      'Jüdische Gemeinden gehörten vielerorts dauerhaft zum mittelalterlichen Europa. Gleichzeitig waren sie immer wieder Vorurteilen, rechtlichen Einschränkungen und Gewalt ausgesetzt. Pogrome zeigen, wie gefährlich religiöse Feindbilder werden konnten.',
      'Viele jüdische Gemeinden erlebten neben Schutz auch ___ und Pogrome.',
      ['Ausgrenzung', 'Verfolgung'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Koran',
      'Heilige Schrift des Islam',
      'Der Koran ist die heilige Schrift des Islam. Er spielte im religiösen Leben und in der Bildung islamischer Gesellschaften eine zentrale Rolle.',
    ),
    pair(
      'p2',
      'Jerusalem',
      'Heilige Stadt für Judentum, Christentum und Islam',
      'Jerusalem besitzt heilige Orte für drei Religionen. Gerade diese Mehrfachbedeutung erklärt seine besondere historische Konfliktlage.',
    ),
    pair(
      'p3',
      'Kreuzzüge',
      'Religiös begründete Kriegszüge in den Mittelmeerraum',
      'Die Kreuzzüge verbanden Frömmigkeit, politische Interessen und militärische Gewalt. Sie veränderten das Verhältnis der Religionen nachhaltig.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Im Mittelalter gab es zwischen Christen, Juden und Muslimen keinerlei Austausch von Handel oder Wissen.',
      false,
      'Es gab Austausch, auch wenn zugleich Konflikte und Ausgrenzung vorkamen.',
      'Zwischen den Religionen bestand nicht nur Feindschaft. Handel, Übersetzungen und Begegnungen sorgten vielerorts für Austausch. Daneben gab es aber ebenso Diskriminierung, Gewalt und politische Gegensätze.',
    ),
  ],
}

const buerger: BioBank = {
  quelle: 'Wikipedia: Bürger',
  url: 'https://de.wikipedia.org/wiki/B%C3%BCrger',
  conceptPrefix: 'ge:k6:buerger',
  facts: [
    fact(
      'polis',
      'Was bedeutete Bürgersein in einer griechischen Polis?',
      'Politische Zugehörigkeit zu einem Stadtstaat mit Rechten und Pflichten',
      ['Nur Besitz einer Ritterrüstung', 'Abhängigkeit als Höriger eines Grundherrn', 'Mitgliedschaft in einer Klosterregel'],
      'In der Polis war Bürgersein eng mit Politik verbunden.',
      'In griechischen Poleis war der Bürger Teil des Stadtstaats und konnte politische Rechte besitzen. Bürgersein bedeutete aber nicht Gleichheit für alle, denn Frauen, Sklaven und Fremde waren oft ausgeschlossen. Rechte und Zugehörigkeit hingen also stark vom Status ab.',
      'In der Polis bedeutete Bürgersein politische ___ zu einem Stadtstaat.',
      ['Zugehörigkeit'],
    ),
    fact(
      'rom',
      'Was war das römische Bürgerrecht?',
      'Ein Rechtsstatus mit Schutz, Rechten und Pflichten innerhalb des römischen Gemeinwesens',
      ['Ein rein religiöses Gelübde ohne Rechtsfolgen', 'Nur ein Titel für Kaiserfamilien', 'Eine Zunftzugehörigkeit im Mittelalter'],
      'Im römischen Reich hatte Bürgerrecht konkrete rechtliche Folgen.',
      'Das römische Bürgerrecht verlieh Schutz und bestimmte Rechte, etwa im Rechtsverkehr oder in politischen Zusammenhängen. Es konnte ausgeweitet werden und band viele Menschen an Rom. Bürgersein war hier stärker rechtlich gefasst als in vielen anderen Epochen.',
      'Das römische Bürgerrecht war ein ___ mit Rechten und Pflichten.',
      ['Rechtsstatus'],
    ),
    fact(
      'stadtmittelalter',
      'Wodurch zeichnete sich ein Bürger in der mittelalterlichen Stadt besonders aus?',
      'Durch Zugehörigkeit zur Stadt mit Rechten, Besitz oder Beruf und oft persönlicher Freiheit',
      ['Durch Lehnseid an einen Vasallen', 'Durch Mitgliedschaft im römischen Senat', 'Durch alleinige Herrschaft über ein Dorf'],
      'Mittelalterliches Bürgersein war an die Stadt gebunden.',
      'Ein Bürger der mittelalterlichen Stadt unterschied sich vom abhängigen Bauern auf dem Land. Bürgerrechte konnten Handel, Eigentum, Schutz und Mitwirkung in der Stadt betreffen. Damit entstand eine eigene städtische Lebensform zwischen Adel und bäuerlicher Welt.',
      'Mittelalterliches Bürgersein war eng an die ___ gebunden.',
      ['Stadt'],
    ),
    fact(
      'vergleich',
      'Was zeigt der Längsschnitt zu Bürgern in Polis, Rom und Mittelalter besonders?',
      'Dass Bürgerrechte sich verändern und von Zeit und Gesellschaft abhängen',
      ['Dass Bürger überall immer genau dieselben Rechte hatten', 'Dass Bürgersein nur im Mittelalter existierte', 'Dass Rechte nie etwas mit Herrschaft zu tun hatten'],
      'Ein Längsschnitt vergleicht Wandel über längere Zeiträume.',
      'Im Vergleich von Polis, Rom und mittelalterlicher Stadt wird deutlich, dass Bürgersein historisch wandelbar ist. Rechte, Pflichten und Ausschlüsse änderten sich je nach Epoche. Geschichte fragt deshalb nicht nur nach Begriffen, sondern auch nach Veränderungen.',
      'Der Vergleich zeigt den historischen ___ von Bürgerrechten.',
      ['Wandel'],
    ),
    fact(
      'pflichten',
      'Warum gehören zu Bürgerrechten fast immer auch Bürgerpflichten?',
      'Weil Zugehörigkeit zu einem Gemeinwesen Mitverantwortung und Leistungen verlangt',
      ['Weil Rechte ohne jede Ordnung funktionieren', 'Weil Pflichten nur Sklaven betreffen', 'Weil Bürger nie Steuern oder Dienste leisten mussten'],
      'Rechte und Pflichten gehören historisch zusammen.',
      'Bürgerrechte bedeuteten selten nur Vorteile. Oft waren damit Wehrdienst, Steuern, politische Teilnahme oder kommunale Aufgaben verbunden. Ein Gemeinwesen erwartete also nicht nur Schutz, sondern auch Beiträge seiner Bürger.',
      'Zu Bürgerrechten gehören oft auch Bürger___.',
      ['pflichten', 'Pflichten'],
    ),
    fact(
      'ausschluss',
      'Was hatten Polis, Rom und mittelalterliche Städte gemeinsam?',
      'Nicht alle Bewohner waren automatisch vollberechtigte Bürger',
      ['Alle Einwohner waren stets gleichgestellt', 'Es gab überall allgemeines Wahlrecht für Kinder', 'Sklaven und Fremde hatten immer dieselben Rechte wie Bürger'],
      'Bürgersein schloss in allen drei Fällen andere Gruppen aus.',
      'In allen drei historischen Modellen blieb Bürgersein begrenzt. Frauen, Sklaven, Fremde oder ärmere Gruppen waren oft ausgeschlossen oder nur teilweise beteiligt. Gerade dieser Ausschluss zeigt, dass Bürgerrechte immer auch Grenzen hatten.',
      'Nicht alle Bewohner waren automatisch vollberechtigte ___.',
      ['Bürger'],
    ),
    fact(
      'mitwirkung',
      'Welche Rolle spielte politische Mitwirkung beim Bürgerbegriff?',
      'Sie war oft wichtig, aber je nach Epoche sehr unterschiedlich ausgeprägt',
      ['Sie spielte historisch nie eine Rolle', 'Sie war nur im Kloster möglich', 'Sie bestand überall nur aus Ritterturnieren'],
      'Mitwirkung konnte direkt, indirekt oder sehr begrenzt sein.',
      'Politische Mitwirkung war in Athen anders organisiert als in Rom oder in mittelalterlichen Städten. Mal stand die Volksversammlung im Vordergrund, mal rechtlicher Status oder kommunale Selbstverwaltung. Bürgersein hatte also kein einziges festes Muster.',
      'Politische Mitwirkung war historisch je nach ___ verschieden.',
      ['Epoche', 'Zeit'],
    ),
    fact(
      'stadtluft',
      'Warum passt die Formel "Stadtluft macht frei" zum Thema Bürger?',
      'Weil städtisches Leben im Mittelalter oft mehr persönliche Freiheit bot als ländliche Abhängigkeit',
      ['Weil jeder Städter automatisch König wurde', 'Weil Städte keine Gesetze kannten', 'Weil dort nur Geistliche wohnen durften'],
      'Die Formel verweist auf Unterschiede zwischen Land und Stadt.',
      'Die Formel "Stadtluft macht frei" beschreibt, dass Städte im Mittelalter häufig mehr Freiheiten boten als die Grundherrschaft auf dem Land. Vollständige Gleichheit bedeutete das nicht. Dennoch zeigt sie, wie eng Bürgersein mit urbanem Leben verbunden war.',
      '"Stadtluft macht frei" verweist auf mehr Freiheit in der ___.',
      ['Stadt'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Polisbürger',
      'Mitglied eines griechischen Stadtstaats',
      'In der Polis war Bürgersein eng mit politischer Zugehörigkeit verbunden. Zugleich blieben viele Bewohner ausgeschlossen.',
    ),
    pair(
      'p2',
      'römisches Bürgerrecht',
      'Rechtsstatus im römischen Gemeinwesen',
      'Römisches Bürgerrecht verlieh konkrete Rechte und Pflichten. Es konnte auf weitere Bevölkerungsgruppen ausgedehnt werden.',
    ),
    pair(
      'p3',
      'Stadtbürger',
      'Bewohner mit Rechten in einer mittelalterlichen Stadt',
      'Mittelalterliche Stadtbürger hatten häufig Handels- und Mitwirkungsrechte. Ihre Stellung unterschied sich von der abhängiger Bauern.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Der Längsschnitt zu Bürgern zeigt, dass Bürgerrechte in allen Epochen unverändert blieben.',
      false,
      'Gerade der Vergleich macht sichtbar, dass sich Rechte, Pflichten und Ausschlüsse wandelten.',
      'Ein Längsschnitt verfolgt Entwicklungen über längere Zeiträume. Beim Bürgerbegriff werden Unterschiede zwischen griechischer Polis, römischem Bürgerrecht und mittelalterlicher Stadt deutlich. Wandel ist hier also der eigentliche Erkenntnisgewinn.',
    ),
  ],
}

const besiedlung: BioBank = {
  quelle: 'Wikipedia: Ostsiedlung',
  url: 'https://de.wikipedia.org/wiki/Ostsiedlung',
  conceptPrefix: 'ge:k6:besiedlung',
  facts: [
    fact(
      'slawen',
      'Wer lebte im frühen Mittelalter in großen Teilen des heutigen Sachsen?',
      'Slawische Gruppen, darunter die Vorfahren der Sorben',
      ['Nur römische Legionäre', 'Ausschließlich Wikinger aus Island', 'Nur französische Ritterorden'],
      'Vor der deutschen Ostsiedlung war der Raum bereits besiedelt.',
      'Im Gebiet des heutigen Sachsen lebten im frühen Mittelalter slawische Gruppen. Zu ihnen gehören die Vorfahren der Sorben, deren Sprache und Kultur bis heute in der Lausitz fortleben. Die Region war also nicht unbewohnt, sondern bereits kulturell geprägt.',
      'Im frühen Mittelalter lebten in Sachsen slawische Gruppen, darunter die Vorfahren der ___.',
      ['Sorben', 'Sorbenen'],
    ),
    fact(
      'sorben',
      'Wer sind die Sorben?',
      'Eine westslawische Minderheit mit eigener Sprache und Kultur in der Lausitz',
      ['Ein mittelalterlicher Ritterorden', 'Die Bezeichnung für fränkische Könige', 'Eine römische Bürgergruppe'],
      'Die Sorben sind bis heute Teil der Geschichte Sachsens.',
      'Die Sorben sind eine westslawische Minderheit in der Lausitz. Sie besitzen eine eigene Sprache und kulturelle Traditionen, die bis in das frühe Mittelalter zurückreichen. Dadurch ist slawische Geschichte bis heute sichtbar mit Sachsen verbunden.',
      'Die Sorben sind eine westslawische ___ in der Lausitz.',
      ['Minderheit'],
    ),
    fact(
      'ostsiedlung',
      'Was meint die deutsche Ostsiedlung?',
      'Die Ausweitung von Siedlungen, Herrschaft und Landwirtschaft ostwärts im Mittelalter',
      ['Den Rückzug aller Menschen aus Sachsen', 'Nur eine einzelne Kreuzfahrt nach Jerusalem', 'Die Gründung Roms am Tiber'],
      'Ostsiedlung veränderte Bevölkerung und Landschaft.',
      'Unter deutscher Ostsiedlung versteht man die mittelalterliche Ausweitung von Siedlungen und Herrschaft nach Osten. Bauern, Handwerker und Adlige gründeten Dörfer und Städte oder bauten bestehende Strukturen um. Das führte zu tiefen Veränderungen, aber nicht zu einer völlig leeren Neubesiedlung.',
      'Die deutsche ___ beschreibt die mittelalterliche Ausweitung nach Osten.',
      ['Ostsiedlung'],
    ),
    fact(
      'waldhufe',
      'Was kennzeichnete viele neue Dörfer der Ostsiedlung?',
      'Planmäßige Anlage mit langgestreckten Flurstücken wie bei Waldhufendörfern',
      ['Nur Rundburgen aus der Römerzeit', 'Ausschließlich schwimmende Häuser', 'Dörfer ohne Felder und Wege'],
      'Siedlungsformen zeigen bewusste Planung.',
      'Viele Dörfer der Ostsiedlung wurden planmäßig angelegt. Waldhufendörfer mit langgestreckten Ackerstreifen sind dafür ein bekanntes Beispiel. Solche Formen machen historische Besiedlung bis heute in der Landschaft erkennbar.',
      'Typisch für manche Ostsiedlungsdörfer waren langgestreckte ___.',
      ['Flurstücke', 'Hufen'],
    ),
    fact(
      'kloster',
      'Welche Rolle spielten Klöster bei der Besiedlung?',
      'Sie förderten Rodung, Landwirtschaft, Mission und Verwaltung',
      ['Sie verhinderten grundsätzlich jeden Ackerbau', 'Sie waren nur Burgen für Ritterturniere', 'Sie wurden erst im Industriezeitalter gegründet'],
      'Klöster wirkten wirtschaftlich, religiös und organisatorisch.',
      'Klöster waren im Mittelalter wichtige Zentren von Religion, Bildung und Wirtschaft. Bei der Besiedlung förderten sie Rodung, Landwirtschaft und oft auch Herrschaftsorganisation. Damit prägten sie die Erschließung des Landes entscheidend mit.',
      'Klöster förderten bei der Besiedlung unter anderem Rodung und ___.',
      ['Landwirtschaft'],
    ),
    fact(
      'ortsnamen',
      'Was können Ortsnamen wie auf -itz oder -ow über die Geschichte Sachsens verraten?',
      'Sie weisen oft auf slawische Ursprünge hin',
      ['Sie beweisen römische Legionen in jedem Dorf', 'Sie zeigen immer französische Gründungen', 'Sie haben nie historische Aussagekraft'],
      'Ortsnamen sind wichtige historische Spuren.',
      'Viele Ortsnamen in Sachsen mit Endungen wie -itz oder -ow gehen auf slawische Ursprünge zurück. Solche Namen zeigen, dass Sprache historische Besiedlung sichtbar macht. Ortsnamen sind deshalb wertvolle Hinweise für Regionalgeschichte.',
      'Ortsnamen auf -itz oder -ow weisen oft auf ___ Ursprünge hin.',
      ['slawische', 'slawisch'],
    ),
    fact(
      'burgen',
      'Warum wurden im Raum Sachsen Burgen und Herrschaftszentren wichtig?',
      'Sie sicherten Herrschaft, Wege und Abgaben in einem umkämpften Raum',
      ['Sie dienten nur als Theaterbühnen', 'Sie ersetzten jedes Dorfleben', 'Sie waren bloß religiöse Begriffe ohne Bauwerke'],
      'Burgen waren militärische und administrative Zentren.',
      'Burgen spielten bei der Sicherung von Herrschaft und Verkehrswegen eine wichtige Rolle. Von ihnen aus konnten Abgaben erhoben, Gebiete kontrolliert und Siedlungen geschützt werden. So verbanden sie militärische und politische Funktionen.',
      'Burgen sicherten Herrschaft, Wege und ___.',
      ['Abgaben'],
    ),
    fact(
      'mischung',
      'Wie entwickelte sich die Bevölkerung Sachsens im Mittelalter?',
      'Durch Begegnung, Vermischung und Konflikte zwischen slawischen und deutschsprachigen Gruppen',
      ['Ohne jeden Kontakt zwischen den Gruppen', 'Nur durch Zuzug aus Nordamerika', 'Ausschließlich durch römische Kolonisten'],
      'Regionalgeschichte ist selten eine einfache Einwanderungsgeschichte.',
      'Die Geschichte Sachsens entstand aus Begegnungen zwischen bereits ansässigen slawischen Gruppen und neu hinzukommenden deutschsprachigen Siedlern. Dabei kam es zu Anpassung, Vermischung und auch Konflikten. Gerade diese Vielschichtigkeit prägt regionale Identität bis heute.',
      'Die Bevölkerung entwickelte sich durch Begegnung, Vermischung und auch ___.',
      ['Konflikte'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Sorben',
      'Westslawische Minderheit in der Lausitz',
      'Die Sorben sind bis heute Teil der sächsischen Geschichte. Ihre Sprache und Kultur erinnern an die slawische Besiedlung des Raumes.',
    ),
    pair(
      'p2',
      'Ostsiedlung',
      'Mittelalterliche Ausweitung von Siedlung und Herrschaft nach Osten',
      'Die Ostsiedlung brachte neue Dörfer, Städte und Herrschaftsformen. Sie traf auf bereits vorhandene slawische Lebenswelten.',
    ),
    pair(
      'p3',
      'Waldhufendorf',
      'Planmäßig angelegtes Dorf mit langgestreckten Flurstücken',
      'Waldhufendörfer zeigen, wie stark Landschaft während der Besiedlung gestaltet wurde. Bis heute ist diese Form oft noch erkennbar.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Vor der deutschen Ostsiedlung war das Gebiet des heutigen Sachsen weitgehend unbewohnt.',
      false,
      'Es lebten dort bereits slawische Gruppen, darunter die Vorfahren der Sorben.',
      'Der Raum Sachsen war vor der Ostsiedlung bereits besiedelt. Slawische Gruppen prägten Sprache, Ortsnamen und Kultur der Region. Genau deshalb spricht man von Begegnung und Wandel, nicht von einer Besiedlung aus dem Nichts.',
    ),
  ],
}

const kurfuerstentum: BioBank = {
  quelle: 'Wikipedia: Kurfürstentum Sachsen',
  url: 'https://de.wikipedia.org/wiki/Kurf%C3%BCrstentum_Sachsen',
  conceptPrefix: 'ge:k6:kurfuerstentum',
  facts: [
    fact(
      'kurfuerst',
      'Was war ein Kurfürst im Heiligen Römischen Reich?',
      'Ein Fürst, der das Recht hatte, den römisch-deutschen König mitzuwählen',
      ['Ein Bischof ohne politische Aufgaben', 'Ein gewählter Bürgermeister einer Stadt', 'Ein Ritter ohne Land und Titel'],
      'Kurfürsten hatten im Reich eine besonders hohe Stellung.',
      'Kurfürsten gehörten zu einem kleinen Kreis besonders bedeutender Reichsfürsten. Sie besaßen das Recht, den römisch-deutschen König zu wählen. Dadurch hatten sie großen politischen Einfluss im Reich.',
      'Ein ___ durfte den römisch-deutschen König mitwählen.',
      ['Kurfürst'],
    ),
    fact(
      'goldene-bulle',
      'Was regelte die Goldene Bulle von 1356?',
      'Vor allem die Königswahl und die besondere Stellung der Kurfürsten',
      ['Die Auflösung aller Fürstentümer', 'Die Einführung des Buchdrucks', 'Die Unabhängigkeit der USA'],
      'Die Goldene Bulle ordnete zentrale Reichsfragen.',
      'Die Goldene Bulle von 1356 war ein wichtiges Reichsgesetz unter Kaiser Karl IV. Sie regelte die Wahl des Königs und bestätigte Rechte der Kurfürsten. Für Sachsen war das bedeutsam, weil der Kurwürde damit besonderes Gewicht zukam.',
      'Die Goldene Bulle regelte vor allem die ___ des Königs.',
      ['Wahl', 'Königswahl'],
    ),
    fact(
      'wettiner',
      'Welche Dynastie prägte Sachsen lange Zeit besonders?',
      'Die Wettiner',
      ['Die Habsburger als Stadtzunft', 'Die Karolinger als Ritterorden', 'Die Tudors als Lausitzer Bauernfamilie'],
      'Die Wettiner formten die Geschichte Sachsens über Jahrhunderte.',
      'Die Wettiner waren ein bedeutendes Herrschergeschlecht im mitteldeutschen Raum. Sie prägten die Geschichte Sachsens über viele Jahrhunderte. Unter ihrer Herrschaft gewann Sachsen im Reich an politischem Gewicht.',
      'Das prägende Herrschergeschlecht Sachsens waren die ___.',
      ['Wettiner'],
    ),
    fact(
      'wahlrecht',
      'Warum war die Kurwürde für Sachsen wichtig?',
      'Sie erhöhte Rang, Einfluss und Mitspracherecht Sachsens im Reich',
      ['Sie machte Sachsen zu einer Seemacht im Mittelmeer', 'Sie beendete jede Fürstenherrschaft sofort', 'Sie gab allen Bauern das Königsamt'],
      'Mit der Kurwürde stieg Sachsen in der Reichspolitik auf.',
      'Die Kurwürde machte Sachsen zu einem der politisch wichtigsten Territorien im Reich. Wer mitwählen durfte, gewann Ansehen, Einfluss und oft zusätzliche Machtchancen. Deshalb war der Weg zum Kurfürstentum ein wichtiger Schritt der Landesgeschichte.',
      'Die Kurwürde erhöhte den politischen ___ Sachsens im Reich.',
      ['Einfluss', 'Rang'],
    ),
    fact(
      'meissen',
      'Welche ältere Herrschaftseinheit spielte für Sachsen eine wichtige Rolle?',
      'Die Markgrafschaft Meißen',
      ['Das Königreich Jerusalem', 'Die Republik Venedig', 'Die Polis Sparta'],
      'Aus älteren Herrschaftsräumen entwickelte sich das spätere Sachsen.',
      'Die Markgrafschaft Meißen war ein zentraler Herrschaftsraum der Wettiner. Von dort aus bauten sie ihre Macht aus. Für die spätere Entwicklung Sachsens war Meißen deshalb von großer Bedeutung.',
      'Ein wichtiger früher Herrschaftsraum der Wettiner war die Markgrafschaft ___.',
      ['Meißen', 'Meissen'],
    ),
    fact(
      'heiliges-roemisches-reich',
      'Zu welchem größeren politischen Verband gehörte Sachsen im Mittelalter?',
      'Zum Heiligen Römischen Reich',
      ['Zum Osmanischen Reich', 'Zur Europäischen Union', 'Zum Römischen Kaiserreich der Antike'],
      'Sachsen war Teil eines vielgestaltigen Reichsverbands.',
      'Sachsen gehörte im Mittelalter und in der frühen Neuzeit zum Heiligen Römischen Reich. Dieses Reich war kein Nationalstaat, sondern ein Verband vieler Territorien. Gerade deshalb konnten einzelne Fürsten wie die Kurfürsten besonders wichtig werden.',
      'Sachsen gehörte zum Heiligen ___ Reich.',
      ['Römischen', 'Römisch-Deutschen', 'Römischen Reich'],
    ),
    fact(
      'wahlkoenig',
      'Wer wurde von den Kurfürsten gewählt?',
      'Der römisch-deutsche König',
      ['Der Papst von Rom', 'Der Patriarch von Jerusalem', 'Der Bürgermeister von Leipzig'],
      'Die Königswahl war ein Kernrecht der Kurfürsten.',
      'Im Reich wählten die Kurfürsten den römisch-deutschen König. Dieser konnte später vom Papst zum Kaiser gekrönt werden, musste es aber nicht in jedem Fall. Fürstenmacht und Reichsordnung waren dadurch eng miteinander verbunden.',
      'Die Kurfürsten wählten den römisch-deutschen ___.',
      ['König', 'Koenig'],
    ),
    fact(
      'territorium',
      'Was zeigt Sachsens Weg zum Kurfürstentum über Herrschaft im Reich?',
      'Dass Territorien durch Titel, Dynastien und Reichsrecht an Bedeutung gewinnen konnten',
      ['Dass nur Städte Geschichte machten', 'Dass Titel im Mittelalter völlig unwichtig waren', 'Dass das Reich keine festen Regeln kannte'],
      'Landesgeschichte und Reichsgeschichte greifen ineinander.',
      'Sachsens Aufstieg zum Kurfürstentum zeigt, wie stark mittelalterliche Politik von Titeln, Erbrecht und Reichsrecht geprägt war. Territoriale Herrschaft entstand nicht plötzlich. Sie wuchs durch lange Entwicklungen und politische Anerkennung im Reich.',
      'Sachsens Aufstieg zeigt die wachsende Bedeutung von ___ und Reichsrecht.',
      ['Titeln', 'Dynastien'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Kurfürst',
      'Reichsfürst mit Wahlrecht für den König',
      'Kurfürsten nahmen im Reich eine Sonderstellung ein. Ihre Stimme bei der Königswahl machte sie politisch besonders einflussreich.',
    ),
    pair(
      'p2',
      'Goldene Bulle',
      'Reichsgesetz von 1356 zur Ordnung der Königswahl',
      'Die Goldene Bulle ordnete zentrale Fragen der Reichsverfassung. Sie festigte die Rechte und das Ansehen der Kurfürsten.',
    ),
    pair(
      'p3',
      'Wettiner',
      'Herrscherdynastie, die Sachsen lange prägte',
      'Die Wettiner bestimmten über Jahrhunderte die Landesgeschichte Sachsens. Mit ihnen verband sich der politische Aufstieg des Territoriums.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Die Goldene Bulle von 1356 machte Sachsen zu einer Seemacht mit Kolonien.',
      false,
      'Sie regelte die Königswahl und stärkte die Stellung der Kurfürsten im Reich.',
      'Die Goldene Bulle war ein Verfassungstext des Heiligen Römischen Reichs. Ihr Schwerpunkt lag auf Wahlrecht und Rang der Kurfürsten, nicht auf Überseehandel oder Kolonien. Für Sachsen war genau diese reichspolitische Rolle entscheidend.',
    ),
  ],
}

const selbstverstaendnis: BioBank = {
  quelle: 'Wikipedia: Geschichte Sachsens',
  url: 'https://de.wikipedia.org/wiki/Geschichte_Sachsens',
  conceptPrefix: 'ge:k6:selbstverstaendnis',
  facts: [
    fact(
      'residenz',
      'Was ist eine Residenzstadt?',
      'Eine Stadt, in der ein Fürst oder Herrscher dauerhaft seinen Hof hat',
      ['Eine unbewohnte Burg im Wald', 'Nur eine Handelskolonie ohne Regierung', 'Ein Kloster ohne weltliche Macht'],
      'Residenzstädte bündeln Herrschaft und Repräsentation.',
      'Eine Residenzstadt ist der Ort, an dem ein Herrscher seinen Hof und wichtige Verwaltungsstellen ansiedelt. Dort entstehen häufig Schlösser, Kirchen und repräsentative Bauten. Residenzen prägen deshalb Machtbild und Selbstverständnis eines Landes.',
      'Eine Residenzstadt ist der Sitz eines fürstlichen ___.',
      ['Hofes', 'Hofs'],
    ),
    fact(
      'dresden',
      'Warum wurde Dresden für Sachsen besonders wichtig?',
      'Weil es sich zur bedeutenden Residenz- und Kulturstadt entwickelte',
      ['Weil dort die Goldene Bulle geschrieben wurde', 'Weil nur Bauern dort wohnen durften', 'Weil es die Hauptstadt des Römischen Reiches war'],
      'Dresden wurde ein Zentrum von Herrschaft und Kultur.',
      'Dresden entwickelte sich in der Neuzeit zu einer wichtigen Residenzstadt der sächsischen Herrscher. Hof, Verwaltung und Kunstförderung machten die Stadt weithin bekannt. So wurde Dresden zu einem Symbol sächsischer Geschichte und Kultur.',
      'Dresden wurde vor allem als Residenz- und ___ wichtig.',
      ['Kulturstadt'],
    ),
    fact(
      'meissen',
      'Welche Stadt steht besonders für frühe sächsische Herrschaft und Geschichte?',
      'Meißen',
      ['Jerusalem', 'Athen', 'Córdoba'],
      'Meißen war lange ein politischer und kultureller Bezugspunkt.',
      'Meißen spielte für die frühe Landesgeschichte Sachsens eine zentrale Rolle. Mit Burg und Dom wurde die Stadt zu einem wichtigen Herrschafts- und Glaubenszentrum. Daher gehört sie bis heute zum historischen Selbstverständnis des Landes.',
      'Eine frühe Schlüsselstadt sächsischer Geschichte ist ___.',
      ['Meißen', 'Meissen'],
    ),
    fact(
      'kulturfoerderung',
      'Warum gehört Kultur zur Geschichte sächsischen Selbstverständnisses?',
      'Weil Herrscher Kunst, Musik, Bauwerke und Sammlungen zur Darstellung des Landes nutzten',
      ['Weil Kultur für Herrschaft völlig bedeutungslos war', 'Weil nur militärische Siege Identität prägen', 'Weil Sachsen keine Städte mit Kunst besaß'],
      'Kultur zeigt Macht, Reichtum und Identität.',
      'Herrscher förderten in Sachsen Kunst, Musik, Architektur und Sammlungen nicht nur aus persönlichem Interesse. Kultur diente auch dazu, Macht sichtbar zu machen und dem Land ein besonderes Ansehen zu geben. So entstand ein identitätsstiftendes Bild Sachsens.',
      'Kulturförderung half, Macht und ___ sichtbar zu machen.',
      ['Identität', 'Ansehen'],
    ),
    fact(
      'porzellan',
      'Wofür wurde Meißen in der frühen Neuzeit europaweit bekannt?',
      'Für das Meißner Porzellan',
      ['Für den Bau der Akropolis', 'Für die Erfindung des Schießpulvers', 'Für die Magna Carta'],
      'Das Porzellan wurde ein Symbol sächsischer Kultur.',
      'Meißen wurde in der frühen Neuzeit durch seine Porzellanmanufaktur berühmt. Das sogenannte weiße Gold verband Handwerk, Kunst und wirtschaftliches Prestige. Noch heute steht es für einen Teil des kulturellen Selbstbildes Sachsens.',
      'Meißen wurde besonders durch ___ berühmt.',
      ['Porzellan', 'Meißner Porzellan', 'Meissner Porzellan'],
    ),
    fact(
      'bauwerke',
      'Warum sind Schlösser, Dome und Sammlungen für das Selbstverständnis eines Landes wichtig?',
      'Weil sie Geschichte sichtbar machen und Erinnerung an Herrschaft und Kultur bewahren',
      ['Weil Gebäude keine Aussage über Geschichte haben', 'Weil nur Schriftquellen Erinnerung tragen', 'Weil Bauwerke im Mittelalter immer zerstört wurden'],
      'Bauwerke und Sammlungen sind Formen historischer Erinnerung.',
      'Bauwerke, Kunstsammlungen und Denkmäler machen Geschichte im Alltag sichtbar. Sie erinnern an Herrscher, religiöse Traditionen und kulturelle Leistungen. Deshalb prägen solche Orte, wie ein Land sich selbst sieht und darstellt.',
      'Schlösser und Dome bewahren historische ___.',
      ['Erinnerung', 'Geschichte'],
    ),
    fact(
      'symbolorte',
      'Was zeigen symbolische Orte wie Residenzen oder historische Stadtkerne?',
      'Sie verbinden politische Geschichte mit kultureller Erinnerung',
      ['Sie haben nur touristische, aber keine historische Bedeutung', 'Sie entstanden erst nach 1990', 'Sie gehören ausschließlich zur Wirtschaftsgeschichte'],
      'Historische Orte verdichten Vergangenheit an einem Platz.',
      'Symbolische Orte sind wichtig, weil sich an ihnen politische und kulturelle Geschichte bündeln. Wer eine Residenzstadt besucht, sieht Herrschaft, Kunst und Erinnerung zugleich. Gerade dadurch prägen solche Orte das Selbstverständnis einer Region.',
      'Symbolische Orte verbinden politische Geschichte mit kultureller ___.',
      ['Erinnerung'],
    ),
    fact(
      'landesidentitaet',
      'Was bedeutet "sächsisches Selbstverständnis" in der Geschichte?',
      'Vorstellungen darüber, was Sachsen ausmacht und worauf sich das Land beruft',
      ['Nur eine Liste moderner Autokennzeichen', 'Eine mittelalterliche Maßeinheit', 'Ausschließlich die Militärstärke eines Fürsten'],
      'Selbstverständnis entsteht aus Geschichte, Erinnerung und Deutung.',
      'Sächsisches Selbstverständnis meint historische Vorstellungen darüber, welche Orte, Traditionen und Leistungen für Sachsen typisch sind. Dazu gehören Herrschaft, Kultur und regionale Erinnerung. Solche Bilder entstehen nicht naturgegeben, sondern werden immer wieder neu gedeutet.',
      'Sächsisches Selbstverständnis besteht aus historischen ___ und Deutungen.',
      ['Vorstellungen', 'Bildern'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Residenzstadt',
      'Sitz eines Herrscherhofes mit Verwaltung und Repräsentation',
      'Residenzstädte bündeln politische Macht, Hofleben und Kultur. Deshalb werden sie oft zu Symbolorten der Landesgeschichte.',
    ),
    pair(
      'p2',
      'Dresden',
      'Bedeutende sächsische Residenz- und Kulturstadt',
      'Dresden steht für Hofkultur, Repräsentation und künstlerische Förderung. Die Stadt wurde zu einem zentralen Erinnerungsort Sachsens.',
    ),
    pair(
      'p3',
      'Meißner Porzellan',
      'Kulturelles Prestigeprodukt Sachsens',
      'Porzellan aus Meißen verband Handwerk, Kunst und höfischen Anspruch. Darum wurde es Teil des sächsischen Selbstbilds.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Sächsisches Selbstverständnis hat nur mit Politik zu tun, nicht mit Kultur oder Erinnerungsorten.',
      false,
      'Kultur, Bauwerke und symbolische Orte gehören wesentlich dazu.',
      'Historisches Selbstverständnis entsteht nicht allein aus Politik. Residenzen, Kunst, Bauwerke und regionale Erinnerungsorte prägen mit, wie Sachsen sich historisch deutet. Gerade Kultur verleiht dieser Deutung Sichtbarkeit.',
    ),
  ],
}

export const GESCHICHTE_K6_REST_GENERATORS: Record<string, Topic['generate']> = {
  'ge-k6-lb2-mittelalter': bankGenerate(mittelalter),
  'ge-k6-lb3-religionen': bankGenerate(religionen),
  'ge-k6-lb4-buerger': bankGenerate(buerger),
  'ge-k6-lbw-besiedlung': bankGenerate(besiedlung),
  'ge-k6-lbw-kurfuerstentum': bankGenerate(kurfuerstentum),
  'ge-k6-lbw-selbstverstaendnis': bankGenerate(selbstverstaendnis),
}
