import { bankGenerate, type BioBank } from './biologieBank'
import type { Topic } from './types'

const fact = (
  concept: string,
  prompt: string,
  answer: string,
  wrong: [string, string, string],
  explanation: string,
  wissen: string,
  gap: string,
  gapAccepted: string[],
) => ({ concept, prompt, answer, wrong, explanation, wissen, gap, gapAccepted })

const pair = (concept: string, term: string, meaning: string, wissen: string) => ({
  concept,
  term,
  meaning,
  wissen,
})

const tf = (
  concept: string,
  statement: string,
  correct: boolean,
  explanation: string,
  wissen: string,
) => ({ concept, statement, correct, explanation, wissen })

const sort = (
  concept: string,
  question: string,
  labels: string[],
  explanation: string,
  wissen: string,
) => ({ concept, question, labels, explanation, wissen })

const einheitFreiheit: BioBank = {
  quelle: 'Wikipedia: Deutsche Revolution 1848/1849',
  url: 'https://de.wikipedia.org/wiki/Deutsche_Revolution_1848/1849',
  conceptPrefix: 'ge:k8:einheit-freiheit',
  facts: [
    fact(
      'vormaerz',
      'Was meint der Begriff Vormärz?',
      'Die Zeit vor der Revolution von 1848 mit wachsender Kritik an Unterdrückung und Zersplitterung',
      ['Die Jahre nach dem Ersten Weltkrieg', 'Nur die französische Hofgesellschaft Ludwigs XIV.', 'Die Epoche vor der Gründung Roms'],
      'Vormärz benennt politische Spannung vor 1848.',
      'Als Vormärz bezeichnet man die Zeit vor der Revolution von 1848 im Deutschen Bund. In diesen Jahren wuchsen Forderungen nach Freiheit, Verfassung und nationaler Einheit. Zugleich versuchten viele Herrscher, oppositionelle Stimmen zu überwachen und einzuschränken.',
      'Vormärz bezeichnet die Zeit vor der Revolution von ___.',
      ['1848'],
    ),
    fact(
      'deutscher-bund',
      'Warum war die Frage nach deutscher Einheit im 19. Jahrhundert so wichtig?',
      'Weil der Deutsche Bund aus vielen Einzelstaaten bestand und nationale Einigung fehlte',
      ['Weil Deutschland schon ein einheitlicher Nationalstaat war', 'Weil nur Frankreich darüber entschied', 'Weil Einheit nur ein Thema des Mittelalters war'],
      'Zersplitterung und Nationalidee prägten die Epoche.',
      'Nach 1815 bestand der Deutsche Bund aus vielen Einzelstaaten. Für viele Liberale und Nationalgesinnte war das ein Hindernis für politische Mitbestimmung und wirtschaftliche Entwicklung. Darum wurden Einheit und Freiheit häufig zusammen gedacht.',
      'Die Frage nach Einheit entstand vor dem Hintergrund vieler deutschen ___.',
      ['Einzelstaaten', 'Staaten'],
    ),
    fact(
      'revolution-1848',
      'Was forderten viele Menschen in der Revolution von 1848?',
      'Verfassungen, Grundrechte und nationale Einheit',
      ['Die Rückkehr zur Grundherrschaft', 'Nur mehr Macht für den Adel', 'Die Abschaffung aller Zeitungen'],
      'Die Revolution verband politische Rechte mit der Nationalfrage.',
      '1848 erhoben sich in vielen deutschen Staaten Menschen für politische Mitbestimmung. Sie forderten Verfassungen, Pressefreiheit und nationale Einheit. Die Revolution war damit zugleich liberal, national und sozial aufgeladen.',
      '1848 forderten viele Menschen Verfassungen, Grundrechte und nationale ___.',
      ['Einheit'],
    ),
    fact(
      'paulskirche',
      'Warum ist die Frankfurter Paulskirche historisch bedeutsam?',
      'Weil dort 1848/49 die Nationalversammlung über eine deutsche Verfassung beriet',
      ['Weil dort der Versailler Vertrag unterschrieben wurde', 'Weil Ludwig XIV. dort residierte', 'Weil dort die Jesuiten gegründet wurden'],
      'Die Paulskirche steht für den Versuch parlamentarischer Einigung.',
      'In der Frankfurter Paulskirche tagte 1848/49 die erste gesamtdeutsche Nationalversammlung. Die Abgeordneten diskutierten Grundrechte und eine Verfassung für Deutschland. Auch wenn der Versuch scheiterte, blieb er ein wichtiger Bezugspunkt deutscher Demokratiegeschichte.',
      'In der Paulskirche tagte die deutsche National___.',
      ['versammlung'],
    ),
    fact(
      'grundrechte',
      'Welche politische Idee wurde 1848 besonders wichtig?',
      'Dass Bürger Grundrechte und politische Mitbestimmung erhalten sollen',
      ['Dass nur Fürsten politische Rechte haben', 'Dass Pressefreiheit abgeschafft werden müsse', 'Dass Nation nur über Kriege entsteht'],
      'Freiheit wurde rechtlich gedacht.',
      'Im Umfeld der Revolution von 1848 wurden Grundrechte intensiv diskutiert. Dazu gehörten Pressefreiheit, Versammlungsfreiheit und Gleichheit vor dem Gesetz. Freiheit sollte also nicht nur ein Gefühl, sondern rechtlich gesichert sein.',
      '1848 wurde Freiheit besonders über ___ und Mitbestimmung gedacht.',
      ['Grundrechte'],
    ),
    fact(
      'bismarck',
      'Welche Rolle spielte Otto von Bismarck bei der Reichsgründung von 1871?',
      'Er betrieb die Einigung von oben unter preußischer Führung',
      ['Er leitete die Paulskirchenversammlung 1848', 'Er war Führer der Chartisten in England', 'Er gründete den Jesuitenorden'],
      'Die Einigung 1871 verlief anders als die liberalen Hoffnungen von 1848.',
      'Otto von Bismarck prägte die Einigung Deutschlands unter preußischer Führung. Die Reichsgründung von 1871 entstand nicht als freiheitliche Volksbewegung, sondern durch Machtpolitik, Kriege und Fürstenentscheidungen. Damit erfüllte sie Einheit, aber nur teilweise die Freiheitsforderungen von 1848.',
      'Bismarck betrieb die Einigung Deutschlands unter ___ Führung.',
      ['preußischer', 'preussischer'],
    ),
    fact(
      'reichsgruendung',
      'Warum war die Reichsgründung von 1871 nur eine teilweise Erfüllung von "Einheit und Freiheit"?',
      'Weil die Einheit erreicht wurde, aber politische Freiheit begrenzt blieb',
      ['Weil weder Einheit noch Staat entstanden', 'Weil Deutschland sofort eine reine Basisdemokratie wurde', 'Weil Fürsten nach 1871 keine Rolle mehr spielten'],
      'Der Nationalstaat löste nicht automatisch alle Freiheitsfragen.',
      'Mit der Reichsgründung 1871 entstand ein deutscher Nationalstaat. Doch dieser Staat war stark monarchisch geprägt und nicht einfach die Verwirklichung aller liberalen Forderungen. Einheit und Freiheit fielen also historisch nicht vollständig zusammen.',
      '1871 wurde Einheit erreicht, doch Freiheit blieb nur teilweise ___.',
      ['verwirklicht', 'erfüllt'],
    ),
    fact(
      'buergertum',
      'Warum spielte das Bürgertum bei Einheit und Freiheit eine große Rolle?',
      'Weil viele bürgerliche Gruppen Verfassung, Rechtsstaat und nationale Einheit forderten',
      ['Weil das Bürgertum nur zur Ritterausbildung diente', 'Weil es grundsätzlich gegen Bildung und Parlamente war', 'Weil nur Bauern die Nationalfrage bewegte'],
      'Das Bürgertum trug viele Reformvorstellungen des 19. Jahrhunderts.',
      'Im 19. Jahrhundert formulierten viele bürgerliche Gruppen Forderungen nach Verfassung, Rechtsstaat und Nation. Sie verbanden wirtschaftliche Interessen mit politischen Idealen. Dadurch wurde das Bürgertum zu einem wichtigen Träger der Bewegungen von 1848.',
      'Das Bürgertum forderte oft Verfassung, Rechtsstaat und nationale ___.',
      ['Einheit'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Vormärz',
      'Zeit politischer Spannung vor 1848',
      'Im Vormärz wuchsen Forderungen nach Freiheit und Einheit. Zugleich reagierten viele Staaten mit Zensur und Überwachung.',
    ),
    pair(
      'p2',
      'Paulskirche',
      'Tagungsort der Nationalversammlung 1848/49',
      'Die Paulskirche steht für den Versuch, Deutschland parlamentarisch zu einen. Sie blieb ein wichtiger Erinnerungsort.',
    ),
    pair(
      'p3',
      'Reichsgründung 1871',
      'Nationalstaat unter preußischer Führung',
      'Die Reichsgründung erfüllte die Einheitsfrage, aber nicht alle liberalen Freiheitsforderungen. Darin liegt ihre Ambivalenz.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Mit der Reichsgründung von 1871 waren automatisch alle Freiheitsforderungen der Revolution von 1848 erfüllt.',
      false,
      'Einheit wurde erreicht, aber der Staat blieb monarchisch und politisch begrenzt.',
      'Der Nationalstaat von 1871 löste nicht automatisch die Fragen nach Parlamentarismus, voller Mitbestimmung und Bürgerrechten. Viele Hoffnungen von 1848 blieben nur teilweise verwirklicht. Gerade deshalb unterscheidet man Einigung und Liberalisierung.',
    ),
  ],
  sorts: [
    sort(
      's1',
      'Ordne chronologisch:',
      ['Vormärz', 'Revolution 1848/49', 'Reichsgründung 1871'],
      'Zuerst wächst Kritik, dann folgt die Revolution, später entsteht der Nationalstaat.',
      'Vom Vormärz führt der Weg in die Revolution von 1848/49. Erst später folgt mit 1871 die Reichsgründung unter preußischer Führung. Chronologie hilft, Einheits- und Freiheitsfrage auseinanderzuhalten.',
    ),
  ],
}

const industrialisierung: BioBank = {
  quelle: 'Wikipedia: Industrialisierung',
  url: 'https://de.wikipedia.org/wiki/Industrialisierung',
  conceptPrefix: 'ge:k8:industrialisierung',
  facts: [
    fact(
      'dampfmaschine',
      'Warum war die Dampfmaschine ein Schlüsselsymbol der Industrialisierung?',
      'Weil sie menschliche und tierische Arbeit in vielen Bereichen durch Maschinenkraft ergänzte',
      ['Weil sie nur für Ritterturniere gebaut wurde', 'Weil sie ausschließlich im Mittelalter vorkam', 'Weil sie keine wirtschaftlichen Folgen hatte'],
      'Maschinenkraft beschleunigte Produktion und Verkehr.',
      'Die Dampfmaschine nutzte erhitzten Wasserdampf, um Maschinen anzutreiben. Sie veränderte Fabriken, Bergbau und später auch den Verkehr grundlegend. Dadurch wurde die Industrialisierung schneller und tiefgreifender.',
      'Die Dampfmaschine lieferte neue ___ für Produktion und Verkehr.',
      ['Kraft', 'Maschinenkraft'],
    ),
    fact(
      'fabrik',
      'Was unterschied die Fabrik von älteren Produktionsformen?',
      'Arbeit, Maschinen und viele Beschäftigte wurden an einem Ort zentral gebündelt',
      ['Fabriken bestanden nur aus Heimarbeit ohne Aufsicht', 'Sie waren identisch mit mittelalterlichen Burgen', 'Sie dienten ausschließlich religiösen Feiern'],
      'Die Fabrik veränderte Arbeitsorganisation und Alltag.',
      'In der Fabrik wurden Maschinen, Rohstoffe und Arbeitskräfte zentral zusammengeführt. Das erhöhte die Produktivität, führte aber auch zu strenger Zeitordnung und Abhängigkeit vom Arbeitgeber. Arbeit wurde damit anders organisiert als im Handwerk oder in der Heimarbeit.',
      'In der Fabrik wurden Maschinen und Arbeit an einem Ort ___.',
      ['gebündelt', 'zentralisiert'],
    ),
    fact(
      'eisenbahn',
      'Warum war die Eisenbahn für die Industrialisierung so wichtig?',
      'Weil sie Menschen, Rohstoffe und Waren schneller und günstiger transportierte',
      ['Weil sie Segelschiffe vollständig ersetzte', 'Weil sie nur militärische Bedeutung hatte', 'Weil sie Handel eher verlangsamte'],
      'Verkehrsrevolution und Industrialisierung verstärkten sich gegenseitig.',
      'Die Eisenbahn verkürzte Entfernungen und senkte Transportkosten erheblich. Kohle, Eisen und fertige Produkte konnten schneller bewegt werden. Dadurch beschleunigte sie Wirtschaftswachstum, Mobilität und Vernetzung ganzer Regionen.',
      'Die Eisenbahn erleichterte den Transport von Menschen, Rohstoffen und ___.',
      ['Waren'],
    ),
    fact(
      'soziale-frage',
      'Was meint die "soziale Frage" im 19. Jahrhundert?',
      'Die Probleme von Armut, schlechten Arbeitsbedingungen und fehlender Absicherung in der Industriegesellschaft',
      ['Die Frage nach der Königswahl im Reich', 'Nur das Problem zu weniger Ritterburgen', 'Die Suche nach antiken Handschriften'],
      'Industrialisierung brachte Fortschritt und neue Notlagen zugleich.',
      'Die soziale Frage bezeichnet die Probleme, die mit raschem Wachstum von Fabrikarbeit und Städten entstanden. Viele Menschen lebten in Armut, arbeiteten lange Stunden und hatten kaum Schutz bei Krankheit oder Arbeitslosigkeit. Politik musste darauf neue Antworten finden.',
      'Die soziale Frage beschreibt Armut und schlechte ___ in der Industriegesellschaft.',
      ['Arbeitsbedingungen'],
    ),
    fact(
      'urbanisierung',
      'Warum wuchsen Städte in der Industrialisierung so stark?',
      'Weil viele Menschen wegen Arbeit in Fabriken vom Land in die Stadt zogen',
      ['Weil Städte plötzlich wieder mittelalterliche Mauern brauchten', 'Weil Bauernhöfe in Innenstädte verlegt wurden', 'Weil nur Könige in Städten leben durften'],
      'Industrie und Urbanisierung gehören eng zusammen.',
      'Industrialisierung zog viele Arbeitskräfte in Städte und Industrieregionen. Dort entstanden neue Wohnviertel, aber oft auch Enge, schlechte Hygiene und soziale Spannungen. Stadtwachstum war daher Chance und Belastung zugleich.',
      'Viele Menschen zogen wegen Fabrikarbeit vom Land in die ___.',
      ['Stadt'],
    ),
    fact(
      'gewerkschaften',
      'Warum bildeten Arbeiter im 19. Jahrhundert Gewerkschaften?',
      'Um gemeinsam bessere Löhne, Arbeitszeiten und Rechte durchzusetzen',
      ['Um die Rückkehr zum Feudalismus zu fordern', 'Um Fabriken vollständig an Fürsten zu verschenken', 'Um den Buchdruck zu verbieten'],
      'Gemeinsame Interessenvertretung wurde in der Industriegesellschaft wichtig.',
      'Einzelne Arbeiter waren gegenüber Unternehmern oft schwach. Deshalb entstanden Gewerkschaften als Organisationen gemeinsamer Interessen. Sie kämpften für Löhne, Schutz und politische Mitbestimmung.',
      'Gewerkschaften sollten gemeinsam bessere ___ und Rechte durchsetzen.',
      ['Löhne', 'Arbeitsbedingungen'],
    ),
    fact(
      'fortschritt',
      'Warum spricht man von einem "Doppelgesicht des Fortschritts"?',
      'Weil die Industrialisierung Wohlstand und Technik förderte, aber auch Not und Umweltbelastung brachte',
      ['Weil Fortschritt nur Nachteile hatte', 'Weil Industrialisierung nur auf dem Papier stattfand', 'Weil es damals keinerlei soziale Probleme gab'],
      'Fortschritt wirkte widersprüchlich.',
      'Industrialisierung brachte neue Produkte, Verkehrsmittel und wachsende Produktion. Zugleich verschärfte sie Armut, Ausbeutung und Umweltprobleme in vielen Regionen. Deshalb bewertet man Fortschritt historisch nicht nur positiv oder nur negativ.',
      'Das Doppelgesicht des Fortschritts meint Technikgewinn und soziale ___.',
      ['Belastungen', 'Probleme'],
    ),
    fact(
      'kohle',
      'Warum spielte Kohle in der Industrialisierung eine zentrale Rolle?',
      'Weil sie als wichtiger Energieträger Maschinen, Hütten und Eisenbahnen versorgte',
      ['Weil sie nur Schmuck für den Adel war', 'Weil sie keine Energie liefern konnte', 'Weil sie erst im 20. Jahrhundert entdeckt wurde'],
      'Energiequellen sind Grundlagen wirtschaftlicher Umbrüche.',
      'Kohle war im 19. Jahrhundert einer der wichtigsten Energieträger. Sie trieb Dampfmaschinen an und versorgte Bergbau, Hüttenwesen und Eisenbahn. Ohne Kohle wäre die Industrialisierung in vielen Regionen kaum denkbar gewesen.',
      'Kohle war ein zentraler ___ der Industrialisierung.',
      ['Energieträger'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Dampfmaschine',
      'Maschinenkraft durch Wasserdampf',
      'Die Dampfmaschine erhöhte Produktivität und veränderte Verkehr wie Produktion. Sie wurde zum Symbol der industriellen Epoche.',
    ),
    pair(
      'p2',
      'soziale Frage',
      'Armut und Unsicherheit in der Industriegesellschaft',
      'Die soziale Frage machte sichtbar, dass wirtschaftlicher Fortschritt nicht automatisch gerechte Lebensbedingungen schuf. Daraus entstanden Reformen und politische Bewegungen.',
    ),
    pair(
      'p3',
      'Gewerkschaft',
      'Organisation zur Vertretung von Arbeiterinteressen',
      'Gewerkschaften sollten die Verhandlungsmacht von Arbeitern stärken. Sie wurden zu wichtigen Akteuren moderner Industriegesellschaften.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Industrialisierung veränderte nur Technik, nicht aber Wohnorte, Arbeitsalltag oder soziale Konflikte.',
      false,
      'Sie prägte zugleich Städte, Arbeit, Armut und politische Reaktionen.',
      'Industrialisierung war nicht nur eine Frage von Maschinen. Sie veränderte Städte, Lebensweise, Arbeitszeiten und soziale Beziehungen grundlegend. Gerade deshalb spricht man von einem tiefen gesellschaftlichen Wandel.',
    ),
  ],
}

const kinderarbeit: BioBank = {
  quelle: 'Wikipedia: Kinderarbeit',
  url: 'https://de.wikipedia.org/wiki/Kinderarbeit',
  conceptPrefix: 'ge:k8:kinderarbeit',
  facts: [
    fact(
      'gruende',
      'Warum mussten im 19. Jahrhundert viele Kinder arbeiten?',
      'Weil arme Familien auf ihren Verdienst angewiesen waren',
      ['Weil Kinder gesetzlich als Fabrikbesitzer galten', 'Weil Schulen überall verboten wurden', 'Weil nur Kinder Dampfmaschinen bedienen konnten'],
      'Kinderarbeit hing eng mit Armut zusammen.',
      'Viele Familien lebten in der frühen Industriegesellschaft am Existenzminimum. Darum mussten auch Kinder zum Einkommen beitragen. Kinderarbeit war also nicht nur eine Fabrikfrage, sondern eng mit sozialer Not verbunden.',
      'Viele Kinder arbeiteten, weil ihre Familien sehr ___ waren.',
      ['arm'],
    ),
    fact(
      'arbeitsorte',
      'Wo arbeiteten Kinder während der Industrialisierung häufig?',
      'In Fabriken, Bergwerken, Werkstätten und im Heimgewerbe',
      ['Nur in Parlamenten und Ministerien', 'Ausschließlich in Universitäten', 'Nur auf Schiffen in Übersee'],
      'Kinderarbeit war in verschiedenen Wirtschaftsbereichen verbreitet.',
      'Kinderarbeit gab es nicht nur in großen Fabriken. Kinder arbeiteten auch in Bergwerken, in Werkstätten oder in Heimarbeit für Verlage und Textilbetriebe. Dadurch war sie in vielen Lebensbereichen sichtbar.',
      'Kinder arbeiteten oft in Fabriken, Bergwerken und ___.',
      ['Werkstätten', 'Heimgewerben'],
    ),
    fact(
      'folgen-gesundheit',
      'Welche Folgen hatte Kinderarbeit oft für die Gesundheit?',
      'Erschöpfung, Verletzungen, Wachstumsprobleme und Krankheit',
      ['Automatisch bessere Ernährung', 'Mehr Freizeit und Erholung', 'Höhere Lebenserwartung durch Fabrikluft'],
      'Schwere Arbeit belastete Kinderkörper besonders stark.',
      'Kinderkörper waren für lange Arbeitszeiten, Staub, Lärm und schwere Belastungen besonders empfindlich. Deshalb führte Kinderarbeit oft zu Krankheit, Verletzungen und dauerhaften Schäden. Historisch wurde dieser Missstand zunehmend kritisiert.',
      'Kinderarbeit führte oft zu Krankheit, Verletzungen und körperlicher ___.',
      ['Erschöpfung'],
    ),
    fact(
      'schule',
      'Warum stand Kinderarbeit im Widerspruch zu Schulbildung?',
      'Weil lange Arbeitszeiten den regelmäßigen Schulbesuch erschwerten oder verhinderten',
      ['Weil Fabriken eigene Universitäten ersetzten', 'Weil Lesen für Kinder verboten war', 'Weil Schule nur für Adelssöhne galt'],
      'Bildungschancen litten unter Arbeitszwang.',
      'Wenn Kinder viele Stunden arbeiten mussten, blieb kaum Zeit oder Kraft für Unterricht. Dadurch wurden Bildungswege versperrt und Armut oft an die nächste Generation weitergegeben. Die Frage nach Kinderarbeit war daher immer auch eine Bildungsfrage.',
      'Lange Arbeitszeiten erschwerten den regelmäßigen ___ der Kinder.',
      ['Schulbesuch'],
    ),
    fact(
      'kritik',
      'Warum wurde Kinderarbeit im 19. Jahrhundert zunehmend kritisiert?',
      'Weil sie als unmenschlich galt und Gesundheit sowie Bildung von Kindern gefährdete',
      ['Weil Kinderarbeit die Gewinne der Unternehmer immer verringerte', 'Weil Parlamente nur Erwachsenenarbeit verboten', 'Weil es kaum Beispiele für Kinderarbeit gab'],
      'Moralische und soziale Kritik wuchs mit der Industrialisierung.',
      'Mit der Zeit kritisierten Ärzte, Lehrer, Geistliche und Politiker die Folgen der Kinderarbeit schärfer. Man sah, dass Kinder Schutz brauchten und nicht bloß billige Arbeitskräfte waren. Daraus entstanden Forderungen nach Gesetzen und Schulpflicht.',
      'Kinderarbeit wurde kritisiert, weil sie Gesundheit und ___ gefährdete.',
      ['Bildung'],
    ),
    fact(
      'schutzgesetze',
      'Was sollten Fabrikgesetze gegen Kinderarbeit erreichen?',
      'Arbeitszeiten begrenzen und Kinder besser schützen',
      ['Kinder zu mehr Nachtarbeit verpflichten', 'Schulen abschaffen und Fabriken ausweiten', 'Jede Arbeit für Erwachsene verbieten'],
      'Staatliche Eingriffe reagierten auf soziale Missstände.',
      'Im 19. Jahrhundert entstanden nach und nach Gesetze, die Kinderarbeit einschränkten. Sie regelten Mindestalter, Arbeitszeit oder Aufsicht. Solche Schutzgesetze zeigen, dass der Staat stärker in soziale Fragen eingriff.',
      'Fabrikgesetze sollten Kinder besser ___ und ihre Arbeitszeit begrenzen.',
      ['schützen'],
    ),
    fact(
      'laengsschnitt',
      'Warum eignet sich Kinderarbeit für einen Längsschnitt?',
      'Weil sich daran Wandel von Arbeit, Kindheit und Schutzrechten gut vergleichen lässt',
      ['Weil Kinderarbeit nur in einem einzigen Jahrzehnt vorkam', 'Weil sich Einstellungen zu Kindheit nie änderten', 'Weil man dazu keine Quellen besitzt'],
      'Ein Längsschnitt macht Wandel sozialer Vorstellungen sichtbar.',
      'Kinderarbeit zeigt, dass Vorstellungen von Kindheit historisch nicht feststehen. Was früher als normal oder notwendig galt, wurde später stark kritisiert und rechtlich eingeschränkt. Gerade dieser Wandel lässt sich im Längsschnitt gut erkennen.',
      'Ein Längsschnitt zeigt den Wandel von Arbeit, Kindheit und ___rechten.',
      ['Schutz', 'Schutzrechten'],
    ),
    fact(
      'heute',
      'Warum ist die Geschichte der Kinderarbeit auch heute noch relevant?',
      'Weil sie hilft, aktuelle Ausbeutung von Kindern weltweit kritisch zu beurteilen',
      ['Weil Kinderarbeit nur noch ein Thema der Antike ist', 'Weil heute nirgends mehr Kinder arbeiten', 'Weil Geschichte mit Gegenwart nichts zu tun hat'],
      'Historisches Lernen schärft den Blick für Gegenwartsprobleme.',
      'Kinderarbeit ist kein rein vergangenes Thema. Auch heute gibt es weltweit Formen von Ausbeutung, gegen die internationale Regeln und Schutzmaßnahmen wirken sollen. Die Geschichte des 19. Jahrhunderts schärft dafür das Bewusstsein.',
      'Die Geschichte der Kinderarbeit hilft, heutige ___ kritisch zu beurteilen.',
      ['Ausbeutung', 'Kinderarbeit'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Kinderarbeit',
      'Erwerbsarbeit von Kindern unter belastenden Bedingungen',
      'Kinderarbeit war eng mit Armut verbunden und gefährdete Gesundheit wie Bildung. Sie wurde im 19. Jahrhundert zunehmend öffentlich kritisiert.',
    ),
    pair(
      'p2',
      'Fabrikgesetz',
      'Staatliche Regel zur Begrenzung und Kontrolle von Kinderarbeit',
      'Fabrikgesetze zeigen den wachsenden staatlichen Schutzanspruch in sozialen Fragen. Sie begrenzten Arbeitszeiten und setzten Mindestalter fest.',
    ),
    pair(
      'p3',
      'Schulpflicht',
      'Verbindlicher Unterricht statt dauernder Kinderarbeit',
      'Schulpflicht stärkte Bildungschancen und begrenzte Kinderarbeit. Sie war ein wichtiger Schritt im Wandel des Kindheitsbildes.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Kinderarbeit war im 19. Jahrhundert vor allem deshalb unproblematisch, weil sie Bildung und Gesundheit der Kinder förderte.',
      false,
      'Gerade Gesundheitsschäden und fehlende Bildung machten Kinderarbeit zum sozialen Problem.',
      'Kinderarbeit stand meist mit Armut und mangelndem Schutz zusammen. Lange Arbeitszeiten und gefährliche Tätigkeiten schadeten Gesundheit und Schulbesuch. Deshalb wurde sie zum Kernproblem der sozialen Frage.',
    ),
  ],
}

const nationalismusWk1: BioBank = {
  quelle: 'Wikipedia: Erster Weltkrieg',
  url: 'https://de.wikipedia.org/wiki/Erster_Weltkrieg',
  conceptPrefix: 'ge:k8:nationalismus-wk1',
  facts: [
    fact(
      'nationalismus',
      'Was ist Nationalismus?',
      'Die Vorstellung, dass die eigene Nation besonders wichtig ist und politisch stark auftreten soll',
      ['Die Ablehnung jeder staatlichen Ordnung', 'Nur Liebe zur Heimat ohne Politik', 'Ausschließlich mittelalterliche Frömmigkeit'],
      'Nationalismus kann integrieren, aber auch ausgrenzen und übersteigern.',
      'Nationalismus betont die Zugehörigkeit zu einer Nation und verbindet sie mit politischen Ansprüchen. Im 19. und frühen 20. Jahrhundert konnte er Einigung fördern, aber auch Feindbilder und Überheblichkeit verstärken. Gerade diese Steigerung war gefährlich.',
      'Nationalismus betont die eigene ___ und ihren politischen Anspruch.',
      ['Nation'],
    ),
    fact(
      'imperialismus',
      'Was wollte der Imperialismus vieler europäischer Mächte?',
      'Macht, Einflussgebiete, Rohstoffe und Prestige in anderen Weltregionen',
      ['Die Auflösung aller Staaten Europas', 'Nur friedlichen Kulturaustausch ohne Herrschaft', 'Die Rückkehr zum Lehnswesen'],
      'Imperialismus verschärfte Konkurrenz der Großmächte.',
      'Im Imperialismus dehnten europäische Mächte ihren Einfluss über Europa hinaus aus. Kolonien, Rohstoffe, Märkte und Prestige spielten dabei eine große Rolle. Diese Konkurrenz erhöhte Spannungen zwischen den Großmächten vor 1914.',
      'Imperialismus zielte auf Macht, Kolonien, Rohstoffe und ___.',
      ['Prestige', 'Einfluss'],
    ),
    fact(
      'buendnisse',
      'Warum waren Bündnisse vor 1914 so bedeutsam?',
      'Weil sie regionale Konflikte leichter zu einer gesamteuropäischen Krise machen konnten',
      ['Weil Bündnisse jeden Krieg unmöglich machten', 'Weil sie nur kulturelle Vereine waren', 'Weil Bündnisse keine militärische Bedeutung hatten'],
      'Sicherheit durch Bündnisse konnte Unsicherheit erhöhen.',
      'Vor dem Ersten Weltkrieg standen sich Bündnissysteme gegenüber. Was der eigenen Sicherheit dienen sollte, verstärkte Misstrauen und Eskalationsgefahr. Dadurch konnte ein lokaler Konflikt schnell viele Staaten hineinziehen.',
      'Bündnisse konnten lokale Konflikte zu einer europäischen ___ machen.',
      ['Krise'],
    ),
    fact(
      'julikrise',
      'Was löste die Julikrise 1914 aus?',
      'Das Attentat von Sarajevo und die anschließende Eskalation zwischen Staaten',
      ['Der Sturz Ludwigs XIV.', 'Die Veröffentlichung der 95 Thesen', 'Die Kapitulation Deutschlands 1945'],
      'Aus einem Attentat wurde eine Kettenreaktion.',
      'Das Attentat von Sarajevo auf den österreichischen Thronfolger war der Ausgangspunkt der Julikrise 1914. Ultimaten, Bündnisse und Mobilmachungen führten dann zu einer raschen Eskalation. So entstand aus einem regionalen Konflikt ein Weltkrieg.',
      'Die Julikrise begann mit dem Attentat von ___.',
      ['Sarajevo'],
    ),
    fact(
      'mobilmachung',
      'Warum verschärfte Mobilmachung die Lage im Sommer 1914?',
      'Weil militärische Vorbereitungen politischen Druck erzeugten und Rückzug erschwerten',
      ['Weil Mobilmachung nur ein Zeitungsbegriff war', 'Weil Armeen damals keine Rolle spielten', 'Weil Diplomatie dadurch einfacher wurde'],
      'Militärische Logik beschleunigte politische Entscheidungen.',
      'Mobilmachung bedeutete nicht bloß Planung, sondern die konkrete Vorbereitung großer Heere auf den Krieg. Sobald mehrere Staaten mobilisierten, wuchs der Zeitdruck enorm. Politische Spielräume wurden dadurch enger und die Eskalation wahrscheinlicher.',
      'Mobilmachung erzeugte Zeitdruck und erschwerte politischen ___.',
      ['Rückzug', 'Ausgleich'],
    ),
    fact(
      'stellungen-krieg-beginn',
      'Warum wurde aus dem Krieg kein kurzer Bewegungskrieg?',
      'Weil neue Waffen, große Heere und Verteidigungssysteme zur Erstarrung an Fronten führten',
      ['Weil es überhaupt keine modernen Waffen gab', 'Weil alle Staaten den Krieg sofort beendeten', 'Weil nur auf See gekämpft wurde'],
      'Der industrielle Krieg war schwer kontrollierbar.',
      'Viele rechneten 1914 mit einem kurzen Krieg. Stattdessen führten Massenheere, Maschinengewehre und befestigte Fronten zu langem Stellungskrieg. Damit zeigte sich, wie sehr moderne Technik den Krieg verändert hatte.',
      'Neue Waffen und Massenheere führten bald zum ___krieg.',
      ['Stellungs', 'Stellungskrieg'],
    ),
    fact(
      'gesamtkrieg',
      'Warum spricht man beim Ersten Weltkrieg oft von einem modernen Massenkrieg?',
      'Weil ganze Gesellschaften, Wirtschaft und Millionen Soldaten einbezogen wurden',
      ['Weil nur kleine Ritterheere kämpften', 'Weil der Krieg kaum Wirtschaft betraf', 'Weil Zivilisten nichts von ihm bemerkten'],
      'Der Krieg erfasste Front und Heimat zugleich.',
      'Der Erste Weltkrieg war kein begrenzter Kabinettskrieg früherer Zeiten. Industrie, Versorgung, Propaganda und Millionenheere banden ganze Gesellschaften ein. Dadurch wurde der Krieg zu einem Massen- und Materialkrieg.',
      'Der Erste Weltkrieg war ein Massen- und ___krieg.',
      ['Material', 'Materialkrieg'],
    ),
    fact(
      'verantwortung',
      'Warum reicht eine einzige Ursache zur Erklärung des Ersten Weltkriegs nicht aus?',
      'Weil Nationalismus, Imperialismus, Bündnisse, Krisen und Entscheidungen zusammenwirkten',
      ['Weil Kriege zufällig ohne Ursachen entstehen', 'Weil nur ein Zeitungsfehler den Krieg auslöste', 'Weil Geschichte immer nur eine Person erklären kann'],
      'Historische Ursachenketten sind meist komplex.',
      'Der Erste Weltkrieg entstand aus mehreren langfristigen und kurzfristigen Faktoren. Nationalismus, imperialistische Konkurrenz, Bündnisse und Fehlentscheidungen verstärkten sich gegenseitig. Historische Erklärung braucht deshalb mehrere Ebenen zugleich.',
      'Der Erste Weltkrieg entstand aus dem ___ mehrerer Faktoren.',
      ['Zusammenwirken', 'Zusammenspiel'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Imperialismus',
      'Wettbewerb um Macht, Kolonien und Einfluss',
      'Imperialismus verschärfte die Konkurrenz der Großmächte. Dadurch stiegen Misstrauen und Konfliktbereitschaft vor 1914.',
    ),
    pair(
      'p2',
      'Julikrise',
      'Eskalation nach dem Attentat von Sarajevo 1914',
      'Aus einem regionalen Auslöser entwickelte sich durch Bündnisse und Mobilmachung eine internationale Krise. Das macht die Julikrise zum Schlüsselereignis.',
    ),
    pair(
      'p3',
      'Bündnissystem',
      'Verflechtung von Staaten in militärischen Lagern',
      'Bündnisse sollten Sicherheit schaffen, steigerten aber zugleich die Eskalationsgefahr. Ein lokaler Konflikt konnte so viele Mächte erfassen.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Der Erste Weltkrieg entstand allein aus dem Attentat von Sarajevo, ohne langfristige Spannungen im Hintergrund.',
      false,
      'Das Attentat war Auslöser, doch Nationalismus, Bündnisse und Imperialismus hatten die Lage bereits zugespitzt.',
      'Historiker unterscheiden zwischen Auslösern und tieferen Ursachen. Das Attentat von Sarajevo setzte die Eskalation in Gang, aber die Spannungslage war schon zuvor hoch. Ohne Imperialismus, Nationalismus und Bündnissysteme ist der Krieg nicht ausreichend erklärt.',
    ),
  ],
}

const kriegstechnik: BioBank = {
  quelle: 'Wikipedia: Stellungskrieg',
  url: 'https://de.wikipedia.org/wiki/Stellungskrieg',
  conceptPrefix: 'ge:k8:kriegstechnik',
  facts: [
    fact(
      'stellungskrieg',
      'Was kennzeichnete den Stellungskrieg im Ersten Weltkrieg?',
      'Tiefe Grabensysteme, feste Fronten und nur geringe Geländegewinne',
      ['Ständige Ritterangriffe ohne Schützengräben', 'Nur Seekämpfe ohne Landfront', 'Friedliche Grenzverhandlungen ohne Waffen'],
      'Der Krieg erstarrte an vielen Frontabschnitten.',
      'Im Stellungskrieg lagen sich Armeen oft monatelang in Schützengräben gegenüber. Frontverläufe änderten sich trotz hoher Verluste nur wenig. Das machte den Krieg langwierig, zermürbend und technisch geprägt.',
      'Der Stellungskrieg war geprägt von Gräben, festen Fronten und geringen ___.',
      ['Geländegewinnen', 'Raumgewinnen'],
    ),
    fact(
      'mg',
      'Warum war das Maschinengewehr so folgenschwer?',
      'Weil es Angriffe auf offenes Gelände extrem verlustreich machte',
      ['Weil es nur zur Signalgebung diente', 'Weil es den Schützengraben überflüssig machte', 'Weil es kaum Feuerkraft besaß'],
      'Neue Feuerkraft stärkte die Verteidigung stark.',
      'Maschinengewehre konnten in kurzer Zeit sehr viele Schüsse abgeben. Dadurch wurden Angriffe über offenes Gelände zu einem hohen Risiko. Die Technik trug wesentlich dazu bei, dass sich Fronten festliefen.',
      'Maschinengewehre machten Angriffe auf offenes Gelände sehr ___.',
      ['verlustreich'],
    ),
    fact(
      'giftgas',
      'Warum galt Giftgas als neue Dimension des Krieges?',
      'Weil es als chemische Waffe massenhaft Leiden verursachte und schwer kontrollierbar war',
      ['Weil es nur Gebäude markierte', 'Weil es völlig ungefährlich für Soldaten war', 'Weil es im Krieg nie eingesetzt wurde'],
      'Chemische Waffen verschärften die Entgrenzung des Krieges.',
      'Giftgas wurde im Ersten Weltkrieg als chemische Waffe eingesetzt und verursachte schwere Verletzungen, Panik und langes Leiden. Schutzmaßnahmen halfen nur begrenzt. Der Einsatz zeigt, wie sehr technische Innovationen auch die Grausamkeit des Krieges steigern konnten.',
      'Giftgas war eine neue Form chemischer ___.',
      ['Kriegsführung', 'Waffe'],
    ),
    fact(
      'panzer',
      'Warum wurden Panzer entwickelt?',
      'Um Schützengräben, Stacheldraht und Maschinengewehrfeuer besser überwinden zu können',
      ['Um Luftschiffe zu ersetzen', 'Um nur auf See eingesetzt zu werden', 'Um Feldpost schneller zuzustellen'],
      'Panzer sollten den festgefahrenen Krieg beweglicher machen.',
      'Panzer wurden entwickelt, um die Sackgasse des Stellungskriegs zu durchbrechen. Sie konnten Gelände, Drahtverhaue und Beschuss besser überwinden als Infanterie allein. Damit begann eine neue Phase motorisierter Kriegsführung.',
      'Panzer sollten Gräben, Stacheldraht und Maschinengewehrfeuer ___ helfen.',
      ['überwinden', 'zu überwinden'],
    ),
    fact(
      'artillerie',
      'Welche Rolle spielte Artillerie im Ersten Weltkrieg?',
      'Sie verursachte enorme Zerstörung und bereitete viele Angriffe vor',
      ['Sie wurde durch Schwerter ersetzt', 'Sie war militärisch bedeutungslos', 'Sie diente nur zum Feiern von Siegen'],
      'Fernwaffen prägten den Materialkrieg entscheidend.',
      'Artillerie war eine der wichtigsten Waffen des Ersten Weltkriegs. Dauerbeschuss zerstörte Stellungen, Landschaften und häufig auch die Psyche der Soldaten. Viele Angriffe wurden durch gewaltige Artillerievorbereitungen eingeleitet.',
      'Artillerie verursachte große Zerstörung und bereitete viele ___ vor.',
      ['Angriffe'],
    ),
    fact(
      'stacheldraht',
      'Warum war Stacheldraht militärisch so wirksam?',
      'Weil er Angreifer bremste und sie leichter unter Beschuss geraten ließ',
      ['Weil er Panzerflugzeuge bauen half', 'Weil er Schützengräben überflüssig machte', 'Weil er nur symbolische Bedeutung hatte'],
      'Kleine technische Mittel konnten große Wirkung entfalten.',
      'Stacheldraht war billig, einfach und im Stellungskrieg äußerst wirksam. Er hielt Angreifer auf und machte sie zu leichten Zielen. Gerade das Zusammenspiel scheinbar einfacher und moderner Waffen prägte die Fronten.',
      'Stacheldraht bremste Angreifer und machte sie leichter zu ___.',
      ['Zielen'],
    ),
    fact(
      'luftkrieg',
      'Was änderte sich mit Flugzeugen und Luftschiffen im Krieg?',
      'Aufklärung und Angriffe erreichten nun auch den Luftraum',
      ['Der Krieg wurde wieder rein lokal', 'Schützengräben verschwanden sofort', 'Nur Diplomaten nutzten Flugzeuge'],
      'Der Krieg dehnte sich technisch auf neue Räume aus.',
      'Flugzeuge und Luftschiffe erweiterten den Krieg auf den Luftraum. Zunächst dienten sie vor allem der Aufklärung, später auch dem Angriff. Damit zeigte sich, wie technisch und räumlich umfassend moderne Kriegsführung wurde.',
      'Mit Flugzeugen erreichte der Krieg auch den ___.',
      ['Luftraum'],
    ),
    fact(
      'materialschlacht',
      'Warum spricht man beim Ersten Weltkrieg von Materialschlacht?',
      'Weil Waffen, Munition, Technik und industrielle Produktion kriegsentscheidend wurden',
      ['Weil nur persönliche Rittertugend zählte', 'Weil Fabriken im Krieg unwichtig waren', 'Weil Waffen knapp und selten blieben'],
      'Industrie und Front waren eng miteinander verbunden.',
      'Im Ersten Weltkrieg entschieden nicht nur Feldherren und Soldaten, sondern auch Fabriken, Nachschub und technische Mittel. Der Krieg verschlang ungeheure Mengen an Material. Deshalb spricht man von einer Materialschlacht moderner Industriegesellschaften.',
      'Materialschlacht meint die kriegsentscheidende Bedeutung von Technik und ___.',
      ['Produktion', 'Material'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Stellungskrieg',
      'Feste Fronten mit Schützengräben und geringem Raumgewinn',
      'Der Stellungskrieg entstand aus dem Zusammenspiel moderner Waffen und großer Heere. Er machte den Krieg lang und verlustreich.',
    ),
    pair(
      'p2',
      'Giftgas',
      'Chemische Waffe mit schwer kontrollierbaren Folgen',
      'Giftgas steht für die technische Entgrenzung des Krieges. Es fügte den Fronten eine besonders grausame Form der Kriegsführung hinzu.',
    ),
    pair(
      'p3',
      'Panzer',
      'Gepanzertes Fahrzeug zum Durchbrechen von Fronten',
      'Panzer sollten helfen, Gräben und Maschinengewehrstellungen zu überwinden. Damit veränderten sie die Kriegsführung langfristig.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Der Stellungskrieg entstand, weil moderne Waffen wie Maschinengewehre und Artillerie die Verteidigung stark begünstigten.',
      true,
      'Gerade diese Waffen machten Frontalangriffe extrem verlustreich und führten zur Frontstarre.',
      'Maschinengewehre, Artillerie und Stacheldraht stärkten die Verteidigung deutlich. Angreifer konnten kaum ohne große Verluste durchbrechen. Darum wurden Schützengräben und feste Fronten zum Kennzeichen des Krieges.',
    ),
  ],
}

const massenmedien: BioBank = {
  quelle: 'Wikipedia: Propaganda im Ersten Weltkrieg',
  url: 'https://de.wikipedia.org/wiki/Propaganda_im_Ersten_Weltkrieg',
  conceptPrefix: 'ge:k8:massenmedien',
  facts: [
    fact(
      'propaganda',
      'Was ist Propaganda im Krieg?',
      'Gezielte Beeinflussung der öffentlichen Meinung zugunsten eigener Kriegsziele',
      ['Neutrale Geschichtsschreibung ohne Absicht', 'Nur private Tagebücher von Soldaten', 'Ausschließlich technische Reparatur von Druckmaschinen'],
      'Propaganda will Stimmungen und Einstellungen lenken.',
      'Propaganda versucht, Menschen von einer bestimmten Sichtweise zu überzeugen. Im Krieg sollte sie Opferbereitschaft stärken, Zweifel schwächen und Feindbilder verbreiten. Massenmedien wurden dafür gezielt eingesetzt.',
      'Propaganda ist die gezielte ___ der öffentlichen Meinung.',
      ['Beeinflussung'],
    ),
    fact(
      'plakate',
      'Warum waren Plakate im Ersten Weltkrieg ein wichtiges Medium?',
      'Weil sie schnell sichtbar waren und Botschaften einfach zuspitzen konnten',
      ['Weil kaum jemand Bilder verstand', 'Weil Plakate nur in Bibliotheken gelesen wurden', 'Weil sie keine emotionalen Wirkungen hatten'],
      'Bildsprache war für Massenmobilisierung besonders wirksam.',
      'Plakate erreichten viele Menschen im öffentlichen Raum. Mit Farben, Symbolen und kurzen Slogans konnten sie Gefühle ansprechen und Feindbilder zuspitzen. Gerade im Krieg war diese einfache Wirkung politisch sehr nützlich.',
      'Plakate waren wirksam, weil sie Botschaften schnell und ___ vermittelten.',
      ['sichtbar', 'zugespitzt'],
    ),
    fact(
      'zensur',
      'Warum setzten Staaten im Krieg Zensur ein?',
      'Um Informationen zu kontrollieren und Kritik oder schlechte Nachrichten zu begrenzen',
      ['Um Presse völlig unabhängig arbeiten zu lassen', 'Um alle Zeitungen abzuschaffen', 'Um wissenschaftliche Debatten über Antike zu fördern'],
      'Informationskontrolle war Teil der Kriegführung.',
      'Im Ersten Weltkrieg kontrollierten viele Staaten Berichte aus dem Krieg. Zensur sollte militärische Geheimnisse schützen, aber auch die öffentliche Stimmung steuern. Dadurch erhielten Menschen oft nur gefilterte Informationen.',
      'Zensur sollte Informationen ___ und Kritik begrenzen.',
      ['kontrollieren'],
    ),
    fact(
      'feindbild',
      'Warum waren Feindbilder in der Kriegspropaganda so wichtig?',
      'Weil sie den Gegner entmenschlichten und die eigene Seite zusammenschweißen sollten',
      ['Weil sie zu mehr Verständnis für den Gegner führten', 'Weil sie militärische Konflikte sofort beendeten', 'Weil sie im Krieg keine Wirkung hatten'],
      'Feindbilder vereinfachen und verschärfen Konflikte.',
      'Kriegspropaganda arbeitet häufig mit vereinfachten Bildern vom Feind. Der Gegner erscheint als Bedrohung, Barbarei oder moralisch minderwertig. Solche Bilder erleichtern Mobilisierung, erschweren aber Verständigung und Frieden.',
      'Feindbilder sollten den Gegner ___ und die eigene Seite einen.',
      ['entmenschlichen'],
    ),
    fact(
      'heimatfront',
      'Warum richtete sich Propaganda nicht nur an Soldaten, sondern auch an die Heimat?',
      'Weil der Krieg von Unterstützung, Arbeit und Durchhaltewillen der Zivilbevölkerung abhing',
      ['Weil Zivilisten im Krieg bedeutungslos waren', 'Weil nur Frontsoldaten Nachrichten lesen konnten', 'Weil Heimat und Krieg nichts miteinander zu tun hatten'],
      'Im Massenkrieg wurde die Heimat zur zweiten Front.',
      'Der Erste Weltkrieg war ein Krieg ganzer Gesellschaften. Produktion, Versorgung und Moral der Bevölkerung waren entscheidend für die Kriegsfähigkeit. Deshalb war die sogenannte Heimatfront ein zentrales Ziel von Propaganda.',
      'Propaganda richtete sich auch an die Heimat, weil der Krieg von ziviler ___ abhing.',
      ['Unterstützung', 'Mitarbeit'],
    ),
    fact(
      'presse',
      'Welche Rolle spielte die Presse im Ersten Weltkrieg?',
      'Sie verbreitete Nachrichten, war aber oft von Zensur und Propaganda beeinflusst',
      ['Sie war völlig unabhängig von jedem Staat', 'Sie bestand nur aus wissenschaftlichen Fachzeitschriften', 'Sie berichtete grundsätzlich nur über Sport'],
      'Presse blieb wichtig, aber nicht neutral.',
      'Zeitungen waren das wichtigste Massenmedium ihrer Zeit. Im Krieg berichteten sie über Front, Heimat und Politik, standen aber vielfach unter Einfluss von Staat und Militär. Dadurch vermischten sich Information, Auswahl und politische Lenkung.',
      'Die Presse verbreitete Nachrichten, stand aber oft unter ___ und Propaganda.',
      ['Zensur'],
    ),
    fact(
      'bildsprache',
      'Warum war Bildsprache für Kriegspropaganda besonders geeignet?',
      'Weil Bilder Gefühle wecken und komplizierte Botschaften einfach darstellen können',
      ['Weil Bilder keine Emotionen auslösen', 'Weil nur Schrift im Krieg verstanden wurde', 'Weil Fotos und Zeichnungen verboten waren'],
      'Emotionen sind für politische Mobilisierung zentral.',
      'Bilder erreichen Menschen oft schneller als lange Texte. In der Kriegspropaganda halfen sie, Stolz, Angst, Hass oder Opferbereitschaft auszulösen. Gerade dadurch konnten Massenmedien politische Einstellungen sehr wirksam formen.',
      'Bilder sind wirksam, weil sie schnell Gefühle ___ können.',
      ['wecken', 'auslösen'],
    ),
    fact(
      'kritik',
      'Warum ist die Analyse von Kriegspropaganda historisch wichtig?',
      'Weil sie zeigt, wie Medien Wahrnehmung lenken und Wirklichkeit vereinfachen können',
      ['Weil Propaganda immer wahrheitsgetreu informiert', 'Weil Medien im Krieg unpolitisch sind', 'Weil historische Bilder keine Quellen darstellen'],
      'Medienkritik gehört zum historischen Lernen.',
      'Wer Kriegspropaganda untersucht, lernt, wie gezielt Medien Stimmungen und Deutungen prägen. Quellen werden dadurch nicht wertlos, aber sie müssen kritisch gelesen werden. Gerade das macht Mediengeschichte für Gegenwart und Geschichte bedeutsam.',
      'Die Analyse von Propaganda zeigt, wie Medien Wahrnehmung ___ können.',
      ['lenken', 'beeinflussen'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Propaganda',
      'Gezielte Lenkung von Meinungen und Stimmungen',
      'Propaganda will nicht nur informieren, sondern Einstellungen formen. Im Krieg diente sie Mobilisierung und Feindbildpflege.',
    ),
    pair(
      'p2',
      'Zensur',
      'Staatliche Kontrolle von Informationen',
      'Zensur begrenzte Berichte und Kritik. Dadurch blieb der öffentliche Blick auf den Krieg oft gefiltert.',
    ),
    pair(
      'p3',
      'Heimatfront',
      'Zivilbevölkerung als wichtiger Teil der Kriegsanstrengung',
      'Heimatfront meint Arbeit, Versorgung und Durchhaltebereitschaft der Bevölkerung. Deshalb wurde auch sie gezielt propagandistisch angesprochen.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Kriegspropaganda im Ersten Weltkrieg richtete sich nur an Soldaten an der Front, nicht an die Bevölkerung zu Hause.',
      false,
      'Auch die Heimatfront sollte durch Medien, Bilder und Sprache mobilisiert werden.',
      'Im Massenkrieg war die Unterstützung der Zivilbevölkerung unverzichtbar. Darum zielte Propaganda auch auf Spenden, Arbeitsmoral und Durchhaltewillen in der Heimat. Front und Heimat waren medial eng verbunden.',
    ),
  ],
}

export const GESCHICHTE_K8_GENERATORS: Record<string, Topic['generate']> = {
  'ge-k8-lb1-einheit-freiheit': bankGenerate(einheitFreiheit),
  'ge-k8-lb2-industrialisierung': bankGenerate(industrialisierung),
  'ge-k8-lb3-kinderarbeit': bankGenerate(kinderarbeit),
  'ge-k8-lb4-nationalismus-wk1': bankGenerate(nationalismusWk1),
  'ge-k8-lbw-kriegstechnik': bankGenerate(kriegstechnik),
  'ge-k8-lbw-massenmedien': bankGenerate(massenmedien),
}
