import { bankGenerate, type BioBank } from './biologieBank'
import type { Topic } from './types'

const fact = (
  concept: string,
  prompt: string,
  answer: string,
  wrong: [string, string, string],
  explanation: string,
  wissen: string,
  gap: string,
  gapAccepted: string[],
) => ({ concept, prompt, answer, wrong, explanation, wissen, gap, gapAccepted })

const pair = (concept: string, term: string, meaning: string, wissen: string) => ({
  concept,
  term,
  meaning,
  wissen,
})

const tf = (
  concept: string,
  statement: string,
  correct: boolean,
  explanation: string,
  wissen: string,
) => ({ concept, statement, correct, explanation, wissen })

const sort = (
  concept: string,
  question: string,
  labels: string[],
  explanation: string,
  wissen: string,
) => ({ concept, question, labels, explanation, wissen })

const neuzeit: BioBank = {
  quelle: 'Wikipedia: Frühe Neuzeit',
  url: 'https://de.wikipedia.org/wiki/Fr%C3%BChe_Neuzeit',
  conceptPrefix: 'ge:k7:neuzeit',
  facts: [
    fact(
      'renaissance',
      'Wofür steht die Renaissance?',
      'Für die Wiederentdeckung antiker Bildungsideale und neue Formen von Kunst und Denken',
      ['Für die Einführung des Lehnswesens', 'Für die Gründung des Völkerbunds', 'Für die Abschaffung aller Städte'],
      'Die Renaissance veränderte das Welt- und Menschenbild.',
      'Die Renaissance begann in Italien und griff auf antike Vorbilder zurück. Kunst, Architektur und Wissenschaft veränderten sich deutlich. Der Mensch und seine Fähigkeiten rückten stärker in den Mittelpunkt als im traditionellen mittelalterlichen Denken.',
      'Die ___ griff auf antike Bildungsideale zurück.',
      ['Renaissance'],
    ),
    fact(
      'humanismus',
      'Was betonte der Humanismus besonders?',
      'Bildung, Sprachen, kritisches Lesen und die Würde des Menschen',
      ['Nur militärische Erziehung von Rittern', 'Ausschließlich klösterliche Abschottung', 'Nur die Herrschaft des Adels über Bauern'],
      'Humanisten wollten Menschen durch Bildung formen.',
      'Der Humanismus war eine Bildungsbewegung der frühen Neuzeit. Humanisten lernten antike Sprachen, lasen Quellen kritisch und glaubten an die Formbarkeit des Menschen durch Bildung. Damit prägten sie Schule, Wissenschaft und Politik.',
      'Der Humanismus betonte besonders ___ und kritisches Lesen.',
      ['Bildung'],
    ),
    fact(
      'buchdruck',
      'Warum war der Buchdruck mit beweglichen Lettern so bedeutsam?',
      'Weil Texte schneller, günstiger und in größerer Zahl verbreitet werden konnten',
      ['Weil Bücher nur noch mündlich erzählt wurden', 'Weil Druck das Lesen unnötig machte', 'Weil nur Könige drucken durften'],
      'Der Buchdruck beschleunigte Wissensverbreitung.',
      'Johannes Gutenberg entwickelte im 15. Jahrhundert den Buchdruck mit beweglichen Metalllettern. Dadurch konnten Texte viel schneller vervielfältigt werden als durch Abschreiben. Das förderte Bildung, religiöse Debatten und die Ausbreitung neuer Ideen.',
      'Der Buchdruck machte die Verbreitung von ___ deutlich schneller.',
      ['Texten', 'Wissen'],
    ),
    fact(
      'kolumbus',
      'Warum gilt 1492 oft als Schlüsseljahr der Neuzeit?',
      'Weil Kolumbus Amerika erreichte und dadurch weltweite Verflechtungen zunahmen',
      ['Weil Rom erst dann gegründet wurde', 'Weil Ludwig XIV. die Magna Carta unterschrieb', 'Weil die Bauernkriege in Sachsen endeten'],
      'Entdeckungsfahrten erweiterten den europäischen Horizont stark.',
      'Mit der Fahrt von Kolumbus 1492 verstärkten sich Kontakte zwischen Europa, Amerika, Afrika und Asien. Diese Verbindungen brachten Handel, Wissen und Machtgewinne, aber auch Eroberung, Gewalt und Ausbeutung. Das macht Entdeckungen historisch ambivalent.',
      '1492 erreichte Kolumbus ___ und veränderte damit den Horizont Europas.',
      ['Amerika'],
    ),
    fact(
      'kompass',
      'Welche technischen Voraussetzungen halfen den Entdeckungsfahrten?',
      'Unter anderem Kompass, verbesserte Karten und seetüchtige Schiffe',
      ['Nur Ritterrüstungen und Burgen', 'Ausschließlich Dampfmaschinen', 'Nur Eisenbahnen und Telegrafen'],
      'Entdeckungsfahrten wurden durch Navigation und Schiffbau erleichtert.',
      'Fernfahrten über den Atlantik wurden durch technische und geografische Kenntnisse begünstigt. Kompass, Karten und neue Schiffstypen wie die Karavelle verbesserten Navigation und Sicherheit. Technik und Wissensdurst wirkten dabei zusammen.',
      'Entdeckungsfahrten wurden durch Kompass, Karten und geeignete ___ erleichtert.',
      ['Schiffe', 'Schiffstypen'],
    ),
    fact(
      'weltbild',
      'Wie veränderte sich in der Neuzeit das Weltbild vieler Europäer?',
      'Es wurde weiter, erforschender und weniger auf den eigenen Nahraum begrenzt',
      ['Es schrumpfte nur auf das Dorfleben', 'Es blieb völlig unverändert seit der Antike', 'Es wurde nur religiöser und ohne Naturbeobachtung'],
      'Neue Erfahrungen förderten ein offeneres Weltbild.',
      'Durch Reisen, Handel, Druck und Wissenschaft veränderte sich das Weltbild vieler Menschen. Fremde Räume und neue Erkenntnisse wurden wichtiger. Das bedeutete nicht, dass alte Vorstellungen verschwanden, aber neue Perspektiven gewannen an Gewicht.',
      'Das Weltbild wurde weiter und stärker auf ___ ausgerichtet.',
      ['Erforschung', 'Erkundung'],
    ),
    fact(
      'da-vinci',
      'Warum gilt Leonardo da Vinci als typische Gestalt der Renaissance?',
      'Weil er Kunst, Naturbeobachtung und technisches Denken verband',
      ['Weil er als Kurfürst Sachsen regierte', 'Weil er die Goldene Bulle verfasste', 'Weil er den Ersten Weltkrieg erklärte'],
      'Leonardo verkörpert das vielseitige Menschenbild der Epoche.',
      'Leonardo da Vinci war Maler, Forscher und Erfinder zugleich. Gerade diese Verbindung von Kunst und Naturstudium macht ihn zu einer Schlüsselfigur der Renaissance. Sie zeigt, wie stark die Epoche an menschliche Fähigkeiten glaubte.',
      'Leonardo da Vinci verband Kunst mit ___ und technischem Denken.',
      ['Naturbeobachtung'],
    ),
    fact(
      'amerika-folgen',
      'Welche Folge hatten die europäischen Entdeckungsfahrten für Amerika?',
      'Sie führten zu Eroberung, Kolonisierung und massiven Umbrüchen für indigene Gesellschaften',
      ['Sie ließen Amerika völlig unverändert', 'Sie beendeten jede Gewalt in Übersee', 'Sie führten sofort zur Gleichberechtigung aller Beteiligten'],
      'Entdeckungen waren für viele Menschen keine reine Erfolgsgeschichte.',
      'Die europäischen Entdeckungsfahrten hatten für indigene Gesellschaften in Amerika tiefgreifende Folgen. Eroberung, Krankheiten, Missionierung und Ausbeutung zerstörten bestehende Lebenswelten vielfach. Deshalb gehören zur Neuzeit nicht nur Fortschritt, sondern auch Gewalt und Herrschaft.',
      'Entdeckungsfahrten brachten in Amerika Kolonisierung und tiefgreifende ___.',
      ['Umbrüche', 'Veränderungen'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Renaissance',
      'Rückgriff auf die Antike in Kunst und Denken',
      'Die Renaissance griff antike Vorbilder auf und verband sie mit neuen künstlerischen Formen. So veränderte sie das Menschenbild der frühen Neuzeit.',
    ),
    pair(
      'p2',
      'Humanismus',
      'Bildungsbewegung mit Schwerpunkt auf Quellen und Sprachen',
      'Humanisten lasen antike Texte kritisch und betonten die Bildung des Menschen. Ihr Einfluss reichte tief in Schule und Wissenschaft.',
    ),
    pair(
      'p3',
      'Buchdruck',
      'Schnelle Vervielfältigung von Texten mit Lettern',
      'Der Buchdruck beschleunigte die Verbreitung von Wissen. Dadurch konnten neue Ideen viel rascher diskutiert werden.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Die Renaissance bedeutete nur, dass Europa im Mittelalter stehen blieb und sich geistig nicht veränderte.',
      false,
      'Gerade die Renaissance steht für neue Formen von Kunst, Bildung und Weltdeutung.',
      'Die Renaissance war eine Epoche kultureller und geistiger Erneuerung. Der Rückgriff auf die Antike verband sich mit neuen Beobachtungen, Forschungen und Ausdrucksformen. Deshalb markiert sie einen wichtigen Übergang zur Neuzeit.',
    ),
  ],
  sorts: [
    sort(
      's1',
      'Ordne grob chronologisch:',
      ['Renaissance und Humanismus', 'Buchdruck', 'Entdeckungsfahrten über den Atlantik'],
      'Alle drei Entwicklungen gehören in die frühe Neuzeit und verstärken sich gegenseitig.',
      'Renaissance, Humanismus, Buchdruck und Entdeckungsfahrten liegen eng beieinander und prägen die frühe Neuzeit. Neue Ideen, neue Medien und neue Räume greifen ineinander.',
    ),
  ],
}

const absolutismus: BioBank = {
  quelle: 'Wikipedia: Absolutismus',
  url: 'https://de.wikipedia.org/wiki/Absolutismus',
  conceptPrefix: 'ge:k7:absolutismus',
  facts: [
    fact(
      'absolutismus',
      'Was versteht man unter Absolutismus?',
      'Eine Herrschaftsform, in der der Monarch seine Macht stark zentralisiert',
      ['Eine direkte Demokratie aller Bürger', 'Die Herrschaft einer mittelalterlichen Zunft', 'Ein Bündnis unabhängiger Stadtstaaten'],
      'Im Absolutismus bündelt der König Macht am Hof und im Staat.',
      'Unter Absolutismus versteht man eine Herrschaftsform der frühen Neuzeit, in der Könige ihre Macht stark konzentrierten. Verwaltung, Heer und Hof wurden enger auf den Monarchen bezogen. In der Wirklichkeit blieb diese Macht dennoch durch Traditionen und Stände begrenzt.',
      'Absolutismus meint stark ___ Herrschaft beim Monarchen.',
      ['zentralisierte', 'gebündelte'],
    ),
    fact(
      'ludwig-xiv',
      'Warum gilt Ludwig XIV. als Symbol des Absolutismus?',
      'Weil er Frankreich lange regierte und den Hof von Versailles zur Machtdemonstration nutzte',
      ['Weil er die Weimarer Verfassung verfasste', 'Weil er die Reformation in Wittenberg auslöste', 'Weil er römischer Konsul der Antike war'],
      'Ludwig XIV. verkörpert höfische Pracht und zentralisierte Herrschaft.',
      'Ludwig XIV. regierte Frankreich im 17. und frühen 18. Jahrhundert. Er machte Versailles zum Mittelpunkt des Hofes und band den Adel an seine Person. Deshalb wird er oft als Muster eines absolutistischen Herrschers dargestellt.',
      'Ludwig XIV. nutzte den Hof von ___ zur Machtdemonstration.',
      ['Versailles'],
    ),
    fact(
      'versailles',
      'Welche politische Funktion hatte Versailles?',
      'Es war Residenz, Kontrollzentrum des Adels und Bühne königlicher Macht',
      ['Es war nur ein Handelslager für Gewürze', 'Es diente als Parlament der englischen Bürger', 'Es war ein Kloster ohne Hofleben'],
      'Der Hofstaat war Teil der Herrschaftsstrategie.',
      'Versailles war weit mehr als ein prunkvolles Schloss. Der Hof regelte Rang, Nähe und Zugang zum König und half so, den Adel zu kontrollieren. Repräsentation war im Absolutismus also selbst ein Mittel der Politik.',
      'Versailles war auch eine Bühne königlicher ___.',
      ['Macht', 'Herrschaft'],
    ),
    fact(
      'stehendes-heer',
      'Warum war ein stehendes Heer für absolutistische Staaten wichtig?',
      'Weil der Monarch damit Kriege führen und seine Herrschaft absichern konnte',
      ['Weil dadurch Parlamente überflüssig wurden', 'Weil Bauern dann keine Steuern zahlten', 'Weil Handel auf dem Meer unnötig wurde'],
      'Heer und Steuern gehörten eng zusammen.',
      'Absolutistische Herrschaft stützte sich auf ein dauerhaft verfügbares Heer. Um dieses zu finanzieren, brauchten Staaten Steuern und Verwaltung. Militär, Bürokratie und Königsmacht verstärkten sich dadurch gegenseitig.',
      'Ein stehendes Heer stärkte Kriegsfähigkeit und ___ des Monarchen.',
      ['Herrschaft'],
    ),
    fact(
      'merkantilismus',
      'Was wollte der Merkantilismus fördern?',
      'Staatlich gelenkte Wirtschaftskraft und Einnahmen des Staates',
      ['Die Abschaffung aller Zölle sofort', 'Nur Selbstversorgung ohne Handel', 'Ausschließlich freie Wahlen im Parlament'],
      'Wirtschaftspolitik sollte den Staat stärken.',
      'Im Merkantilismus griff der Staat gezielt in die Wirtschaft ein. Man wollte Ausfuhr fördern, Einfuhr begrenzen und Manufakturen stärken. Ziel war nicht wirtschaftliche Freiheit an sich, sondern mehr Reichtum und Macht des Staates.',
      'Der Merkantilismus sollte die ___ des Staates erhöhen.',
      ['Einnahmen', 'Wirtschaftskraft'],
    ),
    fact(
      'aufklaerung',
      'Wofür steht die Aufklärung?',
      'Für Vernunft, Kritik und das Prüfen von Herrschaft mit dem Verstand',
      ['Für bedingungslosen Gehorsam ohne Nachdenken', 'Für die Rückkehr zur Leibeigenschaft', 'Für die Herrschaft von Rittern und Burgen'],
      'Die Aufklärung hinterfragte Traditionen und Machtansprüche.',
      'Die Aufklärung war eine geistige Bewegung des 17. und 18. Jahrhunderts. Sie setzte auf Vernunft, Diskussion und Kritik an überlieferten Autoritäten. Dadurch wurden auch Staat, Kirche und Gesellschaft stärker hinterfragt.',
      'Die Aufklärung betonte ___ und Kritik.',
      ['Vernunft'],
    ),
    fact(
      'gewaltenteilung',
      'Welche Idee verband man in der Aufklärung mit Montesquieu?',
      'Die Gewaltenteilung',
      ['Die Alleinherrschaft des Königs', 'Die Rückkehr zum Lehnswesen', 'Die Kreuzzugsidee'],
      'Gewaltenteilung sollte Macht begrenzen.',
      'Montesquieu entwickelte die Vorstellung, staatliche Macht auf verschiedene Gewalten zu verteilen. Gesetzgebung, Regierung und Rechtsprechung sollten sich gegenseitig begrenzen. Diese Idee wurde für moderne Verfassungen sehr wichtig.',
      'Montesquieu verband Aufklärung mit der Idee der ___.',
      ['Gewaltenteilung'],
    ),
    fact(
      'widerspruch',
      'Wie verhielten sich Absolutismus und Aufklärung zueinander?',
      'Sie standen teils im Gegensatz, beeinflussten sich aber in manchen Reformen auch gegenseitig',
      ['Sie waren genau dasselbe', 'Sie hatten keinerlei Berührungspunkte', 'Die Aufklärung wollte nur mehr Hofzeremoniell'],
      'Geistesgeschichte und Herrschaft liefen nicht einfach parallel.',
      'Aufklärung und Absolutismus widersprachen sich oft, weil die Aufklärung Herrschaft kritisch prüfte. Gleichzeitig übernahmen manche Herrscher einzelne Reformideen. Deshalb ist das Verhältnis von absolutistischem Staat und Aufklärung spannungsreich, nicht schlicht.',
      'Zwischen Absolutismus und Aufklärung bestand ein ___ Verhältnis.',
      ['spannungsreiches', 'Spannungsverhältnis'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Absolutismus',
      'Stark zentralisierte Herrschaft des Monarchen',
      'Im Absolutismus bündelte der Monarch viele politische Mittel in seiner Hand. Dennoch blieb seine Macht in der Praxis nie völlig unbegrenzt.',
    ),
    pair(
      'p2',
      'Versailles',
      'Residenz und Machttheater Ludwigs XIV.',
      'Versailles diente der Repräsentation und der Kontrolle des Adels. Hofleben wurde damit Teil politischer Herrschaft.',
    ),
    pair(
      'p3',
      'Aufklärung',
      'Geistige Bewegung von Vernunft und Kritik',
      'Die Aufklärung prüfte Traditionen und Herrschaft mit dem Verstand. Daraus entstanden neue politische Ideen wie Gewaltenteilung und Menschenrechte.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Die Aufklärung bestärkte vor allem die Idee, dass Herrschaft niemals mit Vernunft oder Kritik geprüft werden dürfe.',
      false,
      'Gerade die Aufklärung wollte Herrschaft kritisch mit dem Verstand untersuchen.',
      'Aufklärer forderten, Autoritäten nicht einfach hinzunehmen. Vernunft, Diskussion und Kritik sollten Politik und Gesellschaft prüfen. Darin lag ihr Gegensatz zu rein traditionell oder göttlich begründeter Macht.',
    ),
  ],
}

const alleinherrschaft: BioBank = {
  quelle: 'Wikipedia: Magna Carta',
  url: 'https://de.wikipedia.org/wiki/Magna_Carta',
  conceptPrefix: 'ge:k7:alleinherrschaft',
  facts: [
    fact(
      'magna-carta',
      'Warum ist die Magna Carta von 1215 historisch wichtig?',
      'Weil sie königliche Macht begrenzte und Rechte des Adels festschrieb',
      ['Weil sie Frankreich zur Republik erklärte', 'Weil sie den Buchdruck erfand', 'Weil sie den Ersten Weltkrieg beendete'],
      'Die Magna Carta gilt als frühes Zeichen begrenzter Herrschaft.',
      'Die Magna Carta wurde 1215 dem englischen König Johann abgerungen. Sie beschränkte königliche Willkür und sicherte bestimmten Gruppen Rechte zu. Auch wenn sie noch keine moderne Demokratie schuf, wurde sie später zu einem wichtigen Symbol für Rechtsbindung der Macht.',
      'Die Magna Carta begrenzte die Macht des ___.',
      ['Königs', 'Koenigs'],
    ),
    fact(
      'parlament',
      'Welche Rolle gewann das englische Parlament langfristig?',
      'Es wurde zu einem Organ, das königliche Macht mitbestimmen und begrenzen konnte',
      ['Es diente nur der Hofunterhaltung', 'Es ersetzte jede Rechtsprechung durch Rituale', 'Es war nur eine Zunftversammlung von Kaufleuten'],
      'Parlamentarische Mitwirkung entwickelte sich schrittweise.',
      'Das englische Parlament entstand nicht auf einmal in moderner Form. Über lange Zeit gewann es Mitspracherechte, besonders bei Steuern und Gesetzen. Gerade dadurch wurde die königliche Alleinherrschaft schrittweise eingeschränkt.',
      'Das englische Parlament begrenzte langfristig die ___ des Königs.',
      ['Macht', 'Alleinherrschaft'],
    ),
    fact(
      'glorious-revolution',
      'Was zeigte die Glorious Revolution von 1688/89?',
      'Dass in England die Krone nicht völlig unabhängig vom Parlament regieren konnte',
      ['Dass England zum absolutistischen Musterstaat wurde', 'Dass Parlamente überall abgeschafft wurden', 'Dass Ludwig XIV. König von England wurde'],
      'Die Glorious Revolution stärkte die parlamentarische Ordnung.',
      'Die Glorious Revolution führte in England zu einer stärkeren Bindung der Krone an Recht und Parlament. Die Bill of Rights von 1689 machte deutlich, dass Herrschaft nicht beliebig sein durfte. Damit entstand ein wichtiges Gegenmodell zum Absolutismus.',
      'Die Glorious Revolution stärkte Recht und ___.',
      ['Parlament'],
    ),
    fact(
      'usa',
      'Warum war die Unabhängigkeit der USA für die Frage nach Herrschaft wichtig?',
      'Weil sie Regierung auf Rechte, Verfassung und Zustimmung der Regierten stützte',
      ['Weil sie ein neues Lehnswesen einführte', 'Weil sie den König von Frankreich stärkte', 'Weil sie jede Verfassung ablehnte'],
      'Die USA verbanden Unabhängigkeit mit Verfassungsideen.',
      'Die amerikanische Unabhängigkeitserklärung von 1776 begründete Herrschaft mit Rechten und Zustimmung der Regierten. In der Verfassung der USA wurden Gewaltenteilung und republikanische Ordnung wichtig. Damit entstand ein neues politisches Vorbild für viele Zeitgenossen.',
      'Die USA stützten Herrschaft auf Rechte, Verfassung und die ___ der Regierten.',
      ['Zustimmung'],
    ),
    fact(
      'fr-revolution',
      'Was griff die Französische Revolution gegen die alte Herrschaft an?',
      'Privilegien, Ständegesellschaft und unkontrollierte Monarchie',
      ['Nur den Buchdruck', 'Nur römisches Bürgerrecht der Antike', 'Nur mittelalterliche Stadtmauern'],
      'Die Revolution zielte auf grundlegende politische Veränderung.',
      'Die Französische Revolution von 1789 wandte sich gegen Privilegien des Ancien Régime. Sie stellte die Vorstellung in Frage, dass Herrschaft von Geburt oder Stand abhängen dürfe. Freiheit, Gleichheit und Volkssouveränität wurden dadurch zu zentralen politischen Begriffen.',
      'Die Französische Revolution griff Privilegien und die alte ___ an.',
      ['Ständegesellschaft', 'Monarchie'],
    ),
    fact(
      'bill-of-rights',
      'Wofür steht die englische Bill of Rights von 1689?',
      'Für die Bindung der Krone an Recht und Parlament',
      ['Für das Recht des Königs auf absolute Willkür', 'Für die Abschaffung jeder Volksvertretung', 'Für ein neues Kreuzzugsgesetz'],
      'Die Bill of Rights ordnete Macht verfassungsrechtlich ein.',
      'Die Bill of Rights von 1689 legte fest, dass der englische König nicht ohne Parlament herrschen sollte. Sie stärkte Rechte des Parlaments und begrenzte königliche Eingriffe. Damit wurde Rechtsbindung der Herrschaft deutlich ausgebaut.',
      'Die Bill of Rights band die Krone an Recht und ___.',
      ['Parlament'],
    ),
    fact(
      'verfassung',
      'Was leisten Verfassungen im Kampf gegen Alleinherrschaft?',
      'Sie legen Regeln fest und begrenzen Macht durch Recht',
      ['Sie ersetzen alle Gerichte durch den Hof', 'Sie schaffen automatisch soziale Gleichheit', 'Sie sind nur schöne Texte ohne politische Wirkung'],
      'Verfassungen ordnen Herrschaft und setzen Grenzen.',
      'Verfassungen sind grundlegende Regeln eines Staates. Sie legen fest, wer Macht ausübt und wie diese kontrolliert wird. Gerade dadurch können sie Alleinherrschaft einschränken und Rechte sichern.',
      'Verfassungen begrenzen Macht durch ___.',
      ['Recht'],
    ),
    fact(
      'vergleich',
      'Was verbindet Magna Carta, englisches Parlament, USA und Französische Revolution?',
      'Sie zeigen verschiedene Wege, Macht zu begrenzen und Rechte zu sichern',
      ['Sie alle stärken vorbehaltlos den Absolutismus', 'Sie gehören ausschließlich ins Mittelalter', 'Sie lehnen jede politische Mitwirkung ab'],
      'Herrschaft kann auf unterschiedliche Weise eingeschränkt werden.',
      'Magna Carta, Parlament, amerikanische Verfassung und Französische Revolution stehen nicht für dasselbe Modell. Gemeinsam ist ihnen aber, dass Herrschaft nicht grenzenlos sein soll. Geschichte zeigt hier mehrere Wege zur Begrenzung von Macht.',
      'Die Beispiele zeigen verschiedene Wege zur Begrenzung von ___.',
      ['Macht'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Magna Carta',
      'Frühe Begrenzung königlicher Willkür in England',
      'Die Magna Carta wurde 1215 durchgesetzt und gilt als Symbol rechtsgebundener Herrschaft. Sie schuf noch keine Demokratie, aber setzte Grenzen.',
    ),
    pair(
      'p2',
      'Bill of Rights',
      'Stärkte 1689 das Parlament gegenüber der Krone',
      'Die Bill of Rights baute die englische Verfassungsordnung aus. Sie zeigt, dass Könige nicht schrankenlos regieren konnten.',
    ),
    pair(
      'p3',
      'Volkssouveränität',
      'Idee, dass politische Macht vom Volk ausgeht',
      'Volkssouveränität wurde besonders seit den Revolutionen der Neuzeit wichtig. Sie widerspricht dem Gedanken reiner Alleinherrschaft.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Magna Carta und Bill of Rights sind Beispiele dafür, wie in England königliche Macht begrenzt wurde.',
      true,
      'Beide Texte stehen für die Bindung der Krone an Recht und Mitwirkung anderer Kräfte.',
      'In England entwickelte sich die Begrenzung königlicher Macht über mehrere Jahrhunderte. Magna Carta und Bill of Rights markieren wichtige Stationen dieser Entwicklung. Beide wurden später zu Symbolen verfassungsgebundener Herrschaft.',
    ),
  ],
}

const legitimation: BioBank = {
  quelle: 'Wikipedia: Herrschaftslegitimation',
  url: 'https://de.wikipedia.org/wiki/Legitimit%C3%A4t_(Politik)',
  conceptPrefix: 'ge:k7:legitimation',
  facts: [
    fact(
      'gottesgnadentum',
      'Was bedeutet Gottesgnadentum?',
      'Die Vorstellung, dass Herrscher ihre Macht von Gott erhalten',
      ['Die Idee, dass Macht nur aus Wahlen stammt', 'Die Lehre vom Gewaltenteilungsstaat', 'Das Bürgerrecht der römischen Republik'],
      'Gottesgnadentum legitimiert Herrschaft religiös.',
      'Beim Gottesgnadentum wird Herrschaft religiös begründet. Der Herrscher gilt nicht nur als mächtig, sondern als von Gott eingesetzt. Dadurch wird Widerstand leichter als Angriff auf die göttliche Ordnung dargestellt.',
      'Gottesgnadentum leitet Herrschaft von ___ her.',
      ['Gott'],
    ),
    fact(
      'hobbes',
      'Wie begründete Thomas Hobbes staatliche Herrschaft?',
      'Mit einem Gesellschaftsvertrag zum Schutz vor Unsicherheit und Gewalt',
      ['Mit der Abstammung von Karl dem Großen', 'Nur durch die Macht der Zünfte', 'Ausschließlich durch adelige Geburt'],
      'Hobbes stellte Sicherheit in den Mittelpunkt.',
      'Thomas Hobbes ging davon aus, dass Menschen im Naturzustand in Unsicherheit leben würden. Darum übertragen sie Macht an einen starken Staat, der Frieden sichert. Herrschaft entsteht bei ihm also durch Vertrag, nicht durch göttliche Abstammung.',
      'Hobbes begründete Herrschaft mit einem Gesellschafts___.',
      ['vertrag', 'Vertrag'],
    ),
    fact(
      'locke',
      'Worin unterschied sich John Locke von Hobbes?',
      'Locke betonte stärker Rechte des Einzelnen und das Recht auf Widerstand gegen Machtmissbrauch',
      ['Locke wollte absolute Königsherrschaft ohne Grenzen', 'Locke lehnte Eigentum vollständig ab', 'Locke war gegen jede Form von Parlamenten'],
      'Locke verband Vertrag mit Freiheitsrechten.',
      'John Locke begründete Staat und Regierung ebenfalls mit einem Vertrag, setzte aber stärkere Grenzen. Menschen besitzen nach ihm Rechte wie Leben, Freiheit und Eigentum. Wenn Herrscher diese Rechte verletzen, kann Widerstand legitim sein.',
      'Locke betonte stärker die Rechte des ___ gegen Machtmissbrauch.',
      ['Einzelnen'],
    ),
    fact(
      'rousseau',
      'Was hob Jean-Jacques Rousseau hervor?',
      'Den Gemeinwillen und die politische Selbstbestimmung der Bürger',
      ['Die erbliche Herrschaft des Adels', 'Die Vormacht der Kirche in jedem Staat', 'Nur das Lehnswesen des Mittelalters'],
      'Rousseau dachte Herrschaft von der politischen Gemeinschaft her.',
      'Rousseau fragte, wie Freiheit und politische Ordnung zusammenpassen. Er betonte den Gemeinwillen und die aktive Beteiligung der Bürger an der Gesetzgebung. Herrschaft sollte nach ihm nicht bloß von oben aufgedrückt werden.',
      'Rousseau betonte den Gemeinwillen und die politische ___ der Bürger.',
      ['Selbstbestimmung'],
    ),
    fact(
      'vergleich',
      'Was unterscheidet Gottesgnadentum und Vertragstheorien grundlegend?',
      'Gottesgnadentum leitet Macht von Gott ab, Vertragstheorien von Menschen und ihrer Zustimmung',
      ['Beide erklären Herrschaft nur über Rittertum', 'Beide lehnen jede Begründung von Macht ab', 'Nur Vertragstheorien sind mittelalterliche Kirchenlehren'],
      'Die Quelle der Legitimation verschiebt sich.',
      'Der größte Unterschied liegt in der Begründung von Herrschaft. Beim Gottesgnadentum kommt Legitimation von oben, bei Vertragstheorien von den Menschen selbst. Diese Verschiebung ist ein Kern des politischen Wandels in der Neuzeit.',
      'Vertragstheorien leiten Legitimation von den ___ und ihrer Zustimmung ab.',
      ['Menschen'],
    ),
    fact(
      'widerstand',
      'Wann kann nach Locke Widerstand gegen Herrschaft legitim sein?',
      'Wenn eine Regierung grundlegende Rechte verletzt',
      ['Immer gegen jede Form von Gesetz', 'Nur wenn ein Adeliger es befiehlt', 'Nie unter irgendeiner Bedingung'],
      'Widerstandsrecht soll Freiheit gegen Machtmissbrauch schützen.',
      'Locke sah Regierung als an Rechte gebunden. Wenn Herrscher Freiheit, Leben oder Eigentum zerstören, verlieren sie nach seiner Theorie ihre Legitimation. Daraus ergibt sich die Idee eines begrenzten Widerstandsrechts.',
      'Nach Locke kann bei Verletzung grundlegender Rechte ___ legitim sein.',
      ['Widerstand'],
    ),
    fact(
      'zustimmung',
      'Warum ist die Zustimmung der Regierten in Vertragstheorien so wichtig?',
      'Weil Herrschaft dort als von Menschen geschaffen und gerechtfertigt verstanden wird',
      ['Weil Zustimmung jede Verfassung überflüssig macht', 'Weil nur Priester zustimmen dürfen', 'Weil Macht dann ohne Regeln funktioniert'],
      'Vertragstheorien machen Menschen zu politischen Trägern.',
      'In Vertragstheorien ist Herrschaft nicht einfach naturgegeben. Sie entsteht, weil Menschen Ordnung und Sicherheit wollen und einer politischen Form zustimmen. Darum rückt die Frage nach Rechten, Pflichten und Grenzen der Macht in den Mittelpunkt.',
      'In Vertragstheorien wird Herrschaft durch ___ der Regierten begründet.',
      ['Zustimmung'],
    ),
    fact(
      'laengsschnitt',
      'Warum eignet sich Legitimation gut für einen Längsschnitt?',
      'Weil sich Begründungen von Herrschaft über viele Epochen hinweg vergleichen lassen',
      ['Weil Legitimation nur im 20. Jahrhundert vorkommt', 'Weil alle Herrscher immer gleich legitimiert wurden', 'Weil man dazu keine historischen Quellen braucht'],
      'Der Vergleich zeigt Wandel politischer Grundideen.',
      'Herrschaft wurde in der Geschichte sehr unterschiedlich begründet: religiös, dynastisch, vertraglich oder demokratisch. Gerade ein Längsschnitt macht sichtbar, wie sich diese Begründungen verändern. So erkennt man politische Entwicklung über Epochen hinweg.',
      'Ein Längsschnitt zeigt den Wandel von Herrschafts___.',
      ['legitimationen', 'Legitimationen'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Gottesgnadentum',
      'Religiöse Begründung von Herrschaft durch Gott',
      'Beim Gottesgnadentum wird der Herrscher als von Gott eingesetzt verstanden. So erhält Macht einen sakralen Anspruch.',
    ),
    pair(
      'p2',
      'Hobbes',
      'Vertragstheorie mit Schwerpunkt auf Sicherheit',
      'Hobbes begründet Staat mit dem Wunsch nach Frieden und Ordnung. Sicherheit steht bei ihm im Vordergrund.',
    ),
    pair(
      'p3',
      'Locke',
      'Vertragstheorie mit Rechten und Widerstandsrecht',
      'Locke verbindet Regierung mit Schutz individueller Rechte. Macht bleibt dadurch stärker begrenzt als bei Hobbes.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Vertragstheorien und Gottesgnadentum begründen Herrschaft auf dieselbe Weise.',
      false,
      'Sie unterscheiden sich gerade darin, ob Macht von Gott oder von Menschen und ihrer Zustimmung hergeleitet wird.',
      'Gottesgnadentum und Vertragstheorien setzen an ganz unterschiedlichen Quellen der Legitimation an. Das eine verweist auf göttliche Ordnung, das andere auf menschliche Zustimmung und politische Zwecke. Diese Differenz ist historisch grundlegend.',
    ),
  ],
}

const reformGerechtigkeit: BioBank = {
  quelle: 'Wikipedia: Deutscher Bauernkrieg',
  url: 'https://de.wikipedia.org/wiki/Deutscher_Bauernkrieg',
  conceptPrefix: 'ge:k7:reformation-gerechtigkeit',
  facts: [
    fact(
      'luther',
      'Warum löste Martin Luther eine große religiöse Bewegung aus?',
      'Weil er Missstände der Kirche kritisierte und neue Glaubensakzente setzte',
      ['Weil er Frankreich absolutistisch regierte', 'Weil er die USA gründete', 'Weil er die Goldene Bulle schrieb'],
      'Luthers Kritik wurde durch Druck und Debatten weit verbreitet.',
      'Martin Luther kritisierte kirchliche Missstände wie den Ablasshandel und stellte zentrale Fragen nach Gnade und Glauben. Seine Schriften verbreiteten sich rasch durch den Buchdruck. So wurde aus einer Kritik eine große Reformbewegung.',
      'Luther kritisierte kirchliche ___ und setzte neue Glaubensakzente.',
      ['Missstände'],
    ),
    fact(
      '95-thesen',
      'Wogegen richteten sich Luthers 95 Thesen besonders?',
      'Gegen den Ablasshandel und falsche Heilsversprechen',
      ['Gegen die Magna Carta', 'Gegen das römische Bürgerrecht', 'Gegen die Entdeckung Amerikas'],
      'Die Thesen griffen kirchliche Praxis und Theologie an.',
      'Die 95 Thesen von 1517 richteten sich besonders gegen den Ablasshandel. Luther kritisierte, dass Vergebung nicht gekauft werden könne. Damit stellte er Autorität und Praxis der Kirche öffentlich in Frage.',
      'Die 95 Thesen richteten sich besonders gegen den ___.',
      ['Ablasshandel'],
    ),
    fact(
      'bauernkrieg',
      'Warum beriefen sich viele Bauern im Bauernkrieg auf reformatorische Ideen?',
      'Weil sie hofften, religiöse Erneuerung könne auch mehr Gerechtigkeit im Alltag bringen',
      ['Weil Luther ihnen den Königstitel versprach', 'Weil sie nur für den Papst kämpften', 'Weil sie die Rückkehr zur Leibeigenschaft wollten'],
      'Soziale Fragen verbanden sich mit religiöser Sprache.',
      'Im Bauernkrieg von 1524/25 verbanden viele Bauern soziale Forderungen mit religiösen Argumenten. Sie wollten Abgaben, Frondienste und Ungerechtigkeiten begrenzen. Reformation wurde damit für manche auch zu einer Frage sozialer Gerechtigkeit.',
      'Viele Bauern verbanden Reformation mit Hoffnung auf mehr soziale ___.',
      ['Gerechtigkeit'],
    ),
    fact(
      'zwoelf-artikel',
      'Was waren die Zwölf Artikel?',
      'Eine Sammlung bäuerlicher Forderungen nach Rechten und gerechteren Verhältnissen',
      ['Ein Katalog absolutistischer Hofregeln', 'Die Verfassung der USA', 'Ein Vertrag zwischen Ludwig XIV. und dem Papst'],
      'Die Zwölf Artikel zählen zu den wichtigsten Texten des Bauernkriegs.',
      'Die Zwölf Artikel formulierten Forderungen nach gerechteren Lebensbedingungen, etwa bei Abgaben und Nutzung von Gemeinderechten. Sie zeigen, dass Bauern ihre Anliegen schriftlich und argumentativ darstellten. Damit wurden soziale Konflikte politisch und religiös begründet.',
      'Die Zwölf Artikel sammelten bäuerliche ___ nach gerechteren Verhältnissen.',
      ['Forderungen'],
    ),
    fact(
      'luther-bauern',
      'Wie reagierte Luther auf den Bauernkrieg?',
      'Er wandte sich gegen den gewaltsamen Aufstand der Bauern',
      ['Er führte die Bauernheere persönlich an', 'Er erklärte alle Herren für abgesetzt', 'Er blieb völlig ohne Stellungnahme'],
      'Luthers Haltung enttäuschte viele Hoffnungen auf soziale Reform.',
      'Luther hatte zunächst Verständnis für manche Beschwerden, lehnte aber den gewaltsamen Aufstand ab. In seiner Schrift gegen die Bauern stellte er sich deutlich gegen deren Kriegführung. Das zeigt die Spannungen zwischen religiöser Reform und sozialer Revolte.',
      'Luther wandte sich gegen den ___ Aufstand der Bauern.',
      ['gewaltsamen'],
    ),
    fact(
      'gerechtigkeit',
      'Warum ist der Bauernkrieg ein Beispiel für die Frage nach Gerechtigkeit?',
      'Weil Menschen religiöse Erneuerung mit Forderungen nach gerechteren Lebensverhältnissen verbanden',
      ['Weil es nur um technische Erfindungen ging', 'Weil Gerechtigkeit damals keine Rolle spielte', 'Weil nur Fürsten mitredeten'],
      'Reformation wirkte auch in soziale Konflikte hinein.',
      'Der Bauernkrieg zeigt, dass religiöse Ideen politische und soziale Folgen haben können. Bauern fragten, ob christliche Ordnung auch gerechtere Lebensverhältnisse bedeuten müsse. Gerade deshalb ist das Thema mehr als reine Kirchengeschichte.',
      'Der Bauernkrieg verbindet Religion mit sozialer ___.',
      ['Gerechtigkeit'],
    ),
    fact(
      'gewalt',
      'Was zeigt der Bauernkrieg über politische Veränderung?',
      'Dass Reformhoffnungen in gewaltsame Konflikte umschlagen können',
      ['Dass jede Reform automatisch friedlich verläuft', 'Dass Bauern immer erfolgreich siegen', 'Dass Fürsten sofort auf alle Forderungen eingehen'],
      'Gesellschaftlicher Wandel ist oft umkämpft.',
      'Der Bauernkrieg macht sichtbar, wie schnell Hoffnungen auf Veränderung in Gewalt umschlagen können. Unterschiedliche Interessen von Bauern, Fürsten und Reformatoren prallten hart aufeinander. Wandel verlief deshalb nicht gradlinig, sondern konfliktreich.',
      'Der Bauernkrieg zeigt, dass Reformhoffnungen in ___ umschlagen können.',
      ['Gewalt', 'Konflikte'],
    ),
    fact(
      'folge',
      'Welche unmittelbare Folge hatte der Bauernkrieg für viele Bauern?',
      'Sie wurden militärisch besiegt und ihre Lage verbesserte sich zunächst kaum',
      ['Sie erhielten sofort allgemeines Wahlrecht', 'Sie wurden alle zu Stadtbürgern', 'Sie setzten europaweit eine Republik durch'],
      'Die Niederlage beendete den Konflikt nicht als Erinnerung.',
      'Die Bauernheere wurden 1525 militärisch geschlagen. Für viele Bauern brachte das zunächst keine grundlegende Verbesserung ihrer Lage. Dennoch blieb der Bauernkrieg ein wichtiges Erinnerungszeichen für soziale Konflikte und Gerechtigkeitsfragen.',
      'Viele Bauern wurden 1525 militärisch ___.',
      ['besiegt'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      '95 Thesen',
      'Luthers Kritik am Ablasshandel von 1517',
      'Die 95 Thesen griffen den Ablasshandel an und machten kirchliche Missstände öffentlich. Sie wurden zum Ausgangspunkt der Reformation.',
    ),
    pair(
      'p2',
      'Zwölf Artikel',
      'Schriftliche Forderungen der Bauern im Bauernkrieg',
      'Die Zwölf Artikel formulierten soziale und wirtschaftliche Anliegen der Bauern. Sie verbinden religiöse Sprache mit Gerechtigkeitsforderungen.',
    ),
    pair(
      'p3',
      'Bauernkrieg',
      'Großer Aufstand von 1524/25 im Zeichen sozialer und religiöser Konflikte',
      'Im Bauernkrieg trafen Erwartungen an Reformation und soziale Wirklichkeit hart aufeinander. Das macht ihn zu einem Schlüsselthema der Epoche.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Der Bauernkrieg hatte nur religiöse Ursachen und nichts mit sozialen Belastungen zu tun.',
      false,
      'Soziale Forderungen und Erfahrungen von Ungerechtigkeit spielten eine zentrale Rolle.',
      'Die Bauern beriefen sich zwar auf religiöse Argumente, kämpften aber auch gegen Abgaben, Frondienste und rechtliche Benachteiligung. Gerade diese Verbindung macht den Bauernkrieg historisch so bedeutsam. Reformation und soziale Frage griffen ineinander.',
    ),
  ],
}

const reformSachsen: BioBank = {
  quelle: 'Wikipedia: Wittenberg',
  url: 'https://de.wikipedia.org/wiki/Wittenberg',
  conceptPrefix: 'ge:k7:reformation-sachsen',
  facts: [
    fact(
      'wittenberg',
      'Warum ist Wittenberg für die Reformation besonders wichtig?',
      'Weil Luther dort wirkte und die Stadt zu einem Zentrum der Bewegung wurde',
      ['Weil dort Ludwig XIV. residierte', 'Weil Wittenberg die Magna Carta ausstellte', 'Weil dort der Erste Weltkrieg begann'],
      'Wittenberg wurde zum Erinnerungsort der Reformation.',
      'Wittenberg war der Wirkungsort Martin Luthers und anderer Reformatoren. Universität, Druck und fürstlicher Schutz machten die Stadt zu einem Zentrum der Reformation. Darum besitzt sie bis heute große symbolische Bedeutung.',
      'Wittenberg wurde zu einem Zentrum der ___.',
      ['Reformation'],
    ),
    fact(
      'friedrich-weise',
      'Welche Rolle spielte Kurfürst Friedrich der Weise?',
      'Er schützte Luther politisch und stärkte damit die Reformation in Sachsen',
      ['Er verurteilte Luther als Sultan', 'Er gründete den Jesuitenorden', 'Er führte den Bauernkrieg gegen die Fürsten an'],
      'Fürstenschutz war für die Reformation entscheidend.',
      'Kurfürst Friedrich der Weise unterstützte Luther nicht in allen theologischen Fragen, schützte ihn aber politisch. Ohne diesen Rückhalt wäre Luthers Weg sehr viel gefährlicher gewesen. Sachsen wurde dadurch zu einem Kernraum der Reformation.',
      'Friedrich der Weise schützte Luther vor allem ___.',
      ['politisch'],
    ),
    fact(
      'wartburg',
      'Warum ist die Zeit auf der Wartburg für die Reformation bedeutsam?',
      'Weil Luther dort das Neue Testament ins Deutsche übersetzte',
      ['Weil dort die Goldene Bulle beschlossen wurde', 'Weil dort die Sorben siedelten', 'Weil dort Versailles errichtet wurde'],
      'Die Bibelübersetzung stärkte Sprache und Glaubenszugang.',
      'Während seines Aufenthalts auf der Wartburg übersetzte Luther das Neue Testament ins Deutsche. Dadurch wurde die Bibel für viele Menschen zugänglicher. Zugleich wirkte die Übersetzung prägend auf die deutsche Schriftsprache.',
      'Auf der Wartburg übersetzte Luther das Neue Testament ins ___.',
      ['Deutsche', 'Deutsch'],
    ),
    fact(
      'universitaet',
      'Warum war die Universität Wittenberg für die Reformation wichtig?',
      'Weil dort gelehrt, diskutiert und reformatorische Ideen verbreitet wurden',
      ['Weil Universitäten damals nur Ritter ausbildeten', 'Weil dort keinerlei Texte gedruckt wurden', 'Weil Bildung für die Reformation unwichtig war'],
      'Universitäten halfen, Ideen dauerhaft zu verbreiten.',
      'Die Universität Wittenberg war ein Zentrum von Lehre und Debatte. Dort wurden reformatorische Gedanken ausgearbeitet, diskutiert und an Studenten weitergegeben. Bildung und Öffentlichkeit verstärkten so die Wirkung der Reformation.',
      'Die Universität half, reformatorische Ideen zu ___.',
      ['verbreiten'],
    ),
    fact(
      'druck',
      'Warum spielte der Buchdruck gerade in Sachsen für die Reformation eine große Rolle?',
      'Weil Schriften Luthers schnell vervielfältigt und verbreitet werden konnten',
      ['Weil dadurch alle Klöster sofort verschwanden', 'Weil nur Fürsten lesen durften', 'Weil Druck handschriftliche Briefe verbot'],
      'Druck machte die Reformation zu einer Massenbewegung.',
      'Ohne den Buchdruck hätte sich die Reformation viel langsamer verbreitet. Flugschriften, Predigten und Bibeltexte konnten nun schnell gedruckt werden. Sachsen wurde dadurch nicht nur politisch, sondern auch medial zu einem Kernland der Bewegung.',
      'Der Buchdruck machte die Verbreitung von Luthers ___ schneller.',
      ['Schriften'],
    ),
    fact(
      'kursachsen',
      'Warum war Kursachsen für die Reformation so bedeutsam?',
      'Weil dort ein politisch starkes Territorium die Bewegung trug und schützte',
      ['Weil Kursachsen außerhalb des Reiches lag', 'Weil dort nie Fürsten herrschten', 'Weil nur Bauern ohne Städte lebten'],
      'Reformation brauchte politische Räume und Schutz.',
      'Kursachsen war ein wichtiges Territorium im Heiligen Römischen Reich. Wenn ein Kurfürst reformatorische Entwicklungen zuließ oder schützte, wirkte das weit über die Region hinaus. Darum wurde Sachsen zu einem Kernland der Reformation.',
      'Kursachsen war wichtig, weil es der Reformation politischen ___ bot.',
      ['Schutz', 'Rückhalt'],
    ),
    fact(
      'erinnerungsort',
      'Warum sind Wittenberg und andere Reformationsorte bis heute bedeutend?',
      'Weil sie historische Erinnerung an religiösen Wandel und politische Entscheidungen bündeln',
      ['Weil dort heute keine Geschichte mehr sichtbar ist', 'Weil sie nur touristische Erfindungen sind', 'Weil Erinnerungsorte keine Quellen darstellen'],
      'Orte können Geschichte dauerhaft verkörpern.',
      'Reformationsorte wie Wittenberg sind Erinnerungsorte, weil an ihnen entscheidende Entwicklungen festgemacht werden. Gebäude, Kirchen und Museen machen Geschichte sichtbar. So bleibt die Reformation im öffentlichen Gedächtnis präsent.',
      'Reformationsorte bündeln historische ___.',
      ['Erinnerung'],
    ),
    fact(
      'kernland',
      'Was meint die Aussage, Sachsen sei ein Kernland der Reformation?',
      'Dass von dort wichtige Impulse, Akteure und Schutzräume für die Bewegung ausgingen',
      ['Dass die Reformation nur in Sachsen stattfand', 'Dass andere Regionen keinerlei Rolle spielten', 'Dass Sachsen damals unabhängig von Europa war'],
      'Ein Kernland ist wichtig, aber nicht alleiniger Schauplatz.',
      'Sachsen war für die Reformation besonders bedeutend, weil dort wichtige Personen wirkten und politische Schutzräume entstanden. Das heißt aber nicht, dass nur dort reformiert wurde. Vielmehr verband Sachsen lokale Ereignisse mit europäischer Wirkung.',
      'Ein Kernland liefert wichtige Impulse und ___ für eine Bewegung.',
      ['Schutzräume', 'Rückhalt'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Wittenberg',
      'Zentrum der Reformation in Kursachsen',
      'Wittenberg verband Universität, Druck und reformatorische Akteure. Dadurch wurde die Stadt zu einem zentralen Erinnerungsort.',
    ),
    pair(
      'p2',
      'Friedrich der Weise',
      'Kurfürst, der Luther politisch schützte',
      'Fürstlicher Schutz war für die Reformation entscheidend. Friedrich der Weise gab Luther einen wichtigen Rückhalt.',
    ),
    pair(
      'p3',
      'Wartburgübersetzung',
      'Luthers Übertragung des Neuen Testaments ins Deutsche',
      'Die Übersetzung machte biblische Texte zugänglicher und wirkte sprachprägend. Sie gehört zu den bekanntesten Leistungen der Reformation.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Sachsen gilt als Kernland der Reformation, weil dort nur theologische Texte wichtig waren, nicht aber Fürsten und Druck.',
      false,
      'Gerade Fürstenschutz, Universität und Buchdruck machten Sachsen so bedeutsam.',
      'Theologische Ideen allein erklären den Erfolg der Reformation nicht. In Sachsen kamen politische Unterstützung, mediale Verbreitung und Bildungsorte zusammen. Diese Verbindung machte die Region besonders wirksam.',
    ),
  ],
}

const reformKatholisch: BioBank = {
  quelle: 'Wikipedia: Konzil von Trient',
  url: 'https://de.wikipedia.org/wiki/Konzil_von_Trient',
  conceptPrefix: 'ge:k7:reformation-katholisch',
  facts: [
    fact(
      'trient',
      'Was war das Konzil von Trient?',
      'Eine katholische Kirchenversammlung zur Reform und Klärung des Glaubens',
      ['Ein englisches Parlament gegen den König', 'Eine Bauernversammlung in Memmingen', 'Eine antike Philosophenschule in Athen'],
      'Das Konzil reagierte auf Herausforderungen der Reformation.',
      'Das Konzil von Trient tagte im 16. Jahrhundert und war eine zentrale Antwort der katholischen Kirche auf die Reformation. Es klärte Lehre und forderte Reformen im kirchlichen Leben. Dadurch prägte es die katholische Kirche über Jahrhunderte.',
      'Das Konzil von Trient war eine katholische ___ zur Reform der Kirche.',
      ['Kirchenversammlung'],
    ),
    fact(
      'katholische-reform',
      'Was meint "katholische Reform" oder Gegenreformation?',
      'Die Erneuerung und Stärkung der katholischen Kirche als Reaktion auf die Reformation',
      ['Die Abschaffung aller Klöster in Europa', 'Die Einführung des Gottesgnadentums in England', 'Die Gründung des Völkerbunds'],
      'Katholische Reform war mehr als bloßer Widerstand.',
      'Die katholische Reform bestand nicht nur aus Abwehr gegen Protestanten. Sie umfasste auch innere Erneuerung, bessere Ausbildung des Klerus und strengere Kirchenordnung. Deshalb spricht man häufig lieber von katholischer Reform als nur von Gegenreformation.',
      'Katholische Reform bedeutete Erneuerung und ___ der Kirche.',
      ['Stärkung'],
    ),
    fact(
      'jesuiten',
      'Welche Rolle spielte der Jesuitenorden?',
      'Er wirkte in Bildung, Mission und Stärkung der katholischen Kirche',
      ['Er führte als Ritterorden die Kreuzzüge des Mittelalters weiter', 'Er war nur eine Bauernbewegung', 'Er löste die Französische Revolution aus'],
      'Jesuiten wurden zu einem wichtigen Träger katholischer Reform.',
      'Der Jesuitenorden wurde im 16. Jahrhundert gegründet und gewann rasch Einfluss. Er engagierte sich in Schulen, Mission und Seelsorge. Dadurch trug er wesentlich dazu bei, die katholische Kirche zu festigen und neu auszurichten.',
      'Die Jesuiten wirkten besonders in Bildung, Mission und ___.',
      ['Seelsorge'],
    ),
    fact(
      'priesterbildung',
      'Warum war bessere Ausbildung der Priester ein Ziel der katholischen Reform?',
      'Weil Bildung und Disziplin Missstände verringern und Glaubensvermittlung stärken sollten',
      ['Weil Priester fortan nur Ritter sein sollten', 'Weil Bildung in der Kirche verboten wurde', 'Weil man alle Klöster sofort schließen wollte'],
      'Reform sollte den Alltag der Kirche verbessern.',
      'Ein wichtiges Anliegen der katholischen Reform war die bessere Ausbildung des Klerus. Seminare und klare Regeln sollten Seelsorge und Glaubensunterweisung verbessern. Damit reagierte die Kirche auch auf frühere Missstände.',
      'Die katholische Reform wollte die ___ der Priester verbessern.',
      ['Ausbildung'],
    ),
    fact(
      'barock',
      'Wie hing der Barock oft mit der katholischen Reform zusammen?',
      'Prunkvolle Kunst und Kirchen sollten Glauben sichtbar und eindrucksvoll machen',
      ['Der Barock lehnte jede Kirche ab', 'Barock war nur ein Bauernwerkzeug', 'Er gehörte ausschließlich zur Antike'],
      'Kunst wurde gezielt für religiöse Wirkung genutzt.',
      'Im Barock nutzte die katholische Kirche Kunst, Musik und Architektur besonders eindrucksvoll. Prachtvolle Kirchenräume sollten Glauben erfahrbar machen und Menschen ansprechen. Damit wurde Kultur Teil religiöser Erneuerung.',
      'Im Barock sollte Kunst den ___ eindrucksvoll sichtbar machen.',
      ['Glauben'],
    ),
    fact(
      'bekenntnisse',
      'Welche Folge hatte die Reformation langfristig für Europa?',
      'Europa blieb konfessionell gespalten in katholische und protestantische Räume',
      ['Alle Christen wurden sofort wieder eine einzige Kirche', 'Konfession spielte keine Rolle mehr', 'Nur Sachsen blieb religiös verschieden'],
      'Die Glaubensspaltung prägte Politik und Gesellschaft langfristig.',
      'Nach Reformation und katholischer Reform blieb Europa konfessionell geteilt. In vielen Regionen bestimmten katholische oder protestantische Mehrheiten Politik, Schule und Alltag. Diese Spaltung wirkte über Jahrhunderte weiter.',
      'Europa blieb langfristig konfessionell ___.',
      ['gespalten'],
    ),
    fact(
      'trient-lehre',
      'Was tat das Konzil von Trient mit katholischer Lehre?',
      'Es bestätigte zentrale Lehren und grenzte sie gegenüber protestantischen Positionen ab',
      ['Es übernahm vollständig Luthers Lehre', 'Es verbot jede Sakramentenlehre', 'Es erklärte alle Unterschiede für unwichtig'],
      'Trient schuf Klarheit und Abgrenzung.',
      'Das Konzil von Trient bestätigte zentrale katholische Lehren und präzisierte sie. Zugleich grenzte es sich bewusst gegen protestantische Positionen ab. So verband sich innere Reform mit deutlicher konfessioneller Profilbildung.',
      'Trient bestätigte katholische Lehren und ___ sie gegenüber protestantischen Positionen ab.',
      ['grenzte'],
    ),
    fact(
      'schulen',
      'Warum waren Schulen für die katholische Reform wichtig?',
      'Weil Bildung helfen sollte, Glauben zu vermitteln und die Kirche zu stärken',
      ['Weil Religion von nun an ohne Wissen auskommen sollte', 'Weil nur Adlige lesen lernen durften', 'Weil Schulen durch Ritterburgen ersetzt wurden'],
      'Bildung war ein zentrales Feld konfessioneller Prägung.',
      'Schulen waren in der konfessionellen Zeit wichtig, weil dort Wissen und Glaubensvorstellungen weitergegeben wurden. Besonders Jesuiten gründeten und leiteten viele Bildungseinrichtungen. So wurde Erziehung ein zentrales Mittel religiöser Festigung.',
      'Schulen halfen, Glauben zu vermitteln und die Kirche zu ___.',
      ['stärken'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Konzil von Trient',
      'Katholische Kirchenversammlung zur Reform und Lehre',
      'Trient reagierte auf die Reformation und ordnete die katholische Kirche neu. Es verband innere Reform mit klarer Abgrenzung.',
    ),
    pair(
      'p2',
      'Jesuiten',
      'Orden mit großer Bedeutung für Bildung und Mission',
      'Die Jesuiten wirkten stark in Schulen und Seelsorge. So wurden sie zu wichtigen Trägern katholischer Reform.',
    ),
    pair(
      'p3',
      'katholische Reform',
      'Erneuerung der katholischen Kirche im 16. Jahrhundert',
      'Katholische Reform umfasste Disziplin, Ausbildung und Lehre. Sie war also mehr als nur Abwehr gegen Protestanten.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Die katholische Reform bestand nur darin, jede Veränderung abzulehnen und nichts in der Kirche zu verbessern.',
      false,
      'Sie umfasste auch echte Erneuerung wie bessere Priesterausbildung und neue Bildungsarbeit.',
      'Katholische Reform bedeutete nicht bloß starre Abwehr. Kirche und Orden bemühten sich auch um bessere Bildung, Disziplin und Glaubensvermittlung. Gerade das macht die Epoche komplexer als das Schlagwort Gegenreformation vermuten lässt.',
    ),
  ],
}

export const GESCHICHTE_K7_GENERATORS: Record<string, Topic['generate']> = {
  'ge-k7-lb1-neuzeit': bankGenerate(neuzeit),
  'ge-k7-lb2-absolutismus': bankGenerate(absolutismus),
  'ge-k7-lb3-alleinherrschaft': bankGenerate(alleinherrschaft),
  'ge-k7-lb4-legitimation': bankGenerate(legitimation),
  'ge-k7-lbw-reformation-gerechtigkeit': bankGenerate(reformGerechtigkeit),
  'ge-k7-lbw-reformation-sachsen': bankGenerate(reformSachsen),
  'ge-k7-lbw-reformation-katholisch': bankGenerate(reformKatholisch),
}
