import { bankGenerate, type BioBank } from './biologieBank'
import type { Topic } from './types'

const fact = (
  concept: string,
  prompt: string,
  answer: string,
  wrong: [string, string, string],
  explanation: string,
  wissen: string,
  gap: string,
  gapAccepted: string[],
) => ({ concept, prompt, answer, wrong, explanation, wissen, gap, gapAccepted })

const pair = (concept: string, term: string, meaning: string, wissen: string) => ({
  concept,
  term,
  meaning,
  wissen,
})

const tf = (
  concept: string,
  statement: string,
  correct: boolean,
  explanation: string,
  wissen: string,
) => ({ concept, statement, correct, explanation, wissen })

const usaUdssr: BioBank = {
  quelle: 'Wikipedia: Kalter Krieg',
  url: 'https://de.wikipedia.org/wiki/Kalter_Krieg',
  conceptPrefix: 'ge:k10:usa-udssr',
  facts: [
    fact(
      'kalter-krieg',
      'Warum nennt man den Konflikt zwischen USA und UdSSR "Kalter Krieg"?',
      'Weil beide Supermächte gegeneinanderstanden, ohne direkt einen großen Krieg gegeneinander zu führen',
      ['Weil nur in kalten Regionen gekämpft wurde', 'Weil es keinerlei Spannungen gab', 'Weil der Konflikt im Mittelalter stattfand'],
      'Der Konflikt blieb global gefährlich, auch ohne direkten Weltkrieg zwischen beiden.',
      'Der Kalte Krieg war ein weltweiter Konflikt zwischen zwei Machtblöcken nach 1945. USA und UdSSR bekämpften sich politisch, wirtschaftlich, militärisch und ideologisch, ohne direkt einen großen Krieg gegeneinander zu führen. Gerade die atomare Abschreckung machte die Lage dauerhaft gefährlich.',
      'Man spricht von Kaltem Krieg, weil es keinen direkten großen Krieg zwischen den ___ gab.',
      ['Supermächten', 'USA und UdSSR'],
    ),
    fact(
      'bloecke',
      'Was meint die Blockbildung im Kalten Krieg?',
      'Die politische und militärische Aufteilung vieler Staaten in ein westliches und ein östliches Lager',
      ['Die Auflösung aller Bündnisse nach 1945', 'Nur die Teilung einer einzelnen Stadt', 'Eine rein wirtschaftliche Reform in den USA'],
      'Blockbildung strukturierte die internationale Ordnung nach 1945.',
      'Nach dem Zweiten Weltkrieg entstanden zwei große Machtblöcke. Viele Staaten orientierten sich politisch, wirtschaftlich und militärisch an den USA oder an der UdSSR. Dadurch wurde die Weltordnung stark bipolar geprägt.',
      'Blockbildung meint die Aufteilung in ein westliches und ein ___ Lager.',
      ['östliches', 'oestliches'],
    ),
    fact(
      'nato-warschauer-pakt',
      'Warum waren NATO und Warschauer Pakt wichtig?',
      'Weil sie die militärische Organisation der beiden Machtblöcke verkörperten',
      ['Weil sie die deutsche Wiedervereinigung sofort herbeiführten', 'Weil sie nur kulturelle Austauschprogramme waren', 'Weil sie die Atomwaffen abschafften'],
      'Bündnisse machten die Blockkonfrontation sichtbar.',
      'Die NATO und der Warschauer Pakt standen für die militärische Organisation der beiden Lager. Sie banden Staaten an gemeinsame Sicherheits- und Kriegsplanungen. Damit wurde der Kalte Krieg institutionell und militärisch abgesichert.',
      'NATO und Warschauer Pakt verkörperten die militärische ___ der Blöcke.',
      ['Organisation'],
    ),
    fact(
      'abschreckung',
      'Was meint atomare Abschreckung?',
      'Die Drohung mit verheerender nuklearer Gegenreaktion sollte einen Angriff verhindern',
      ['Die friedliche Nutzung von Kernkraftwerken', 'Die planmäßige Abrüstung aller Staaten', 'Den Verzicht auf jede militärische Planung'],
      'Abschreckung beruhte auf der Gefahr gegenseitiger Vernichtung.',
      'Im Kalten Krieg besaßen beide Supermächte Atomwaffen. Die Vorstellung, dass ein Angriff zur gegenseitigen Vernichtung führen könnte, sollte Krieg verhindern. Diese Logik der Abschreckung hielt Frieden, schuf aber dauernde Angst.',
      'Atomare Abschreckung sollte einen Angriff durch die Drohung mit ___ verhindern.',
      ['Gegenvernichtung', 'Gegenreaktion', 'Vernichtung'],
    ),
    fact(
      'kuba',
      'Warum war die Kubakrise 1962 so gefährlich?',
      'Weil die Stationierung sowjetischer Raketen auf Kuba die Welt an den Rand eines Atomkriegs brachte',
      ['Weil dort der Erste Weltkrieg begann', 'Weil Kuba der NATO beitrat', 'Weil alle Atomwaffen in Europa sofort zerstört wurden'],
      'Die Krise zeigte die extreme Zuspitzung des Kalten Krieges.',
      'In der Kubakrise standen die USA und die UdSSR kurz vor einer militärischen Eskalation. Sowjetische Raketen auf Kuba und amerikanischer Druck erhöhten das Risiko eines Atomkriegs drastisch. Die Krise gilt deshalb als einer der gefährlichsten Momente des 20. Jahrhunderts.',
      'Die Kubakrise brachte die Welt an den Rand eines ___.',
      ['Atomkriegs', 'Atomkrieges'],
    ),
    fact(
      'wettruesten',
      'Was bedeutet Wettrüsten?',
      'Dass rivalisierende Staaten ihre Waffenbestände immer weiter ausbauen, um überlegen oder sicher zu sein',
      ['Dass Staaten gemeinsam abrüsten', 'Dass nur Sportwettkämpfe stattfinden', 'Dass Waffen im Krieg keine Rolle mehr spielen'],
      'Wettrüsten erhöhte Kosten und Bedrohungsgefühl.',
      'Im Kalten Krieg versuchten die Supermächte, militärisch nicht zurückzufallen. So entstand ein Wettrüsten mit immer neuen Waffen und Systemen. Sicherheit wurde gesucht, zugleich wuchs das Gefühl ständiger Gefahr.',
      'Wettrüsten meint den ständigen Ausbau von ___ auf beiden Seiten.',
      ['Waffen', 'Rüstung'],
    ),
    fact(
      'stellvertreter',
      'Warum spricht man im Kalten Krieg von Stellvertreterkonflikten?',
      'Weil Auseinandersetzungen oft in anderen Regionen stattfanden, während die Supermächte indirekt beteiligt waren',
      ['Weil die USA und UdSSR nie irgendeinen Einfluss außerhalb Europas hatten', 'Weil alle Konflikte rein wirtschaftlich waren', 'Weil nur neutrale Staaten gegeneinander kämpften'],
      'Viele Krisen wurden global ausgetragen.',
      'Die USA und die UdSSR vermieden meist den direkten Krieg gegeneinander. Stattdessen unterstützten sie unterschiedliche Seiten in Konflikten in Asien, Afrika oder Lateinamerika. So wurde der Kalte Krieg zu einem globalen Stellvertreterkonflikt.',
      'Stellvertreterkonflikte fanden oft in anderen ___ statt.',
      ['Regionen', 'Weltregionen'],
    ),
    fact(
      'entspannung',
      'Was meint Entspannungspolitik im Kalten Krieg?',
      'Versuche, Konflikte zu begrenzen und Verständigung trotz Gegensätzen zu ermöglichen',
      ['Die Auflösung aller politischen Unterschiede', 'Die sofortige Vereinigung beider Machtblöcke', 'Den Verzicht auf jede Diplomatie'],
      'Auch im Kalten Krieg gab es Phasen bewusster Entschärfung.',
      'Entspannungspolitik suchte nicht das Ende aller Gegensätze, sondern die Begrenzung der Gefahr. Verträge, Gespräche und Rüstungskontrolle sollten das Risiko eines Krieges verringern. Gerade nach der Kubakrise gewann dieser Gedanke an Bedeutung.',
      'Entspannungspolitik sollte Gegensätze begrenzen und ___ ermöglichen.',
      ['Verständigung', 'Verstaendigung'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'Kalter Krieg',
      'Systemkonflikt zwischen USA und UdSSR nach 1945',
      'Der Kalte Krieg prägte Politik, Militär und Ideologie weltweit. Seine Gefahr lag gerade im Nebeneinander von Nichtkrieg und ständiger Eskalationsdrohung.',
    ),
    pair(
      'p2',
      'Kubakrise',
      'Krise von 1962 mit akuter Atomkriegsgefahr',
      'Die Kubakrise gilt als einer der gefährlichsten Momente des Kalten Krieges. Sie machte die Risiken der Abschreckung deutlich sichtbar.',
    ),
    pair(
      'p3',
      'Entspannungspolitik',
      'Versuch, Konfrontation durch Verhandlungen zu begrenzen',
      'Entspannungspolitik schaffte den Konflikt nicht ab, verringerte aber zeitweise die Eskalationsgefahr. Diplomatie blieb darum entscheidend.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Im Kalten Krieg standen sich USA und UdSSR ideologisch und militärisch gegenüber, ohne direkt einen großen Krieg gegeneinander zu führen.',
      true,
      'Genau diese Mischung aus Konfrontation und Abschreckung erklärt den Begriff.',
      'Der Kalte Krieg war kein friedlicher Zustand, sondern eine dauerhafte Konfrontation mit globalen Folgen. Zugleich verhinderten Abschreckung und Diplomatie meist den direkten Großkrieg. Diese Spannung prägt den Begriff.',
    ),
  ],
}

const ostWest: BioBank = {
  quelle: 'Wikipedia: Deutsche Teilung',
  url: 'https://de.wikipedia.org/wiki/Deutsche_Teilung',
  conceptPrefix: 'ge:k10:ost-west',
  facts: [
    fact(
      'teilung',
      'Warum wurde Deutschland nach 1945 geteilt?',
      'Weil die Siegermächte unterschiedliche politische Vorstellungen hatten und der Kalte Krieg die Besatzungszonen auseinandertrieb',
      ['Weil Deutschland freiwillig zwei Staaten gründen wollte', 'Weil es im Mittelalter immer schon zwei deutsche Staaten gab', 'Weil die UNO die Teilung aus Kulturgründen verlangte'],
      'Die deutsche Teilung war eng mit der Blockkonfrontation verbunden.',
      'Nach 1945 wurde Deutschland von den Siegermächten besetzt und in Zonen aufgeteilt. Mit dem Kalten Krieg wuchsen die Unterschiede zwischen West und Ost. Daraus entstanden 1949 zwei deutsche Staaten mit verschiedenen politischen Systemen.',
      'Die Teilung Deutschlands hing eng mit dem ___ Krieg zusammen.',
      ['Kalten', 'kalten'],
    ),
    fact(
      'brd-ddr',
      'Worin unterschieden sich BRD und DDR grundlegend?',
      'Die BRD war eine parlamentarische Demokratie, die DDR eine sozialistische Diktatur unter SED-Führung',
      ['Beide waren identische Mehrparteiendemokratien', 'Die BRD war monarchisch und die DDR republikanisch', 'Beide hatten keine Verbindung zum Kalten Krieg'],
      'Die beiden Staaten standen für unterschiedliche politische Systeme.',
      'Die Bundesrepublik Deutschland entwickelte sich zu einer parlamentarischen Demokratie mit Rechtsstaat und Wahlen. Die DDR war formal ein Staat mit Volksvertretung, tatsächlich aber von der SED beherrscht. Der Gegensatz war daher systemisch und nicht nur verwaltungstechnisch.',
      'Die BRD war eine Demokratie, die DDR eine sozialistische ___.',
      ['Diktatur'],
    ),
    fact(
      'berlin',
      'Warum war Berlin ein besonderer Ort im Ost-West-Konflikt?',
      'Weil die Stadt selbst geteilt war und so die Blockkonfrontation mitten in Europa sichtbar machte',
      ['Weil Berlin außerhalb Deutschlands lag', 'Weil dort keine Besatzungsmächte präsent waren', 'Weil die Stadt nur wirtschaftliche Bedeutung hatte'],
      'Berlin wurde zum Brennpunkt des Kalten Krieges.',
      'Berlin lag im sowjetischen Besatzungsgebiet, war aber selbst in Sektoren geteilt. Damit trafen die beiden Machtblöcke in einer Stadt unmittelbar aufeinander. Viele Krisen des Kalten Krieges verdichteten sich deshalb in Berlin.',
      'Berlin war ein Symbol der Blockkonfrontation, weil die Stadt selbst ___ war.',
      ['geteilt'],
    ),
    fact(
      'mauer',
      'Warum errichtete die DDR 1961 die Berliner Mauer?',
      'Um Flucht und Abwanderung in den Westen zu stoppen',
      ['Um den Handel mit den USA zu erleichtern', 'Um Berlin zur Hauptstadt Europas zu machen', 'Um freie Wahlen vorzubereiten'],
      'Die Mauer war ein Mittel der Abschottung und Zwangssicherung.',
      'Bis 1961 verließen viele Menschen die DDR Richtung Westen. Mit dem Mauerbau wollte die SED-Führung diese Fluchtbewegung beenden und ihre Herrschaft stabilisieren. Die Mauer wurde so zum Symbol von Unfreiheit und Teilung.',
      'Die Berliner Mauer sollte Flucht in den ___ verhindern.',
      ['Westen'],
    ),
    fact(
      'alltag',
      'Warum betraf die deutsche Teilung nicht nur Politik, sondern auch den Alltag?',
      'Weil Familien, Biografien, Reisen, Medien und Lebenswege über Jahrzehnte getrennt wurden',
      ['Weil nur Politiker die Teilung bemerkten', 'Weil Grenzen im Alltag keine Rolle spielen', 'Weil beide Staaten ohne Unterschiede lebten'],
      'Teilung wurde von Millionen Menschen konkret erlebt.',
      'Die deutsche Teilung wirkte in das Leben vieler Menschen hinein. Familien wurden getrennt, Reisen erschwert und unterschiedliche politische Sozialisationen entstanden. Dadurch prägte der Ost-West-Konflikt den Alltag über Generationen.',
      'Die Teilung prägte Familien, Reisen und den täglichen ___.',
      ['Alltag'],
    ),
    fact(
      'friedliche-revolution',
      'Warum war 1989 für die DDR ein Wendepunkt?',
      'Weil Proteste, Reformdruck und der Zusammenbruch des Ostblocks das SED-System erschütterten',
      ['Weil die DDR wirtschaftlich gerade ihren größten Erfolg feierte', 'Weil die Mauer erst 1999 gebaut wurde', 'Weil die Teilung danach stabiler wurde'],
      '1989 öffnete den Weg zum Ende der SED-Herrschaft.',
      'Im Jahr 1989 geriet die DDR in eine tiefe Krise. Bürgerrechtsgruppen, Ausreisewellen und Massenproteste setzten die Führung unter Druck. Zugleich veränderte sich das Umfeld im Ostblock grundlegend.',
      '1989 erschütterten Proteste und Krise das ___-System der DDR.',
      ['SED', 'sed'],
    ),
    fact(
      'mauerfall',
      'Warum gilt der Mauerfall vom 9. November 1989 als historisches Schlüsseldatum?',
      'Weil er die Teilung sichtbar durchbrach und den Weg zur Einheit öffnete',
      ['Weil an diesem Tag die DDR gegründet wurde', 'Weil damit der Erste Weltkrieg endete', 'Weil die NATO aufgelöst wurde'],
      'Der Mauerfall wurde zum Symbol des Umbruchs in Europa.',
      'Mit dem Mauerfall wurde die deutsche Teilung praktisch und symbolisch erschüttert. Menschen konnten Grenzen überwinden, die jahrzehntelang unüberwindbar schienen. Der 9. November 1989 steht deshalb für den Beginn eines tiefen politischen Umbruchs.',
      'Der Mauerfall öffnete den Weg zur deutschen ___.',
      ['Einheit', 'Wiedervereinigung'],
    ),
    fact(
      'wiedervereinigung',
      'Warum war die Wiedervereinigung 1990 mehr als nur ein Verwaltungsakt?',
      'Weil zwei unterschiedlich geprägte Staaten, Gesellschaften und Lebenswelten zusammengeführt wurden',
      ['Weil beide Staaten schon seit Jahrzehnten völlig identisch waren', 'Weil es keine wirtschaftlichen Fragen gab', 'Weil nur Berlin betroffen war'],
      'Einheit bedeutete politischen, sozialen und wirtschaftlichen Wandel.',
      'Mit der Wiedervereinigung 1990 endete die staatliche Teilung Deutschlands. Zugleich begann ein langer Prozess des Zusammenwachsens von Institutionen, Wirtschaft und Alltagskulturen. Einheit war daher nicht nur ein Datum, sondern eine anspruchsvolle Transformation.',
      '1990 mussten zwei unterschiedlich geprägte ___ zusammengeführt werden.',
      ['Gesellschaften', 'Staaten'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'BRD',
      'Westdeutscher Staat als parlamentarische Demokratie',
      'Die BRD entwickelte sich im westlichen Block. Demokratie, Rechtsstaat und parlamentarische Ordnung prägten ihren politischen Rahmen.',
    ),
    pair(
      'p2',
      'DDR',
      'Sozialistischer Staat unter Führung der SED',
      'Die DDR war Teil des Ostblocks und wurde von der SED dominiert. Wahlen und Mitwirkung entsprachen nicht den Standards einer liberalen Demokratie.',
    ),
    pair(
      'p3',
      'Berliner Mauer',
      'Grenzanlage zur Verhinderung von Flucht in den Westen',
      'Die Mauer steht für Abschottung und Unfreiheit. Ihr Fall wurde zum Symbol des Endes der deutschen Teilung.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Die deutsche Teilung war eng mit dem Ost-West-Konflikt verbunden und nicht bloß eine rein innere deutsche Verwaltungsfrage.',
      true,
      'Die Entwicklung der beiden deutschen Staaten lässt sich nur im Zusammenhang des Kalten Krieges verstehen.',
      'Deutschland wurde nach 1945 im Rahmen der internationalen Blockkonfrontation geteilt. Besatzungspolitik, Bündnisse und Ideologien prägten den Gegensatz von BRD und DDR. Der nationale Konflikt war daher immer auch ein internationaler.',
    ),
  ],
}

const wandelEuropa: BioBank = {
  quelle: 'Wikipedia: Europäische Union',
  url: 'https://de.wikipedia.org/wiki/Europ%C3%A4ische_Union',
  conceptPrefix: 'ge:k10:wandel-europa',
  facts: [
    fact(
      'eg',
      'Warum entstand nach 1945 die europäische Integration?',
      'Weil Zusammenarbeit Frieden sichern und wirtschaftliche Verflechtung stärken sollte',
      ['Weil Europa wieder in viele Zölle und Grenzen zerfallen sollte', 'Weil Nationalstaaten sofort abgeschafft wurden', 'Weil nur Militärbündnisse als Lösung galten'],
      'Integration war eine Antwort auf Kriegserfahrungen.',
      'Nach den Katastrophen zweier Weltkriege suchten europäische Staaten nach neuen Formen der Zusammenarbeit. Gemeinsame wirtschaftliche Projekte sollten Konflikte unwahrscheinlicher machen. Aus solchen Anfängen entwickelte sich schrittweise die europäische Integration.',
      'Europäische Integration sollte Frieden sichern und Zusammenarbeit ___.',
      ['stärken'],
    ),
    fact(
      'eu',
      'Was unterscheidet die Europäische Union von einem klassischen Nationalstaat?',
      'Sie ist ein Zusammenschluss souveräner Staaten mit gemeinsamen Institutionen',
      ['Sie ist eine Monarchie mit einem Kaiser', 'Sie ist bloß ein Militärbündnis ohne Politik', 'Sie ersetzt alle Staaten vollständig durch Provinzen'],
      'Die EU verbindet nationale Selbstständigkeit mit gemeinsamer Politik.',
      'Die Europäische Union ist kein Nationalstaat, sondern ein Verbund von Mitgliedstaaten. Diese arbeiten in vielen Bereichen zusammen und haben gemeinsame Institutionen, bleiben aber eigenständige Staaten. Gerade diese Mischform macht die EU historisch besonders.',
      'Die EU ist ein Zusammenschluss souveräner Staaten mit gemeinsamen ___.',
      ['Institutionen'],
    ),
    fact(
      '1989',
      'Warum war 1989 für Europa insgesamt ein Schlüsseljahr?',
      'Weil der Ostblock ins Wanken geriet und Grenzen sowie Machtordnungen sich veränderten',
      ['Weil Europa an diesem Tag erst entdeckt wurde', 'Weil die EG sich sofort auflöste', 'Weil alle Staaten ihre Verfassungen abschafften'],
      '1989 veränderte Europas politische Landkarte grundlegend.',
      '1989 brachte in vielen osteuropäischen Staaten tiefgreifende Umbrüche. Kommunistische Regime gerieten in die Krise oder brachen zusammen. Damit änderten sich Machtverhältnisse, Grenzen und Zukunftsvorstellungen in Europa.',
      '1989 veränderte Europas politische ___.',
      ['Ordnung', 'Landkarte'],
    ),
    fact(
      'transformation',
      'Was meint "Transformation" nach 1989 in Osteuropa?',
      'Den tiefgreifenden Wandel von Politik, Wirtschaft und Gesellschaft',
      ['Nur die Umbenennung von Hauptstädten', 'Die Rückkehr aller Monarchien', 'Ausschließlich den Wechsel einzelner Flaggen'],
      'Transformation beschreibt umfassende Veränderungen.',
      'Nach 1989 mussten viele Staaten in Mittel- und Osteuropa politische und wirtschaftliche Systeme neu ordnen. Der Wandel betraf Verfassungen, Eigentum, Parteien und Alltag. Transformation war daher oft lang, schwierig und konfliktreich.',
      'Transformation bezeichnet den tiefgreifenden Wandel von Politik, Wirtschaft und ___.',
      ['Gesellschaft'],
    ),
    fact(
      'erweiterung',
      'Warum war die Erweiterung der EU für Europa bedeutsam?',
      'Weil sie ehemalige Ostblockstaaten stärker in gemeinsame Strukturen einband',
      ['Weil dadurch jede nationale Politik verschwand', 'Weil nur westeuropäische Staaten profitieren konnten', 'Weil die EU damit zum Weltreich wurde'],
      'Erweiterung veränderte Größe und Aufgaben der Union.',
      'Mit der Aufnahme weiterer Staaten wuchs die Europäische Union geografisch und politisch. Besonders für ehemalige Ostblockstaaten bedeutete dies stärkere Einbindung in westliche Institutionen. Gleichzeitig stellte die Erweiterung die EU vor neue Herausforderungen.',
      'Die EU-Erweiterung band weitere Staaten in gemeinsame ___ ein.',
      ['Strukturen'],
    ),
    fact(
      'friedensidee',
      'Warum wird die EU oft mit der Idee des Friedens verbunden?',
      'Weil Zusammenarbeit und Verflechtung zwischen Mitgliedstaaten Kriege unwahrscheinlicher machen sollen',
      ['Weil es in Europa seitdem keinerlei Konflikte mehr gibt', 'Weil die EU nur eine Kulturorganisation ist', 'Weil Frieden ohne Politik entsteht'],
      'Friedenssicherung ist ein Gründungsmotiv europäischer Einigung.',
      'Die europäische Einigung entstand aus der Erfahrung schwerer Kriege. Wirtschaftliche und politische Verflechtung sollten dazu beitragen, dass Konflikte nicht wieder militärisch eskalieren. Diese Friedensidee gehört bis heute zum Selbstverständnis der EU.',
      'Die EU wird mit Frieden verbunden, weil Verflechtung Kriege ___ machen soll.',
      ['unwahrscheinlicher'],
    ),
    fact(
      'herausforderungen',
      'Warum verlief der Wandel Europas nach 1989 nicht ohne Probleme?',
      'Weil wirtschaftliche Umbrüche, soziale Unsicherheit und neue politische Konflikte entstanden',
      ['Weil alle Menschen sofort gleich reich wurden', 'Weil Grenzen und Identitäten plötzlich bedeutungslos waren', 'Weil Wandel nur Vorteile ohne Spannungen bringt'],
      'Transformation schuf Chancen und Belastungen zugleich.',
      'Der Wandel nach 1989 brachte neue Freiheiten und Möglichkeiten, aber auch soziale Verwerfungen. Arbeitslosigkeit, Unsicherheit und politische Spannungen begleiteten die Transformation vielerorts. Historisch gehört beides zusammen: Hoffnung und Belastung.',
      'Der Wandel Europas brachte Chancen, aber auch soziale und politische ___.',
      ['Spannungen', 'Belastungen'],
    ),
    fact(
      'europa-begriff',
      'Warum ist Europa nach 1989 mehr als nur ein geografischer Raum?',
      'Weil politische Ordnung, Werte, Erinnerung und Zusammenarbeit neu verhandelt wurden',
      ['Weil Europa danach keine Geschichte mehr hatte', 'Weil Geografie jede Politik ersetzt', 'Weil nur Grenzen wichtig blieben'],
      'Europa ist auch ein politischer und historischer Deutungsraum.',
      'Europa ist nicht nur ein Kontinent, sondern auch eine politische Idee. Nach 1989 wurde neu verhandelt, welche Staaten dazugehören, welche Werte gelten und wie Zusammenarbeit aussehen soll. Gerade deshalb ist europäische Geschichte mehr als Kartenkunde.',
      'Europa ist auch ein politischer und historischer ___.',
      ['Deutungsraum', 'Raum'],
    ),
  ],
  pairs: [
    pair(
      'p1',
      'EG/EU',
      'Europäische Zusammenarbeit mit gemeinsamen Institutionen',
      'Die europäische Integration sollte Frieden und Zusammenarbeit fördern. Aus wirtschaftlichen Anfängen entstand ein politischer Verbund.',
    ),
    pair(
      'p2',
      '1989',
      'Jahr des Umbruchs in Europa und im Ostblock',
      '1989 veränderte Machtordnungen und Zukunftsperspektiven tiefgreifend. Es wurde zu einem Schlüsseljahr der europäischen Zeitgeschichte.',
    ),
    pair(
      'p3',
      'Transformation',
      'Tiefer Wandel von Staat, Wirtschaft und Gesellschaft',
      'Transformation meint mehr als Regierungswechsel. Sie umfasst langwierige Umgestaltungen im Alltag und in Institutionen.',
    ),
  ],
  trueFalse: [
    tf(
      't1',
      'Europäische Integration und der Wandel nach 1989 waren nur wirtschaftliche Vorgänge ohne politische oder gesellschaftliche Bedeutung.',
      false,
      'Beides betraf Frieden, Institutionen, Identität und gesellschaftliche Veränderungen.',
      'Die europäische Integration und die Transformation nach 1989 veränderten nicht nur Märkte, sondern auch politische Ordnungen, Grenzen und Lebenswelten. Gerade dadurch gehören sie zu den zentralen Themen der Zeitgeschichte. Europa ist daher auch ein politisches Projekt.',
    ),
  ],
}

const alltag50er: BioBank = {
  quelle: 'Wikipedia: Wirtschaftswunder',
  url: 'https://de.wikipedia.org/wiki/Wirtschaftswunder',
  conceptPrefix: 'ge:k10:50er',
  facts: [
    fact('wiederaufbau', 'Was prägte die 1950er Jahre in Westdeutschland stark?', 'Wiederaufbau und wirtschaftlicher Aufschwung', ['Nur totale Versorgungskrise ohne Veränderungen', 'Ausschließlich Kolonialpolitik', 'Das Ende jeder Industrie'], 'Die 1950er stehen für Neubeginn und neue Alltagsformen.', 'In den 1950er Jahren erlebte Westdeutschland einen deutlichen wirtschaftlichen Aufschwung. Konsum, Wohnungsbau und Wiederaufbau veränderten den Alltag vieler Menschen. Gleichzeitig blieben Kriegsfolgen und traditionelle Rollenbilder spürbar.', 'Die 1950er in Westdeutschland waren geprägt von Wiederaufbau und wirtschaftlichem ___.', ['Aufschwung']),
    fact('ddr-aufbau', 'Was prägte die 1950er Jahre in der DDR?', 'Sozialistischer Aufbau unter politischer Kontrolle der SED', ['Freie Mehrparteiendemokratie ohne Staatseinfluss', 'Ausschließlich private Großunternehmen', 'Vollständige Auflösung aller staatlichen Planung'], 'Alltag und Politik standen enger unter staatlicher Lenkung.', 'In der DDR wurden Gesellschaft und Wirtschaft nach sozialistischen Vorstellungen umgebaut. Staatliche Planung, Parteiherrschaft und politische Kontrolle prägten den Alltag stark. Zugleich gab es Hoffnungen auf soziale Sicherheit und Aufstieg.', 'In der DDR prägten sozialistischer Aufbau und politische ___ die 1950er.', ['Kontrolle']),
    fact('konsum', 'Warum ist Konsum ein wichtiges Thema der 1950er Jahre?', 'Weil steigender Wohlstand besonders in der BRD Alltagswünsche und Lebensstil veränderte', ['Weil Konsum damals verboten war', 'Weil nur der Adel einkaufen durfte', 'Weil Produkte keine soziale Bedeutung hatten'], 'Konsum kann gesellschaftlichen Wandel sichtbar machen.', 'Mit wachsendem Wohlstand wurden Haushaltsgeräte, Kleidung und Freizeitangebote wichtiger. Besonders in der BRD wurde Konsum zu einem Zeichen neuer Lebensqualität. Gleichzeitig verlief dieser Wandel sozial ungleich.', 'Konsum zeigte veränderten Wohlstand und neuen ___.', ['Lebensstil', 'Alltag']),
    fact('rollenbilder', 'Welche Geschlechterrollen waren in den 1950er Jahren oft verbreitet?', 'Eher traditionelle Rollen von männlichem Ernährer und weiblicher Hausfrau', ['Völlig aufgehobene Familienrollen', 'Nur politische Gleichheit ohne Alltagserwartungen', 'Ausschließlich klösterliche Lebensformen'], 'Alltagsmentalitäten wandelten sich langsamer als Technik oder Wirtschaft.', 'In vielen Familien galten in den 1950er Jahren noch traditionelle Vorstellungen von Ehe und Arbeitsteilung. Diese Muster unterschieden sich zwischen Ost und West, prägten aber beide Gesellschaften. Mentalitäten verändern sich oft langsamer als politische Systeme.', 'In den 1950ern waren oft traditionelle ___ verbreitet.', ['Rollenbilder']),
    fact('jugend', 'Warum veränderte sich Jugendkultur in den 1950er Jahren?', 'Weil Medien, Musik und Konsum neue Vorbilder und Lebensstile verbreiteten', ['Weil Jugendliche keine eigene Kultur hatten', 'Weil nur Politik den Alltag bestimmte', 'Weil Rundfunk und Kino nicht existierten'], 'Jugendkultur zeigt gesellschaftlichen Wandel besonders früh.', 'Jugendliche orientierten sich stärker an Musik, Mode und Medien. Neue Vorbilder aus Film und Rundfunk beeinflussten Sprache und Verhalten. Damit entstand sichtbarer Abstand zu älteren Generationen.', 'Jugendkultur wandelte sich durch Medien, Musik und neue ___.', ['Vorbilder', 'Lebensstile']),
    fact('wohnraum', 'Warum war Wohnraum nach 1945 ein wichtiges Alltagsthema?', 'Weil Kriegsschäden und Bevölkerungsbewegungen großen Bedarf an Wohnungen schufen', ['Weil alle Städte unzerstört geblieben waren', 'Weil Menschen nur noch auf dem Land wohnten', 'Weil Wohnraum politisch bedeutungslos war'], 'Wohnen gehört zu den zentralen Erfahrungen der Nachkriegszeit.', 'Nach Krieg und Flucht fehlte in vielen Städten Wohnraum. Neubau und Wiederaufbau waren deshalb entscheidend für den Alltag. Wohnungsfrage, Familie und soziale Lage hingen eng zusammen.', 'Nach 1945 bestand in vielen Städten großer Bedarf an ___.', ['Wohnungen', 'Wohnraum']),
    fact('mentalitaeten', 'Warum spricht man bei den 1950er Jahren auch von Mentalitäten?', 'Weil Einstellungen zu Ordnung, Familie, Arbeit und Konsum den Alltag mitprägten', ['Weil nur Gesetze den Alltag erklären', 'Weil Gefühle für Geschichte unwichtig sind', 'Weil Mentalitäten nur in der Antike vorkamen'], 'Geschichte des Alltags fragt auch nach Denk- und Deutungsmustern.', 'Mentalitäten beschreiben verbreitete Einstellungen und Erwartungen einer Zeit. In den 1950er Jahren spielten Ordnung, Sicherheit, Familie und Leistungsbereitschaft in vielen Milieus eine große Rolle. Solche Haltungen prägen Alltag und Politik zugleich.', 'Mentalitäten betreffen verbreitete Einstellungen zu Arbeit, Familie und ___.', ['Ordnung', 'Konsum']),
    fact('vergleich', 'Was zeigt der Vergleich der 1950er Jahre in BRD und DDR?', 'Ähnliche Nachkriegserfahrungen konnten in sehr unterschiedlichen politischen Systemen verarbeitet werden', ['Beide Staaten waren im Alltag völlig identisch', 'Nur die Außenpolitik unterschied sich', 'Nachkriegsalltag spielte keine Rolle'], 'Vergleich macht Unterschiede und Gemeinsamkeiten sichtbar.', 'BRD und DDR teilten Nachkriegserfahrungen, entwickelten aber unterschiedliche politische und wirtschaftliche Ordnungen. Der Alltag wurde deshalb ähnlich belastet, aber verschieden organisiert und gedeutet. Gerade das macht den Vergleich historisch interessant.', 'Der Vergleich zeigt Gemeinsamkeiten des Nachkriegsalltags und politische ___.', ['Unterschiede']),
  ],
  pairs: [
    pair('p1', 'Wirtschaftswunder', 'Aufschwung und Konsumzuwachs in der BRD', 'Der wirtschaftliche Aufschwung veränderte Wohnen, Konsum und Zukunftserwartungen. Er wurde zu einem prägenden Bild der 1950er Jahre.'),
    pair('p2', 'sozialistischer Aufbau', 'Politisch gelenkter Um- und Aufbau in der DDR', 'In der DDR verbanden sich wirtschaftlicher Aufbau und SED-Herrschaft. Alltag blieb dadurch stärker staatlich geprägt.'),
    pair('p3', 'Mentalitäten', 'Typische Einstellungen und Erwartungen einer Zeit', 'Mentalitäten erklären, warum Menschen auf Wandel nicht nur politisch, sondern auch kulturell reagieren. Sie sind für Alltagsgeschichte zentral.'),
  ],
  trueFalse: [
    tf('t1', 'Die 1950er Jahre in BRD und DDR lassen sich nur über hohe Politik verstehen, nicht über Alltag, Konsum oder Rollenbilder.', false, 'Gerade Alltagsgeschichte zeigt, wie politische Systeme konkret gelebt und erlebt wurden.', 'Politische Systeme wirken nicht nur in Verfassungen, sondern auch in Wohnen, Konsum, Familie und Jugendkultur. Die 1950er Jahre lassen sich deshalb nur mit Blick auf den Alltag wirklich verstehen. Mentalitäten gehören ausdrücklich dazu.'),
  ],
}

const alltag70er: BioBank = {
  quelle: 'Wikipedia: 1970er',
  url: 'https://de.wikipedia.org/wiki/1970er',
  conceptPrefix: 'ge:k10:70er',
  facts: [
    fact('ostpolitik', 'Warum sind die 1970er Jahre in Deutschland politisch bedeutsam?', 'Weil Entspannung, Ostpolitik und gesellschaftlicher Wandel neue Perspektiven eröffneten', ['Weil der Kalte Krieg sofort endete', 'Weil Deutschland wieder monarchisch wurde', 'Weil Europa sich vollkommen abschottete'], 'Die 1970er verbinden innen- und außenpolitischen Wandel.', 'In den 1970er Jahren veränderten sich Politik und Gesellschaft in beiden deutschen Staaten. Entspannungspolitik, Ostverträge und neue soziale Debatten prägten die Zeit. Damit verschoben sich Alltagserfahrungen und Zukunftserwartungen.', 'Die 1970er waren geprägt von Entspannung, Ostpolitik und gesellschaftlichem ___.', ['Wandel']),
    fact('ostvertraege', 'Was war das Ziel der Ostverträge?', 'Die Beziehungen zwischen BRD, DDR und osteuropäischen Staaten zu entspannen und zu regeln', ['Die sofortige militärische Vereinigung Deutschlands', 'Die Auflösung aller Grenzen in Europa', 'Die Rückkehr zum Kaiserreich'], 'Verträge konnten trotz Teilung praktische Annäherung schaffen.', 'Mit den Ostverträgen der 1970er Jahre versuchte die Bundesrepublik, das Verhältnis zum Osten zu normalisieren. Grenzen und politische Realitäten wurden anerkannt, ohne die Einheit als Ziel ganz aufzugeben. Das war ein wichtiger Schritt der Entspannungspolitik.', 'Die Ostverträge sollten Beziehungen ___ und praktisch regeln.', ['entspannen']),
    fact('gesellschaft', 'Warum gelten die 1970er auch als Zeit gesellschaftlicher Debatten?', 'Weil Fragen nach Mitbestimmung, Umwelt, Geschlechterrollen und Lebensstil stärker diskutiert wurden', ['Weil es keinerlei Protest mehr gab', 'Weil nur Außenpolitik zählte', 'Weil der Alltag völlig unverändert blieb'], 'Neue soziale Bewegungen erweiterten politische Themen.', 'In den 1970er Jahren gewannen Themen wie Umwelt, Frauenrechte, Bildung und Mitbestimmung an Gewicht. Gesellschaftliche Konflikte wurden sichtbarer und oft offener ausgetragen. Politik bezog sich damit nicht mehr nur auf Staat und Krieg, sondern stärker auf Alltag und Lebensqualität.', 'In den 1970ern wurden Umwelt, Mitbestimmung und ___ stärker diskutiert.', ['Geschlechterrollen', 'Lebensstil']),
    fact('konsum', 'Wie veränderte sich der Alltag in den 1970er Jahren?', 'Mehr Medien, Mobilität und Konsum beeinflussten Freizeit und Lebensgefühl', ['Freizeit spielte keine Rolle', 'Menschen lebten wieder überwiegend ohne Technik', 'Nur Soldaten prägten den Alltag'], 'Alltagskultur wird in modernen Gesellschaften stark von Medien und Konsum mitgeprägt.', 'Fernsehen, Auto, Reisen und Popkultur prägten in den 1970er Jahren das Lebensgefühl vieler Menschen. Alltag wurde dadurch stärker konsum- und medienorientiert. Solche Veränderungen machten sich in Ost und West unterschiedlich bemerkbar.', 'Medien, Mobilität und ___ beeinflussten den Alltag der 1970er.', ['Konsum']),
    fact('krise', 'Warum waren die 1970er nicht nur eine Zeit des Fortschritts?', 'Weil Krisen wie Ölpreisschock, Terrorismus und wirtschaftliche Unsicherheit neue Probleme schufen', ['Weil es gar keine wirtschaftlichen oder politischen Herausforderungen gab', 'Weil jede Gesellschaft seitdem konfliktfrei wurde', 'Weil Entspannung alle Spannungen beseitigte'], 'Wandel brachte Chancen und neue Verunsicherung zugleich.', 'Die 1970er Jahre waren von Reformen, aber auch von Krisen geprägt. Ölpreisschock, Arbeitslosigkeit und Terrorismus belasteten Politik und Gesellschaft. Historisch gehört deshalb zur Dekade sowohl Aufbruch als auch Unsicherheit.', 'Die 1970er brachten Reformen, aber auch Krisen und ___.', ['Unsicherheit']),
    fact('ddr-alltag', 'Was kennzeichnete den DDR-Alltag in den 1970er Jahren häufig?', 'Staatliche Kontrolle blieb bestehen, zugleich gab es Bemühungen um soziale Stabilität und Versorgung', ['Die DDR wurde eine liberale Mehrparteiendemokratie', 'Staat und Partei verloren jede Bedeutung', 'Grenzen wurden komplett geöffnet'], 'Herrschaft und Alltag standen weiter eng zusammen.', 'In der DDR blieb die politische Kontrolle durch die SED erhalten. Gleichzeitig bemühte sich der Staat, Versorgung, Wohnen und soziale Sicherheit zu stabilisieren. Alltag bestand also aus Anpassung, Versorgung und begrenzten Freiräumen zugleich.', 'In der DDR blieben politische Kontrolle und soziale ___ zentrale Alltagsthemen.', ['Versorgung', 'Stabilität']),
    fact('west-alltag', 'Warum unterschied sich der Alltag in der BRD von dem in der DDR?', 'Weil Demokratie, Marktwirtschaft und Reise- oder Medienfreiheit andere Lebensmöglichkeiten eröffneten', ['Weil die BRD kein Fernsehen oder Konsum kannte', 'Weil beide Staaten identische politische Systeme hatten', 'Weil nur die DDR eine Wirtschaft besaß'], 'Politische Systeme wirken tief in Lebenswelten hinein.', 'In der BRD prägten Marktwirtschaft, politische Freiheit und breitere Reisemöglichkeiten den Alltag. Diese Rahmenbedingungen unterschieden sich deutlich von der DDR. Deshalb führten ähnliche Zeitströmungen nicht zu denselben Erfahrungen.', 'Die BRD bot unter anderem andere Medien-, Reise- und ___.', ['Freiheitsmöglichkeiten', 'Freiheiten']),
    fact('vergleich', 'Was zeigt der Vergleich der 1970er Jahre in Ost und West?', 'Dass Entspannung und Modernisierung in unterschiedlichen politischen Systemen sehr verschieden erlebt wurden', ['Dass Alltag im Kalten Krieg überall gleich war', 'Dass Politik keinen Einfluss auf Lebenswelten hatte', 'Dass nur Außenminister Geschichte machten'], 'Vergleich macht Gleichzeitigkeit von Nähe und Unterschied sichtbar.', 'Ost und West erlebten die 1970er zur gleichen Zeit, aber unter unterschiedlichen politischen Bedingungen. Darum lassen sich ähnliche Themen wie Medien, Jugend oder Konsum nicht einfach gleichsetzen. Gerade die Unterschiede machen den Vergleich ergiebig.', 'Der Vergleich zeigt gemeinsame Zeitphänomene und politische ___.', ['Unterschiede']),
  ],
  pairs: [
    pair('p1', 'Ostpolitik', 'Annäherung und Entspannung im Verhältnis zum Osten', 'Ostpolitik verband Anerkennung von Realitäten mit dem Versuch, den Kalten Krieg im Alltag zu entschärfen. Sie war ein wichtiger Teil der 1970er Jahre.'),
    pair('p2', 'Ölkrise', 'Wirtschaftliche Erschütterung und Unsicherheit der 1970er', 'Die Ölkrise zeigt, dass die 1970er nicht nur Jahre des Aufbruchs waren. Globale Probleme wirkten direkt in den Alltag hinein.'),
    pair('p3', 'neue soziale Bewegungen', 'Gesellschaftliche Gruppen mit Themen wie Umwelt oder Frauenrechten', 'Diese Bewegungen erweiterten politische Debatten über klassische Parteien hinaus. So veränderte sich auch das Verständnis von Politik.'),
  ],
  trueFalse: [
    tf('t1', 'Die 1970er Jahre waren in Deutschland nur eine ruhige Übergangszeit ohne gesellschaftliche Konflikte oder neue politische Themen.', false, 'Gerade Debatten über Ostpolitik, Umwelt, Gleichberechtigung und Krisen prägten die Dekade stark.', 'Die 1970er gelten als Jahrzehnt von Reformen, neuen Bewegungen und zugleich wirtschaftlicher sowie politischer Verunsicherung. Wer sie nur als ruhige Zwischenphase sieht, verfehlt wichtige Entwicklungen des Alltags und der Politik.'),
  ],
}

const friedlicheRevolution: BioBank = {
  quelle: 'Wikipedia: Friedliche Revolution',
  url: 'https://de.wikipedia.org/wiki/Friedliche_Revolution',
  conceptPrefix: 'ge:k10:friedliche-revolution',
  facts: [
    fact('proteste', 'Warum wuchsen 1989 in der DDR die Proteste?', 'Weil viele Menschen politische Freiheit, Reisefreiheit und Reformen forderten', ['Weil die SED gerade freie Wahlen eingeführt hatte', 'Weil die Mauer neu gebaut werden sollte', 'Weil keinerlei Unzufriedenheit bestand'], 'Die Proteste richteten sich gegen politische Unfreiheit und Erstarrung.', '1989 wuchs in der DDR der Unmut über fehlende Freiheit, wirtschaftliche Probleme und politische Erstarrung. Viele Menschen wollten reisen, mitbestimmen und offen sprechen können. Daraus entstanden immer größere Proteste.', '1989 forderten viele Menschen Freiheit, Reisefreiheit und politische ___.', ['Reformen']),
    fact('montagsdemos', 'Warum wurden die Montagsdemonstrationen so wichtig?', 'Weil sie regelmäßig viele Menschen sichtbar versammelten und den Druck auf das Regime erhöhten', ['Weil sie geheime Treffen weniger Funktionäre waren', 'Weil sie nur kulturelle Veranstaltungen ohne Politik waren', 'Weil sie außerhalb der DDR stattfanden'], 'Öffentliche Massenproteste signalisierten den Machtverlust der SED.', 'Die Montagsdemonstrationen wurden zu einem sichtbaren Zeichen des Widerstands gegen die SED-Herrschaft. Immer mehr Menschen gingen friedlich auf die Straße und zeigten, dass Angstbarrieren bröckelten. Das erhöhte den politischen Druck erheblich.', 'Die Montagsdemonstrationen erhöhten den Druck auf das ___.', ['Regime', 'SED-Regime']),
    fact('friedlich', 'Warum spricht man von einer "friedlichen" Revolution?', 'Weil viele Veränderungen durch massenhaften Protest ohne Bürgerkrieg erkämpft wurden', ['Weil es keinerlei Konflikte oder Spannungen gab', 'Weil nur Regierende Reformen planten', 'Weil Militär und Polizei alle Proteste anführten'], 'Die Gewaltfreiheit war ein zentrales Merkmal des Umbruchs.', 'Die Friedliche Revolution war von großer Spannung begleitet, blieb aber weitgehend gewaltfrei. Viele Menschen setzten bewusst auf Demonstrationen, Gebete und Öffentlichkeit statt auf bewaffnete Auseinandersetzung. Darin liegt ihr historischer Rang.', 'Man spricht von Friedlicher Revolution wegen des weitgehend ___ Verlaufs.', ['gewaltfreien']),
    fact('mauerfall', 'Wie hing der Mauerfall mit der Friedlichen Revolution zusammen?', 'Er war ein sichtbares Ergebnis des wachsenden Drucks auf die SED-Herrschaft', ['Er geschah unabhängig von allen Protesten', 'Er war nur ein wirtschaftlicher Verwaltungsakt', 'Er führte sofort zur Spaltung Europas'], 'Der Mauerfall war Höhepunkt und Symbol des Umbruchs.', 'Ohne Reformdruck, Ausreisewellen und Demonstrationen wäre der Mauerfall kaum denkbar gewesen. Der 9. November 1989 machte den Zusammenbruch der alten Ordnung sichtbar. Deshalb ist er eng mit der Friedlichen Revolution verbunden.', 'Der Mauerfall war ein sichtbares Ergebnis des Drucks auf die ___-Herrschaft.', ['SED', 'sed']),
    fact('buergerbewegung', 'Welche Rolle spielten Bürgerbewegungen 1989?', 'Sie organisierten Kritik, sammelten Forderungen und schufen Räume für Opposition', ['Sie verteidigten geschlossen die alte Parteiherrschaft', 'Sie bestanden nur aus ausländischen Regierungen', 'Sie ersetzten sofort alle staatlichen Institutionen'], 'Opposition brauchte Organisation und Öffentlichkeit.', 'Bürgerbewegungen wie Neues Forum boten Menschen Möglichkeiten, Kritik zu formulieren und sich zu vernetzen. Sie machten Opposition sichtbarer und politisch wirksamer. Solche Gruppen halfen, Protest in geordnete Forderungen zu übersetzen.', 'Bürgerbewegungen schufen Räume für Opposition und politische ___.', ['Forderungen']),
    fact('runde-tische', 'Warum waren Runde Tische nach 1989 wichtig?', 'Weil dort Vertreter alter Macht und neuer Opposition den Übergang verhandelten', ['Weil sie nur kulturelle Feste organisierten', 'Weil sie die Mauer neu planten', 'Weil sie freie Wahlen verhindern sollten'], 'Transformation brauchte auch Gesprächsforen und Aushandlung.', 'Nach dem Machtverlust der SED mussten neue Regeln und Schritte vereinbart werden. Runde Tische brachten verschiedene Kräfte an einen Tisch, um Übergänge friedlich zu gestalten. Damit wurden Protest und Verhandlung miteinander verbunden.', 'Runde Tische dienten der friedlichen ___ des Übergangs.', ['Aushandlung', 'Regelung']),
    fact('wiedervereinigung', 'Warum gehört die Wiedervereinigung zur Geschichte der Friedlichen Revolution?', 'Weil der Umbruch von 1989 den Weg zur staatlichen Einheit 1990 öffnete', ['Weil die Einheit schon lange vorher vollzogen war', 'Weil die Revolution nur Kulturpolitik betraf', 'Weil es nach 1989 keine staatlichen Veränderungen gab'], 'Revolution und Einheit hängen zusammen, sind aber nicht identisch.', 'Die Friedliche Revolution brachte zunächst den Sturz der SED-Herrschaft. Daraus entwickelte sich in kurzer Zeit auch der Weg zur deutschen Wiedervereinigung. Revolution und Einheit gehören zusammen, meinen aber unterschiedliche Schritte des Umbruchs.', 'Die Revolution von 1989 öffnete den Weg zur staatlichen ___.', ['Einheit', 'Wiedervereinigung']),
    fact('erinnerung', 'Warum ist die Friedliche Revolution ein wichtiger Erinnerungsort der deutschen Geschichte?', 'Weil sie zeigt, dass Bürgerinnen und Bürger friedlich politische Veränderung erzwingen konnten', ['Weil nur Regierungen Geschichte machen', 'Weil Protest niemals Wirkung hat', 'Weil Erinnerung nur für Kriege wichtig ist'], 'Die Ereignisse von 1989 stehen für Mut, Öffentlichkeit und Wandel.', 'Die Friedliche Revolution ist ein zentraler Erinnerungsort, weil sie demokratischen Wandel von unten sichtbar macht. Viele Menschen überwanden Angst und traten öffentlich für Freiheit ein. Darin liegt ihre langfristige Bedeutung für das Selbstverständnis des vereinten Deutschlands.', 'Die Friedliche Revolution erinnert an friedlich erkämpfte politische ___.', ['Veränderung', 'Freiheit']),
  ],
  pairs: [
    pair('p1', 'Montagsdemonstrationen', 'Regelmäßige Massenproteste gegen die SED-Herrschaft', 'Die Montagsdemonstrationen machten Opposition sichtbar und stärkten den Mut vieler Menschen. Sie gehören zu den markantesten Bildern von 1989.'),
    pair('p2', 'Runder Tisch', 'Forum zur Aushandlung des Übergangs nach dem Machtverlust der SED', 'Runde Tische zeigen, dass Wandel nicht nur auf der Straße, sondern auch in Verhandlungen gestaltet wurde. Sie stehen für geordnete Transformation.'),
    pair('p3', 'Mauerfall', 'Symbolischer Durchbruch der deutschen Teilung am 9. November 1989', 'Der Mauerfall verdichtete die Ereignisse von 1989 in einem starken Bild. Er steht für Freiheit, Bewegung und den Zerfall der alten Ordnung.'),
  ],
  trueFalse: [
    tf('t1', 'Die Friedliche Revolution zeigt, dass massenhafter, öffentlicher und gewaltfreier Protest politische Systeme verändern kann.', true, 'Gerade diese Erfahrung macht 1989 zu einem Schlüsselmoment deutscher Zeitgeschichte.', 'Die Ereignisse von 1989 zeigen, dass Bürgerinnen und Bürger autoritäre Herrschaft friedlich unter Druck setzen können. Öffentlichkeit, Organisation und Beharrlichkeit waren dafür entscheidend. Darum bleibt die Friedliche Revolution historisch so bedeutsam.'),
  ],
}

export const GESCHICHTE_K10_GENERATORS: Record<string, Topic['generate']> = {
  'ge-k10-lb1-usa-udssr': bankGenerate(usaUdssr),
  'ge-k10-lb2-ost-west': bankGenerate(ostWest),
  'ge-k10-lb3-wandel-europa': bankGenerate(wandelEuropa),
  'ge-k10-lbw-50er': bankGenerate(alltag50er),
  'ge-k10-lbw-70er': bankGenerate(alltag70er),
  'ge-k10-lbw-friedliche-revolution': bankGenerate(friedlicheRevolution),
}
