import type { PackArea, PackGrade, PackTopic } from './pack'
import { DEFAULT_TASKS_PER_ROUND } from './tasksPerRound'

const topic = (id: string, title: string, keywords?: string[]): PackTopic => ({
  id,
  title,
  pointsPerTask: 10,
  hint: 'Tippe oder gib die Antwort ein. Erklärung erscheint nach dem Prüfen.',
  released: false,
  tasksPerRound: DEFAULT_TASKS_PER_ROUND,
  ...(keywords?.length ? { keywords } : {}),
  // Wissen default via hydrate/ensureTopicFachwissen (Issue #45)
})

const area = (id: string, title: string, ustd: number | undefined, topics: PackTopic[]): PackArea => ({
  id,
  title,
  ...(ustd !== undefined ? { ustd } : {}),
  topics,
})

const grade = (
  id: string,
  title: string,
  gradeTitle: string,
  description: string,
  searchHints: string[],
  areas: PackArea[],
): PackGrade => ({
  id,
  title,
  subjectTitle: 'Physik',
  gradeTitle,
  description,
  searchHints,
  areas,
})

/** JGS 11/12 Gk/Lk with ~5–7 practice topics per Lernbereich. */
export function buildPhysikGymOberstufeGrades(): PackGrade[] {
  return [
    grade(
      'physik-jgs-11-gk',
      'Jahrgangsstufe 11 · Grundkurs',
      'JGS 11 · Grundkurs',
      'Energieerhaltung, Kinematik/Dynamik, Kondensator und Spule, geladene Teilchen in Feldern.',
      ['Energie', 'Kinematik', 'Kondensator', 'Feld'],
      [
        area('lb1', 'Erhaltung der Energie', 10, [
          topic('ph-j11gk-lb1-ekin', 'Kinetische Energie', ['Ekin']),
          topic('ph-j11gk-lb1-epot', 'Potentielle Energie', ['Epot']),
          topic('ph-j11gk-lb1-energie', 'Erhaltung der Energie', ['Energieerhaltung']),
          topic('ph-j11gk-lb1-bilanz', 'Energiebilanz', ['Bilanz']),
          topic('ph-j11gk-lb1-reibung', 'Energie und Reibung', ['Reibung']),
        ]),
        area('lb2', 'Anwendung der Kinematik und Dynamik', 14, [
          topic('ph-j11gk-lb2-gleichfoermig', 'Gleichförmige Bewegung', ['v']),
          topic('ph-j11gk-lb2-mechanik', 'Anwendung der Kinematik und Dynamik', ['Kinematik', 'Dynamik']),
          topic('ph-j11gk-lb2-beschleunigung', 'Beschleunigte Bewegung', ['a']),
          topic('ph-j11gk-lb2-kraft', 'F = m·a', ['Newton']),
          topic('ph-j11gk-lb2-diagramme', 'Bewegungsdiagramme', ['Diagramm']),
          topic('ph-j11gk-lb2-wurf', 'Senkrechter Wurf (Einblick)', ['Wurf']),
        ]),
        area('lb3', 'Kondensator und Spule – Praktikum', 10, [
          topic('ph-j11gk-lb3-kondensator', 'Kondensator C = Q/U', ['Kondensator']),
          topic('ph-j11gk-lb3-praktikum', 'Kondensator und Spule – Praktikum', ['Kondensator', 'Spule']),
          topic('ph-j11gk-lb3-laden', 'Laden und Entladen', ['RC']),
          topic('ph-j11gk-lb3-spule', 'Spule und Induktion (Einblick)', ['Spule']),
          topic('ph-j11gk-lb3-messung', 'Messung am Kondensator', ['Messung']),
        ]),
        area('lb4', 'Geladene Teilchen in elektrischen und magnetischen Feldern', 18, [
          topic('ph-j11gk-lb4-efeld', 'Elektrisches Feld', ['E-Feld']),
          topic('ph-j11gk-lb4-felder', 'Geladene Teilchen in Feldern', ['Feld', 'Ladung']),
          topic('ph-j11gk-lb4-kraft', 'F = q·E', ['Kraft']),
          topic('ph-j11gk-lb4-lorentz', 'Lorentzkraft (Einblick)', ['Lorentz']),
          topic('ph-j11gk-lb4-bahn', 'Bahnformen', ['Bahn']),
          topic('ph-j11gk-lb4-anwendung', 'Technische Anwendungen', ['Anwendung']),
        ]),
        area('lbw', 'Wahlbereiche', undefined, [
          topic('ph-j11gk-lbw-konstanten', 'Bestimmung elementarer Naturkonstanten', ['Naturkonstante']),
          topic('ph-j11gk-lbw-e', 'Elementarladung', ['e']),
          topic('ph-j11gk-lbw-exkursion', 'Physikalisch-technische Exkursion', ['Exkursion']),
          topic('ph-j11gk-lbw-sicherheit', 'Sicherheit bei Exkursionen', ['Sicherheit']),
          topic('ph-j11gk-lbw-anwendungen', 'Technische Anwendungen von Spulen und Kondensatoren', ['Anwendung']),
          topic('ph-j11gk-lbw-filter', 'Filter und Schwingkreise (Einblick)', ['Filter']),
          topic('ph-j11gk-lbw-relativitaet', 'Relativität von Zeit und Raum', ['Relativität']),
          topic('ph-j11gk-lbw-lichtgeschwindigkeit', 'Lichtgeschwindigkeit als Grenze', ['c']),
        ]),
      ],
    ),
    grade(
      'physik-jgs-12-gk',
      'Jahrgangsstufe 12 · Grundkurs',
      'JGS 12 · Grundkurs',
      'Optik, Quantenphysik, Strahlung aus Atomhülle und Atomkern.',
      ['Optik', 'Quantenphysik', 'Atom', 'Strahlung'],
      [
        area('lb1', 'Welleneigenschaften des Lichts', 8, [
          topic('ph-j12gk-lb1-welle', 'Licht als Welle', ['Lichtwelle']),
          topic('ph-j12gk-lb1-licht', 'Welleneigenschaften des Lichts', ['Lichtwelle']),
          topic('ph-j12gk-lb1-interferenz', 'Interferenz', ['Interferenz']),
          topic('ph-j12gk-lb1-beugung', 'Beugung', ['Beugung']),
          topic('ph-j12gk-lb1-cf', 'c = λ·f', ['Wellenlänge']),
        ]),
        area('lb2', 'Praktikum Optik', 6, [
          topic('ph-j12gk-lb2-linse', 'Linsenexperiment', ['Linse']),
          topic('ph-j12gk-lb2-optik', 'Praktikum Optik', ['Optik', 'Praktikum']),
          topic('ph-j12gk-lb2-brennweite', 'Brennweite bestimmen', ['Brennweite']),
          topic('ph-j12gk-lb2-bild', 'reelle und virtuelle Bilder', ['Bild']),
          topic('ph-j12gk-lb2-fehler', 'Messunsicherheit Optik', ['Fehler']),
        ]),
        area('lb3', 'Grundlagen der Quantenphysik', 10, [
          topic('ph-j12gk-lb3-photo', 'Photoeffekt', ['Photoeffekt']),
          topic('ph-j12gk-lb3-quanten', 'Grundlagen der Quantenphysik', ['Quantenphysik']),
          topic('ph-j12gk-lb3-photon', 'Photon E = h·f', ['Photon']),
          topic('ph-j12gk-lb3-dualismus', 'Welle-Teilchen-Dualismus', ['Dualismus']),
          topic('ph-j12gk-lb3-grenze', 'Klassische Grenzen', ['Klassik']),
        ]),
        area('lb4', 'Strahlung aus Atomhülle und Atomkern', 20, [
          topic('ph-j12gk-lb4-atomhuelle', 'Strahlung der Atomhülle', ['Atom']),
          topic('ph-j12gk-lb4-strahlung', 'Strahlung aus Atomhülle und Atomkern', ['Atom', 'Kernstrahlung']),
          topic('ph-j12gk-lb4-zerfall', 'Radioaktiver Zerfall', ['Zerfall']),
          topic('ph-j12gk-lb4-halbwert', 'Halbwertszeit', ['Halbwertszeit']),
          topic('ph-j12gk-lb4-arten', 'Alpha, Beta, Gamma', ['Strahlung']),
          topic('ph-j12gk-lb4-spaltung', 'Kernspaltung und Fusion (Einblick)', ['Kernspaltung']),
        ]),
        area('lbw', 'Wahlbereiche', undefined, [
          topic('ph-j12gk-lbw-anwendungen', 'Anwendungen der Physik', ['Anwendung']),
          topic('ph-j12gk-lbw-medizin', 'Strahlung in der Medizin', ['Medizin']),
          topic('ph-j12gk-lbw-optik', 'Optische Phänomene', ['Optik']),
          topic('ph-j12gk-lbw-regenbogen', 'Regenbogen und Dispersion', ['Regenbogen']),
          topic('ph-j12gk-lbw-akustik', 'Akustik', ['Akustik']),
          topic('ph-j12gk-lbw-schall', 'Schallgeschwindigkeit', ['Schall']),
        ]),
      ],
    ),
    grade(
      'physik-jgs-11-lk',
      'Jahrgangsstufe 11 · Leistungskurs',
      'JGS 11 · Leistungskurs',
      'Erhaltungssätze, Mechanik, Felder, Induktion, Praktikum.',
      ['Erhaltungssatz', 'Newton', 'Feld', 'Induktion'],
      [
        area('lb1', 'Erhaltungssätze und ihre Anwendungen', 20, [
          topic('ph-j11lk-lb1-impuls', 'Impuls', ['Impuls']),
          topic('ph-j11lk-lb1-erhaltung', 'Erhaltungssätze und ihre Anwendungen', ['Impuls', 'Energie']),
          topic('ph-j11lk-lb1-energie', 'Energieerhaltung', ['Energie']),
          topic('ph-j11lk-lb1-stoss', 'Stoßprozesse', ['Stoß']),
          topic('ph-j11lk-lb1-drehimpuls', 'Drehimpuls (Einblick)', ['Drehimpuls']),
        ]),
        area('lb2', 'Kinematik geradliniger Bewegungen', 12, [
          topic('ph-j11lk-lb2-ort', 'Ort und Zeit', ['Ort']),
          topic('ph-j11lk-lb2-kinematik', 'Kinematik geradliniger Bewegungen', ['Kinematik']),
          topic('ph-j11lk-lb2-geschwindigkeit', 'Geschwindigkeit', ['v']),
          topic('ph-j11lk-lb2-beschleunigung', 'Beschleunigung', ['a']),
          topic('ph-j11lk-lb2-gleichungen', 'Bewegungsgleichungen', ['Gleichung']),
        ]),
        area('lb3', 'Newtonsche Gesetze und deren Anwendungen', 8, [
          topic('ph-j11lk-lb3-traegheit', 'Trägheitsgesetz', ['Trägheit']),
          topic('ph-j11lk-lb3-newton', 'Newtonsche Gesetze und deren Anwendungen', ['Newton']),
          topic('ph-j11lk-lb3-kraft', 'F = m·a', ['Kraft']),
          topic('ph-j11lk-lb3-wechselwirkung', 'Wechselwirkungsgesetz', ['Aktion']),
          topic('ph-j11lk-lb3-anwendung', 'Anwendungen im Alltag', ['Anwendung']),
        ]),
        area('lb4', 'Modellbildung und Simulation', 8, [
          topic('ph-j11lk-lb4-modell', 'Modellbildung und Simulation', ['Modell', 'Simulation']),
          topic('ph-j11lk-lb4-annahmen', 'Modellannahmen', ['Annahme']),
          topic('ph-j11lk-lb4-grenzen', 'Grenzen von Modellen', ['Grenze']),
          topic('ph-j11lk-lb4-simulation', 'Simulation vs. Experiment', ['Simulation']),
          topic('ph-j11lk-lb4-numerisch', 'Numerische Schritte (Einblick)', ['Numerik']),
        ]),
        area('lb5', 'Krummlinige Bewegungen', 10, [
          topic('ph-j11lk-lb5-kreis', 'Gleichförmige Kreisbewegung', ['Kreis']),
          topic('ph-j11lk-lb5-kurven', 'Krummlinige Bewegungen', ['Kreisbewegung']),
          topic('ph-j11lk-lb5-zentripetal', 'Zentripetalkraft', ['Zentripetal']),
          topic('ph-j11lk-lb5-wurf', 'Schräger Wurf', ['Wurf']),
          topic('ph-j11lk-lb5-bahn', 'Bahnkurven', ['Bahn']),
        ]),
        area('lb6', 'Einblick in die Relativitätstheorie', 8, [
          topic('ph-j11lk-lb6-postulate', 'Postulate', ['Relativität']),
          topic('ph-j11lk-lb6-relativitaet', 'Einblick in die Relativitätstheorie', ['Relativität']),
          topic('ph-j11lk-lb6-zeit', 'Zeitdilatation', ['Zeit']),
          topic('ph-j11lk-lb6-laenge', 'Längenkontraktion (Einblick)', ['Länge']),
          topic('ph-j11lk-lb6-c', 'c als Grenzgeschwindigkeit', ['c']),
        ]),
        area('lb7', 'Elektrisches Feld', 14, [
          topic('ph-j11lk-lb7-ladung', 'Ladung und Feld', ['Ladung']),
          topic('ph-j11lk-lb7-efeld', 'Elektrisches Feld', ['Elektrisches Feld']),
          topic('ph-j11lk-lb7-feldstaerke', 'Feldstärke E = F/q', ['E']),
          topic('ph-j11lk-lb7-linien', 'Feldlinien', ['Feldlinien']),
          topic('ph-j11lk-lb7-potential', 'Potential und Spannung', ['Potential']),
        ]),
        area('lb8', 'Magnetisches Feld', 10, [
          topic('ph-j11lk-lb8-magnet', 'Magnetfeldquellen', ['Magnet']),
          topic('ph-j11lk-lb8-mfeld', 'Magnetisches Feld', ['Magnetisches Feld']),
          topic('ph-j11lk-lb8-linien', 'Feldlinien Magnet', ['Feldlinien']),
          topic('ph-j11lk-lb8-strom', 'Magnetfeld um Leiter', ['Strom']),
          topic('ph-j11lk-lb8-spule', 'Spulenfeld', ['Spule']),
        ]),
        area('lb9', 'Geladene Teilchen in Feldern', 12, [
          topic('ph-j11lk-lb9-efeld', 'Teilchen im E-Feld', ['E-Feld']),
          topic('ph-j11lk-lb9-teilchen', 'Geladene Teilchen in Feldern', ['Lorentzkraft']),
          topic('ph-j11lk-lb9-lorentz', 'Lorentzkraft', ['Lorentz']),
          topic('ph-j11lk-lb9-bahn', 'Kreisbahn im B-Feld', ['Bahn']),
          topic('ph-j11lk-lb9-anwendung', 'Massenspektrometer (Einblick)', ['Anwendung']),
        ]),
        area('lb10', 'Elektromagnetische Induktion', 15, [
          topic('ph-j11lk-lb10-fluss', 'Magnetischer Fluss', ['Fluss']),
          topic('ph-j11lk-lb10-induktion', 'Elektromagnetische Induktion', ['Induktion']),
          topic('ph-j11lk-lb10-lenz', 'Lenzsche Regel', ['Lenz']),
          topic('ph-j11lk-lb10-generator', 'Generator', ['Generator']),
          topic('ph-j11lk-lb10-transformator', 'Transformator (Einblick)', ['Transformator']),
        ]),
        area('lb11', 'Physikalisches Praktikum', 13, [
          topic('ph-j11lk-lb11-planung', 'Versuch planen', ['Versuch']),
          topic('ph-j11lk-lb11-praktikum', 'Physikalisches Praktikum', ['Praktikum']),
          topic('ph-j11lk-lb11-messung', 'Messen', ['Messung']),
          topic('ph-j11lk-lb11-auswertung', 'Auswertung', ['Auswertung']),
          topic('ph-j11lk-lb11-unsicherheit', 'Messunsicherheit', ['Unsicherheit']),
        ]),
        area('lbw', 'Wahlbereiche', undefined, [
          topic('ph-j11lk-lbw-fahren', 'Physik des Fahrens', ['Fahren']),
          topic('ph-j11lk-lbw-bremsen', 'Bremsweg', ['Bremsweg']),
          topic('ph-j11lk-lbw-halbleiter', 'Leitungsvorgänge in Halbleitern', ['Halbleiter']),
          topic('ph-j11lk-lbw-diode', 'pn-Übergang', ['Diode']),
          topic('ph-j11lk-lbw-messen', 'Messen und Modellieren', ['Messen']),
          topic('ph-j11lk-lbw-kalibrierung', 'Kalibrierung', ['Kalibrierung']),
        ]),
      ],
    ),
    grade(
      'physik-jgs-12-lk',
      'Jahrgangsstufe 12 · Leistungskurs',
      'JGS 12 · Leistungskurs',
      'Schwingungen und Wellen, Quanten- und Atomphysik, Thermodynamik.',
      ['Schwingung', 'Welle', 'Quanten', 'Atomkern', 'Thermodynamik'],
      [
        area('lb1', 'Mechanische und elektromagnetische Schwingungen', 22, [
          topic('ph-j12lk-lb1-harmonisch', 'Harmonische Schwingung', ['Schwingung']),
          topic('ph-j12lk-lb1-schwingung', 'Mechanische und elektromagnetische Schwingungen', ['Schwingung']),
          topic('ph-j12lk-lb1-pendel', 'Pendel und Feder', ['Pendel']),
          topic('ph-j12lk-lb1-lc', 'LC-Schwingkreis', ['LC']),
          topic('ph-j12lk-lb1-energie', 'Energie in Schwingungen', ['Energie']),
          topic('ph-j12lk-lb1-resonanz', 'Resonanz', ['Resonanz']),
        ]),
        area('lb2', 'Wellen als vielschichtige Naturerscheinung', 15, [
          topic('ph-j12lk-lb2-typen', 'Longitudinal und transversal', ['Welle']),
          topic('ph-j12lk-lb2-wellen', 'Wellen als vielschichtige Naturerscheinung', ['Welle']),
          topic('ph-j12lk-lb2-cf', 'c = λ·f', ['Wellenlänge']),
          topic('ph-j12lk-lb2-interferenz', 'Interferenz', ['Interferenz']),
          topic('ph-j12lk-lb2-beugung', 'Beugung', ['Beugung']),
          topic('ph-j12lk-lb2-stehend', 'Stehende Wellen', ['Stehende Welle']),
        ]),
        area('lb4', 'Grundlagen der Quantenphysik', 15, [
          topic('ph-j12lk-lb4-photo', 'Photoeffekt', ['Photoeffekt']),
          topic('ph-j12lk-lb4-quanten', 'Grundlagen der Quantenphysik', ['Quantenphysik']),
          topic('ph-j12lk-lb4-photon', 'Photonen', ['Photon']),
          topic('ph-j12lk-lb4-unschaerfe', 'Unschärferelation (Einblick)', ['Unschärfe']),
          topic('ph-j12lk-lb4-dualismus', 'Dualismus', ['Dualismus']),
        ]),
        area('lb5', 'Grundlagen der Atomphysik', 18, [
          topic('ph-j12lk-lb5-bohr', 'Bohrsches Atommodell', ['Bohr']),
          topic('ph-j12lk-lb5-atom', 'Grundlagen der Atomphysik', ['Atomphysik']),
          topic('ph-j12lk-lb5-spektrum', 'Spektrallinien', ['Spektrum']),
          topic('ph-j12lk-lb5-niveaus', 'Energieniveaus', ['Niveau']),
          topic('ph-j12lk-lb5-anregung', 'Anregung und Emission', ['Emission']),
        ]),
        area('lb6', 'Eigenschaften der Atomkerne', 17, [
          topic('ph-j12lk-lb6-aufbau', 'Aufbau der Kerne', ['Kern']),
          topic('ph-j12lk-lb6-kerne', 'Eigenschaften der Atomkerne', ['Kernphysik']),
          topic('ph-j12lk-lb6-zerfall', 'Zerfallsarten', ['Zerfall']),
          topic('ph-j12lk-lb6-halbwert', 'Halbwertszeit', ['Halbwertszeit']),
          topic('ph-j12lk-lb6-bindung', 'Bindungsenergie (Einblick)', ['Bindung']),
          topic('ph-j12lk-lb6-spaltung', 'Spaltung und Fusion', ['Spaltung']),
        ]),
        area('lb7', 'Thermodynamik', 15, [
          topic('ph-j12lk-lb7-gas', 'Ideales Gas', ['Gas']),
          topic('ph-j12lk-lb7-thermo', 'Thermodynamik', ['Thermodynamik']),
          topic('ph-j12lk-lb7-hs1', '1. Hauptsatz', ['Hauptsatz']),
          topic('ph-j12lk-lb7-hs2', '2. Hauptsatz (Einblick)', ['Entropie']),
          topic('ph-j12lk-lb7-prozess', 'Zustandsänderungen', ['Prozess']),
        ]),
        area('lbw', 'Wahlbereiche', undefined, [
          topic('ph-j12lk-lbw-chaos', 'Deterministisches Chaos', ['Chaos']),
          topic('ph-j12lk-lbw-anfang', 'Anfangsbedingungen', ['Chaos']),
          topic('ph-j12lk-lbw-gas', 'Kinetische Gastheorie', ['Gastheorie']),
          topic('ph-j12lk-lbw-druck', 'Druck aus Teilchenmodell', ['Druck']),
          topic('ph-j12lk-lbw-anwendungen', 'Anwendungen der Physik', ['Anwendung']),
          topic('ph-j12lk-lbw-technik', 'Technische Beispiele', ['Technik']),
        ]),
      ],
    ),
  ]
}
